repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: ^check-deps/action\.yml$
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: scripts/lint.sh
        language: script
        pass_filenames: false
        always_run: true
      - id: fmt
        name: fmt
        entry: scripts/fmt.sh
        language: script
        pass_filenames: false
        always_run: true

  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.11
    hooks:
      - id: actionlint
