"""The CLI stream contract, driven from ``schema/cli-streams.yml``.

This is the shared table both ports must satisfy: for a given command (and,
where the rule is conditional, a given flag combination) exactly one of
``stdout``/``stderr`` carries the described output. The TypeScript mirror is
``packages/typescript/src/cli/streams.test.ts``.

Every case below invokes the real command and asks the table which stream the
row's marker text belongs on, rather than hard-coding "stdout" or "stderr" in
the assertion. Corrupting a row in ``schema/cli-streams.yml`` therefore fails
the corresponding case here *and* the TypeScript mirror, which is the whole
point of a shared oracle: see docs/issues/24-conformance-gaps-is-inert.md for
what happens to a table nothing actually reads.

``click.testing.Result.output`` (Python) mixes stdout and stderr in write
order, so it cannot stand in for either column here -- every assertion below
reads ``result.stdout``/``result.stderr`` directly, indexed through the row.
"""

from __future__ import annotations

from pathlib import Path
from unittest.mock import patch

from ruamel.yaml import YAML
from typer.testing import CliRunner

from ghagen.cli.main import app
from ghagen.pin.engine import PinReport, ResolvedPin
from ghagen_schema.paths import SCHEMA_DIR

runner = CliRunner()

_TABLE: dict[str, dict[str, str]] = {
    row["id"]: row
    for row in YAML(typ="safe").load((SCHEMA_DIR / "cli-streams.yml").read_text())
}

assert _TABLE, "schema/cli-streams.yml is empty -- every case below would be vacuous"


def _stream(result, row_id: str) -> str:
    """The text of the stream ``schema/cli-streams.yml`` names for *row_id*."""
    return result.stdout if _TABLE[row_id]["stream"] == "stdout" else result.stderr


def _other_stream(result, row_id: str) -> str:
    """The text of the *other* stream -- what the marker must be absent from."""
    return result.stderr if _TABLE[row_id]["stream"] == "stdout" else result.stdout


_CONFIG = """\
from ghagen import App, Job, On, PushTrigger, Step, Workflow

app = App()
ci = Workflow(
    name="CI",
    on=On(push=PushTrigger(branches=["main"])),
    jobs={"test": Job(
        runs_on="ubuntu-latest",
        steps=[Step(uses="actions/checkout@v4")],
    )},
)
app.add_workflow(ci, "ci.yml")
"""

_LOCKFILE = """\
# Auto-generated by `ghagen deps pin`. Do not edit manually.

pins:
  actions/checkout@v4:
    sha: "0123456789abcdef0123456789abcdef01234567"
    resolved_at: "2026-04-09T00:00:00+00:00"
"""

_UPGRADE_CONFIG = """\
from ghagen import App, Job, On, PushTrigger, Step, Workflow

app = App()
ci = Workflow(
    name="CI",
    on=On(push=PushTrigger(branches=["main"])),
    jobs={"test": Job(
        runs_on="ubuntu-latest",
        steps=[
            Step(uses="actions/checkout@v4"),
            Step(uses="actions/setup-python@v5"),
        ],
    )},
)
app.add_workflow(ci, "ci.yml")
"""

_CHECKOUT_TAGS = ["v1", "v2", "v3", "v4", "v5", "v6", "v7"]
_SETUP_PYTHON_TAGS = ["v4", "v5", "v5.1.0", "v6", "v7"]


def _mock_list_tags(owner: str, repo: str, *, token=None) -> list[str]:
    if repo == "checkout":
        return _CHECKOUT_TAGS
    if repo == "setup-python":
        return _SETUP_PYTHON_TAGS
    return []


def _mock_track_user_files(config_path):
    from ghagen.cli._common import _load_app

    loaded_app = _load_app(config_path)
    root = loaded_app.root
    config = root / "ghagen_config.py"
    files = {config} if config.is_file() else set()
    return loaded_app, files


# -- synth / check-synced / init (top-level) ---------------------------------


def test_synth_success_stream(tmp_path: Path, monkeypatch: object):
    monkeypatch.chdir(tmp_path)  # type: ignore[attr-defined]
    (tmp_path / "ghagen_config.py").write_text(_CONFIG)

    result = runner.invoke(app, ["synth"])
    assert result.exit_code == 0, (result.stdout, result.stderr)
    assert "Synthesized 1" in _stream(result, "synth-success")
    assert "Synthesized 1" not in _other_stream(result, "synth-success")


def test_synth_config_not_found_stream(tmp_path: Path, monkeypatch: object):
    monkeypatch.chdir(tmp_path)  # type: ignore[attr-defined]

    result = runner.invoke(app, ["synth"])
    assert result.exit_code == 1
    assert "no config file found" in _stream(result, "synth-config-not-found")
    assert "no config file found" not in _other_stream(result, "synth-config-not-found")


def test_check_synced_top_level_in_sync_stream(tmp_path: Path, monkeypatch: object):
    monkeypatch.chdir(tmp_path)  # type: ignore[attr-defined]
    (tmp_path / "ghagen_config.py").write_text(_CONFIG)
    assert runner.invoke(app, ["synth"]).exit_code == 0

    result = runner.invoke(app, ["check-synced"])
    assert result.exit_code == 0, (result.stdout, result.stderr)
    assert "up-to-date" in _stream(result, "check-synced-top-level-in-sync")
    assert "up-to-date" not in _other_stream(result, "check-synced-top-level-in-sync")


def test_check_synced_top_level_stale_stream(tmp_path: Path, monkeypatch: object):
    monkeypatch.chdir(tmp_path)  # type: ignore[attr-defined]
    (tmp_path / "ghagen_config.py").write_text(_CONFIG)
    (tmp_path / ".github" / "workflows").mkdir(parents=True)
    (tmp_path / ".github" / "workflows" / "ci.yml").write_text("# stale content\n")

    result = runner.invoke(app, ["check-synced"])
    assert result.exit_code == 1
    assert "out of date" in _stream(result, "check-synced-top-level-stale")
    assert "out of date" not in _other_stream(result, "check-synced-top-level-stale")


def test_init_success_stream(tmp_path: Path, monkeypatch: object):
    monkeypatch.chdir(tmp_path)  # type: ignore[attr-defined]

    result = runner.invoke(app, ["init"])
    assert result.exit_code == 0, (result.stdout, result.stderr)
    assert "Created" in _stream(result, "init-success")
    assert "Created" not in _other_stream(result, "init-success")


def test_init_already_exists_stream(tmp_path: Path, monkeypatch: object):
    monkeypatch.chdir(tmp_path)  # type: ignore[attr-defined]
    (tmp_path / ".github").mkdir()
    (tmp_path / ".github" / "ghagen_workflows.py").write_text("# existing")

    result = runner.invoke(app, ["init"])
    assert result.exit_code == 1
    assert "already exists" in _stream(result, "init-already-exists")
    assert "already exists" not in _other_stream(result, "init-already-exists")


# -- deps check-synced ---------------------------------------------------------


def test_deps_check_synced_in_sync_stream(tmp_path: Path, monkeypatch: object):
    monkeypatch.chdir(tmp_path)  # type: ignore[attr-defined]
    monkeypatch.delenv("GITHUB_TOKEN", raising=False)  # type: ignore[attr-defined]
    monkeypatch.delenv("GH_TOKEN", raising=False)  # type: ignore[attr-defined]
    (tmp_path / "ghagen_config.py").write_text(_CONFIG)
    (tmp_path / ".ghagen.lock.yml").write_text(_LOCKFILE)

    result = runner.invoke(app, ["deps", "check-synced"])
    assert result.exit_code == 0, (result.stdout, result.stderr)
    assert "Lockfile is in sync." in _stream(result, "deps-check-synced-in-sync")
    assert "Lockfile is in sync." not in _other_stream(
        result, "deps-check-synced-in-sync"
    )


def test_deps_check_synced_missing_stream(tmp_path: Path, monkeypatch: object):
    monkeypatch.chdir(tmp_path)  # type: ignore[attr-defined]
    monkeypatch.delenv("GITHUB_TOKEN", raising=False)  # type: ignore[attr-defined]
    monkeypatch.delenv("GH_TOKEN", raising=False)  # type: ignore[attr-defined]
    (tmp_path / "ghagen_config.py").write_text(_CONFIG)
    (tmp_path / ".ghagen.lock.yml").write_text("# empty\n")

    result = runner.invoke(app, ["deps", "check-synced"])
    assert result.exit_code == 1
    assert "Missing lockfile entries" in _stream(result, "deps-check-synced-missing")
    assert "Missing lockfile entries" not in _other_stream(
        result, "deps-check-synced-missing"
    )


# -- deps pin -------------------------------------------------------------------


def test_deps_pin_resolved_stream(tmp_path: Path, monkeypatch: object):
    monkeypatch.chdir(tmp_path)  # type: ignore[attr-defined]
    monkeypatch.setenv("GITHUB_TOKEN", "fake-token")  # type: ignore[attr-defined]
    (tmp_path / "ghagen_config.py").write_text(_CONFIG)

    report = PinReport(
        resolved=[
            ResolvedPin(uses="actions/checkout@v4", sha="0" * 40),
        ],
        written=True,
        lockfile_path=tmp_path / ".ghagen.lock.yml",
    )
    with patch("ghagen.pin.engine.pin", return_value=report):
        result = runner.invoke(app, ["deps", "pin"])

    assert result.exit_code == 0, (result.stdout, result.stderr)
    assert "actions/checkout@v4" in _stream(result, "deps-pin-resolved")
    assert "actions/checkout@v4" not in _other_stream(result, "deps-pin-resolved")


def test_deps_pin_no_token_warning_stream(tmp_path: Path, monkeypatch: object):
    monkeypatch.chdir(tmp_path)  # type: ignore[attr-defined]
    monkeypatch.delenv("GITHUB_TOKEN", raising=False)  # type: ignore[attr-defined]
    monkeypatch.delenv("GH_TOKEN", raising=False)  # type: ignore[attr-defined]
    (tmp_path / "ghagen_config.py").write_text(_CONFIG)

    report = PinReport(lockfile_path=tmp_path / ".ghagen.lock.yml", up_to_date=True)
    with patch("ghagen.pin.engine.pin", return_value=report):
        result = runner.invoke(app, ["deps", "pin"])

    assert result.exit_code == 0, (result.stdout, result.stderr)
    assert "no GitHub token found" in _stream(result, "deps-pin-no-token-warning")
    assert "no GitHub token found" not in _other_stream(
        result, "deps-pin-no-token-warning"
    )


# -- deps upgrade -----------------------------------------------------------


class TestDepsUpgradeStreams:
    @patch("ghagen.pin.sources.track_user_files", side_effect=_mock_track_user_files)
    @patch("ghagen.pin.github.GitHubClient.list_tags", side_effect=_mock_list_tags)
    def test_report_always_on_stdout(
        self, mock_tags, mock_track, tmp_path, monkeypatch
    ):
        """The rendered report owns stdout whether or not --format is passed."""
        monkeypatch.chdir(tmp_path)
        monkeypatch.setenv("GITHUB_TOKEN", "fake-token")
        (tmp_path / "ghagen_config.py").write_text(_UPGRADE_CONFIG)

        result = runner.invoke(
            app,
            ["deps", "upgrade", "--mode", "versions", "--format", "json", "--check"],
        )
        assert result.exit_code == 0, (result.stdout, result.stderr)
        assert '"version_bumps"' in _stream(result, "deps-upgrade-report")
        assert '"version_bumps"' not in _other_stream(result, "deps-upgrade-report")

    @patch("ghagen.pin.sources.track_user_files", side_effect=_mock_track_user_files)
    def test_warning_always_on_stderr(self, mock_track, tmp_path, monkeypatch):
        monkeypatch.chdir(tmp_path)
        monkeypatch.setenv("GITHUB_TOKEN", "fake-token")
        (tmp_path / "ghagen_config.py").write_text(_UPGRADE_CONFIG)

        from ghagen.pin.github import ResolveError

        def mock_tags_with_error(owner, repo, *, token=None):
            if repo == "checkout":
                raise ResolveError("rate limited")
            return _SETUP_PYTHON_TAGS

        with patch(
            "ghagen.pin.github.GitHubClient.list_tags", side_effect=mock_tags_with_error
        ):
            result = runner.invoke(
                app,
                [
                    "deps",
                    "upgrade",
                    "--mode",
                    "versions",
                    "--format",
                    "json",
                    "--check",
                ],
            )

        assert result.exit_code == 0, (result.stdout, result.stderr)
        assert "warning:" in _stream(result, "deps-upgrade-warning")
        assert "warning:" not in _other_stream(result, "deps-upgrade-warning")

    @patch("ghagen.pin.sources.track_user_files", side_effect=_mock_track_user_files)
    @patch("ghagen.pin.github.GitHubClient.list_tags", side_effect=_mock_list_tags)
    def test_progress_note_without_format_is_stdout(
        self, mock_tags, mock_track, tmp_path, monkeypatch
    ):
        monkeypatch.chdir(tmp_path)
        monkeypatch.setenv("GITHUB_TOKEN", "fake-token")
        (tmp_path / "ghagen_config.py").write_text(_UPGRADE_CONFIG)

        result = runner.invoke(app, ["deps", "upgrade", "--mode", "versions"])
        assert result.exit_code == 0, (result.stdout, result.stderr)
        row = "deps-upgrade-progress-note-no-format"
        assert "Applied version bumps" in _stream(result, row)
        assert "Applied version bumps" not in _other_stream(result, row)

    @patch("ghagen.pin.sources.track_user_files", side_effect=_mock_track_user_files)
    @patch("ghagen.pin.github.GitHubClient.list_tags", side_effect=_mock_list_tags)
    def test_progress_note_with_format_is_stderr(
        self, mock_tags, mock_track, tmp_path, monkeypatch
    ):
        """The H6 hotfix: --format flips the progress note off stdout."""
        monkeypatch.chdir(tmp_path)
        monkeypatch.setenv("GITHUB_TOKEN", "fake-token")
        (tmp_path / "ghagen_config.py").write_text(_UPGRADE_CONFIG)

        result = runner.invoke(
            app, ["deps", "upgrade", "--mode", "versions", "--format", "json"]
        )
        assert result.exit_code == 0, (result.stdout, result.stderr)
        row = "deps-upgrade-progress-note-with-format"
        assert "Applied version bumps" in _stream(result, row)
        assert "Applied version bumps" not in _other_stream(result, row)


# -- deps update --------------------------------------------------------------

_LOCKFILE_NONE_CONFIG = """\
from ghagen import App, Job, On, PushTrigger, Step, Workflow

app = App(lockfile=None)
ci = Workflow(
    name="CI",
    on=On(push=PushTrigger(branches=["main"])),
    jobs={"test": Job(
        runs_on="ubuntu-latest",
        steps=[Step(uses="actions/checkout@v4")],
    )},
)
app.add_workflow(ci, "ci.yml")
"""


class TestDepsUpdateStreams:
    @patch("ghagen.pin.sources.track_user_files", side_effect=_mock_track_user_files)
    @patch("ghagen.pin.github.GitHubClient.list_tags", side_effect=_mock_list_tags)
    def test_plan_always_on_stdout(self, mock_tags, mock_track, tmp_path, monkeypatch):
        """The plan owns stdout under both --format github and --format json."""
        monkeypatch.chdir(tmp_path)
        monkeypatch.setenv("GITHUB_TOKEN", "fake-token")
        (tmp_path / "ghagen_config.py").write_text(_LOCKFILE_NONE_CONFIG)

        for fmt in ("github", "json"):
            result = runner.invoke(
                app, ["deps", "update", "--dry-run", "--format", fmt]
            )
            assert result.exit_code == 0, (fmt, result.stdout, result.stderr)
            marker = '"action"' if fmt == "json" else "action="
            assert marker in _stream(result, "deps-update-plan"), fmt
            assert marker not in _other_stream(result, "deps-update-plan"), fmt

    @patch("ghagen.pin.sources.track_user_files", side_effect=_mock_track_user_files)
    def test_warning_always_on_stderr(self, mock_track, tmp_path, monkeypatch):
        monkeypatch.chdir(tmp_path)
        monkeypatch.setenv("GITHUB_TOKEN", "fake-token")
        (tmp_path / "ghagen_config.py").write_text(_LOCKFILE_NONE_CONFIG)

        from ghagen.pin.github import ResolveError

        def mock_tags_with_error(owner, repo, *, token=None):
            raise ResolveError("rate limited")

        with patch(
            "ghagen.pin.github.GitHubClient.list_tags", side_effect=mock_tags_with_error
        ):
            result = runner.invoke(
                app, ["deps", "update", "--dry-run", "--format", "json"]
            )

        assert result.exit_code == 0, (result.stdout, result.stderr)
        assert "warning:" in _stream(result, "deps-update-warning")
        assert "warning:" not in _other_stream(result, "deps-update-warning")

    @patch("ghagen.pin.sources.track_user_files", side_effect=_mock_track_user_files)
    @patch("ghagen.pin.github.GitHubClient.list_tags", side_effect=_mock_list_tags)
    def test_modified_note_always_on_stderr(
        self, mock_tags, mock_track, tmp_path, monkeypatch
    ):
        """Unlike deps upgrade, this note is always stderr -- no --format branch."""
        monkeypatch.chdir(tmp_path)
        monkeypatch.setenv("GITHUB_TOKEN", "fake-token")
        (tmp_path / "ghagen_config.py").write_text(_LOCKFILE_NONE_CONFIG)

        result = runner.invoke(app, ["deps", "update", "--format", "json"])
        assert result.exit_code == 0, (result.stdout, result.stderr)
        row = "deps-update-modified-note"
        assert "modified" in _stream(result, row)
        assert "modified" not in _other_stream(result, row)
