"""Tests for the ``ghagen deps`` CLI subcommands."""

from __future__ import annotations

from pathlib import Path

from typer.testing import CliRunner

from ghagen.cli.main import app

runner = CliRunner()


_CONFIG = """\
from ghagen import App, Job, On, PushTrigger, Step, Workflow

app = App()
ci = Workflow(
    name="CI",
    on=On(push=PushTrigger(branches=["main"])),
    jobs={"test": Job(
        runs_on="ubuntu-latest",
        steps=[Step(uses="actions/checkout@v4")],
    )},
)
app.add_workflow(ci, "ci.yml")
"""


_LOCKFILE = """\
# Auto-generated by `ghagen pin`. Do not edit manually.

[pins."actions/checkout@v4"]
sha = "0123456789abcdef0123456789abcdef01234567"
resolved_at = "2026-04-09T00:00:00+00:00"
"""


def test_deps_check_synced_passes_when_lockfile_in_sync(
    tmp_path: Path, monkeypatch: object
):
    monkeypatch.chdir(tmp_path)  # type: ignore[attr-defined]
    monkeypatch.delenv("GITHUB_TOKEN", raising=False)  # type: ignore[attr-defined]
    monkeypatch.delenv("GH_TOKEN", raising=False)  # type: ignore[attr-defined]

    (tmp_path / "ghagen_config.py").write_text(_CONFIG)
    lockfile = tmp_path / ".github" / "ghagen.lock.toml"
    lockfile.parent.mkdir(parents=True)
    lockfile.write_text(_LOCKFILE)

    result = runner.invoke(app, ["deps", "check-synced"])
    assert result.exit_code == 0, result.output
    assert "Lockfile is in sync." in result.output
    # check-synced never hits the network, so the no-token warning must NOT fire.
    assert "no GitHub token found" not in result.output


def test_deps_check_synced_fails_when_entry_missing(
    tmp_path: Path, monkeypatch: object
):
    monkeypatch.chdir(tmp_path)  # type: ignore[attr-defined]
    monkeypatch.delenv("GITHUB_TOKEN", raising=False)  # type: ignore[attr-defined]
    monkeypatch.delenv("GH_TOKEN", raising=False)  # type: ignore[attr-defined]

    (tmp_path / "ghagen_config.py").write_text(_CONFIG)
    # Deliberately create an empty lockfile so the check sees a missing entry.
    lockfile = tmp_path / ".github" / "ghagen.lock.toml"
    lockfile.parent.mkdir(parents=True)
    lockfile.write_text("# empty\n")

    result = runner.invoke(app, ["deps", "check-synced"])
    assert result.exit_code == 1
    assert "Missing lockfile entries" in result.output
    assert "actions/checkout@v4" in result.output
    assert "no GitHub token found" not in result.output


def test_deps_check_synced_fails_on_stale_entry_with_prune(
    tmp_path: Path, monkeypatch: object
):
    monkeypatch.chdir(tmp_path)  # type: ignore[attr-defined]
    monkeypatch.delenv("GITHUB_TOKEN", raising=False)  # type: ignore[attr-defined]
    monkeypatch.delenv("GH_TOKEN", raising=False)  # type: ignore[attr-defined]

    # Config references only checkout; lockfile has an extra unused entry.
    (tmp_path / "ghagen_config.py").write_text(_CONFIG)
    lockfile = tmp_path / ".github" / "ghagen.lock.toml"
    lockfile.parent.mkdir(parents=True)
    lockfile.write_text(
        _LOCKFILE
        + """
[pins."actions/unused@v1"]
sha = "fedcba9876543210fedcba9876543210fedcba98"
resolved_at = "2026-04-09T00:00:00+00:00"
"""
    )

    result = runner.invoke(app, ["deps", "check-synced"])
    assert result.exit_code == 1
    assert "Stale lockfile entries" in result.output
    assert "actions/unused@v1" in result.output
