"""Tests for the ``ghagen deps`` CLI subcommands."""

from __future__ import annotations

import json
from pathlib import Path
from unittest.mock import patch

from typer.testing import CliRunner

from ghagen.cli.deps import _bump_to_json, _stale_to_json
from ghagen.cli.main import app
from ghagen.pin.engine import LockfileStaleEntry, VersionBump

runner = CliRunner()


def _repo_root() -> Path:
    """Walk up to find the repo root (directory containing the shared fixtures)."""
    d = Path(__file__).resolve().parent
    while d != d.parent:
        if (d / "fixtures" / "expected").is_dir():
            return d
        d = d.parent
    raise RuntimeError("Cannot find repo root (directory containing fixtures/expected)")


FIXTURES_DIR = _repo_root() / "fixtures" / "expected"


_CONFIG = """\
from ghagen import App, Job, On, PushTrigger, Step, Workflow

app = App()
ci = Workflow(
    name="CI",
    on=On(push=PushTrigger(branches=["main"])),
    jobs={"test": Job(
        runs_on="ubuntu-latest",
        steps=[Step(uses="actions/checkout@v4")],
    )},
)
app.add_workflow(ci, "ci.yml")
"""


_LOCKFILE = """\
# Auto-generated by `ghagen pin`. Do not edit manually.

pins:
  actions/checkout@v4:
    sha: "0123456789abcdef0123456789abcdef01234567"
    resolved_at: "2026-04-09T00:00:00+00:00"
"""


def test_deps_check_synced_passes_when_lockfile_in_sync(
    tmp_path: Path, monkeypatch: object
):
    monkeypatch.chdir(tmp_path)  # type: ignore[attr-defined]
    monkeypatch.delenv("GITHUB_TOKEN", raising=False)  # type: ignore[attr-defined]
    monkeypatch.delenv("GH_TOKEN", raising=False)  # type: ignore[attr-defined]

    (tmp_path / "ghagen_config.py").write_text(_CONFIG)
    lockfile = tmp_path / ".ghagen.lock.yml"
    lockfile.write_text(_LOCKFILE)

    result = runner.invoke(app, ["deps", "check-synced"])
    assert result.exit_code == 0, result.output
    assert "Lockfile is in sync." in result.output
    # check-synced never hits the network, so the no-token warning must NOT fire.
    assert "no GitHub token found" not in result.output


def test_deps_check_synced_fails_when_entry_missing(
    tmp_path: Path, monkeypatch: object
):
    monkeypatch.chdir(tmp_path)  # type: ignore[attr-defined]
    monkeypatch.delenv("GITHUB_TOKEN", raising=False)  # type: ignore[attr-defined]
    monkeypatch.delenv("GH_TOKEN", raising=False)  # type: ignore[attr-defined]

    (tmp_path / "ghagen_config.py").write_text(_CONFIG)
    # Deliberately create an empty lockfile so the check sees a missing entry.
    lockfile = tmp_path / ".ghagen.lock.yml"
    lockfile.write_text("# empty\n")

    result = runner.invoke(app, ["deps", "check-synced"])
    assert result.exit_code == 1
    assert "Missing lockfile entries" in result.output
    assert "actions/checkout@v4" in result.output
    assert "no GitHub token found" not in result.output


def test_deps_check_synced_fails_on_stale_entry_with_prune(
    tmp_path: Path, monkeypatch: object
):
    monkeypatch.chdir(tmp_path)  # type: ignore[attr-defined]
    monkeypatch.delenv("GITHUB_TOKEN", raising=False)  # type: ignore[attr-defined]
    monkeypatch.delenv("GH_TOKEN", raising=False)  # type: ignore[attr-defined]

    # Config references only checkout; lockfile has an extra unused entry.
    (tmp_path / "ghagen_config.py").write_text(_CONFIG)
    lockfile = tmp_path / ".ghagen.lock.yml"
    lockfile.write_text(
        _LOCKFILE
        + "  actions/unused@v1:\n"
        + '    sha: "fedcba9876543210fedcba9876543210fedcba98"\n'
        + '    resolved_at: "2026-04-09T00:00:00+00:00"\n'
    )

    result = runner.invoke(app, ["deps", "check-synced"])
    assert result.exit_code == 1
    assert "Stale lockfile entries" in result.output
    assert "actions/unused@v1" in result.output


# -- deps upgrade ------------------------------------------------------------
#
# Exercises the ``ghagen deps upgrade`` CLI command end to end via CliRunner
# (network calls are patched out). This is CLI-surface coverage — argument
# parsing, --mode/--json/--check flags, human vs. JSON rendering, and token
# resolution. Engine-level behavior of ``ghagen.pin.engine.upgrade`` itself is
# covered directly (no CLI) in ``tests/test_pin/test_engine.py::TestUpgrade``.

_UPGRADE_CONFIG = """\
from ghagen import App, Job, On, PushTrigger, Step, Workflow

app = App()
ci = Workflow(
    name="CI",
    on=On(push=PushTrigger(branches=["main"])),
    jobs={"test": Job(
        runs_on="ubuntu-latest",
        steps=[
            Step(uses="actions/checkout@v4"),
            Step(uses="actions/setup-python@v5"),
        ],
    )},
)
app.add_workflow(ci, "ci.yml")
"""


_UPGRADE_LOCKFILE = """\
# Auto-generated by `ghagen pin`. Do not edit manually.

pins:
  actions/checkout@v4:
    sha: "0123456789abcdef0123456789abcdef01234567"
    resolved_at: "2026-04-09T00:00:00+00:00"
  actions/setup-python@v5:
    sha: "abcdef0123456789abcdef0123456789abcdef01"
    resolved_at: "2026-04-09T00:00:00+00:00"
"""

# Common mock values
_CHECKOUT_TAGS = ["v1", "v2", "v3", "v4", "v5", "v6", "v7"]
_SETUP_PYTHON_TAGS = ["v4", "v5", "v5.1.0", "v6", "v7"]
_NEW_CHECKOUT_SHA = "f" * 40
_NEW_SETUP_PY_SHA = "e" * 40


def _setup_upgrade_project(tmp_path: Path, *, with_lockfile: bool = False) -> Path:
    """Write a config file and optionally a lockfile; return the config path."""
    config_path = tmp_path / "ghagen_config.py"
    config_path.write_text(_UPGRADE_CONFIG)
    if with_lockfile:
        lockfile = tmp_path / ".ghagen.lock.yml"
        lockfile.write_text(_UPGRADE_LOCKFILE)
    return config_path


def _mock_list_tags(owner: str, repo: str, *, token=None) -> list[str]:
    """Return fake tags for known repos."""
    if repo == "checkout":
        return _CHECKOUT_TAGS
    if repo == "setup-python":
        return _SETUP_PYTHON_TAGS
    return []


def _mock_resolve_ref(owner: str, repo: str, ref: str, *, token=None) -> str:
    """Return a fake SHA that differs from the lockfile entries."""
    if repo == "checkout":
        return _NEW_CHECKOUT_SHA
    if repo == "setup-python":
        return _NEW_SETUP_PY_SHA
    return "0" * 40


def _mock_track_user_files(config_path, app_loader):
    """Load the app and return ``(app, files)`` with the config file tracked."""
    loaded_app = app_loader(config_path)
    # Return the config file based on the root -- in tests we write
    # ghagen_config.py in tmp_path which is also the cwd.
    root = loaded_app.root
    config = root / "ghagen_config.py"
    files = {config} if config.is_file() else set()
    return loaded_app, files


class TestUpgradeVersionsMode:
    """Tests for version bump detection."""

    @patch("ghagen.pin.sources.track_user_files", side_effect=_mock_track_user_files)
    @patch("ghagen.pin.github.GitHubClient.list_tags", side_effect=_mock_list_tags)
    def test_human_output_shows_version_bumps(
        self, mock_tags, mock_track, tmp_path, monkeypatch
    ):
        monkeypatch.chdir(tmp_path)
        monkeypatch.setenv("GITHUB_TOKEN", "fake-token")
        _setup_upgrade_project(tmp_path)

        result = runner.invoke(
            app, ["deps", "upgrade", "--mode", "versions", "--check"]
        )
        assert result.exit_code == 0, result.output
        assert "Version updates available" in result.output
        assert "actions/checkout@v4" in result.output
        assert "v5" in result.output
        assert "[major]" in result.output

    @patch("ghagen.pin.sources.track_user_files", side_effect=_mock_track_user_files)
    @patch("ghagen.pin.github.GitHubClient.list_tags", side_effect=_mock_list_tags)
    def test_json_output(self, mock_tags, mock_track, tmp_path, monkeypatch):
        monkeypatch.chdir(tmp_path)
        monkeypatch.setenv("GITHUB_TOKEN", "fake-token")
        _setup_upgrade_project(tmp_path)

        result = runner.invoke(
            app, ["deps", "upgrade", "--mode", "versions", "--json", "--check"]
        )
        assert result.exit_code == 0, result.output
        data = json.loads(result.output)
        assert "version_bumps" in data
        bumps = data["version_bumps"]
        assert len(bumps) >= 1
        # Check structure of a bump entry
        bump = bumps[0]
        assert "uses" in bump
        assert "current" in bump
        assert "latest" in bump
        assert "severity" in bump

    @patch("ghagen.pin.sources.track_user_files", side_effect=_mock_track_user_files)
    @patch("ghagen.pin.github.GitHubClient.list_tags", side_effect=_mock_list_tags)
    def test_json_output_has_source_files_for_user_refs(
        self, mock_tags, mock_track, tmp_path, monkeypatch
    ):
        monkeypatch.chdir(tmp_path)
        monkeypatch.setenv("GITHUB_TOKEN", "fake-token")
        _setup_upgrade_project(tmp_path)

        result = runner.invoke(
            app, ["deps", "upgrade", "--mode", "versions", "--json", "--check"]
        )
        assert result.exit_code == 0, result.output
        data = json.loads(result.output)
        for bump in data["version_bumps"]:
            assert "source_files" in bump
            assert len(bump["source_files"]) > 0


class TestUpgradeLockfileMode:
    """Tests for lockfile staleness detection."""

    @patch("ghagen.pin.sources.track_user_files", side_effect=_mock_track_user_files)
    @patch("ghagen.pin.github.GitHubClient.resolve_ref", side_effect=_mock_resolve_ref)
    def test_lockfile_stale_detection(
        self, mock_resolve, mock_track, tmp_path, monkeypatch
    ):
        monkeypatch.chdir(tmp_path)
        monkeypatch.setenv("GITHUB_TOKEN", "fake-token")
        _setup_upgrade_project(tmp_path, with_lockfile=True)

        result = runner.invoke(
            app, ["deps", "upgrade", "--mode", "lockfile", "--check"]
        )
        assert result.exit_code == 0, result.output
        assert "Stale lockfile entries" in result.output
        assert "actions/checkout@v4" in result.output

    @patch("ghagen.pin.sources.track_user_files", side_effect=_mock_track_user_files)
    @patch("ghagen.pin.github.GitHubClient.resolve_ref", side_effect=_mock_resolve_ref)
    def test_lockfile_json_output(
        self, mock_resolve, mock_track, tmp_path, monkeypatch
    ):
        monkeypatch.chdir(tmp_path)
        monkeypatch.setenv("GITHUB_TOKEN", "fake-token")
        _setup_upgrade_project(tmp_path, with_lockfile=True)

        result = runner.invoke(
            app, ["deps", "upgrade", "--mode", "lockfile", "--json", "--check"]
        )
        assert result.exit_code == 0, result.output
        data = json.loads(result.output)
        assert "lockfile_stale" in data
        stale = data["lockfile_stale"]
        assert len(stale) >= 1
        entry = stale[0]
        assert "current_sha" in entry
        assert "latest_sha" in entry

    @patch("ghagen.pin.sources.track_user_files", side_effect=_mock_track_user_files)
    def test_lockfile_mode_no_lockfile_configured(
        self, mock_track, tmp_path, monkeypatch
    ):
        """When lockfile_path is None, lockfile mode finds nothing stale."""
        monkeypatch.chdir(tmp_path)
        monkeypatch.setenv("GITHUB_TOKEN", "fake-token")

        # Config with lockfile=None
        config = tmp_path / "ghagen_config.py"
        config.write_text(
            """\
from ghagen import App, Job, On, PushTrigger, Step, Workflow

app = App(lockfile=None)
ci = Workflow(
    name="CI",
    on=On(push=PushTrigger(branches=["main"])),
    jobs={"test": Job(
        runs_on="ubuntu-latest",
        steps=[Step(uses="actions/checkout@v4")],
    )},
)
app.add_workflow(ci, "ci.yml")
"""
        )

        result = runner.invoke(
            app, ["deps", "upgrade", "--mode", "lockfile", "--json", "--check"]
        )
        assert result.exit_code == 0, result.output
        data = json.loads(result.output)
        assert data["lockfile_stale"] == []


class TestUpgradeAllMode:
    """Tests for the default 'all' mode."""

    @patch("ghagen.pin.sources.track_user_files", side_effect=_mock_track_user_files)
    @patch("ghagen.pin.github.GitHubClient.list_tags", side_effect=_mock_list_tags)
    @patch("ghagen.pin.github.GitHubClient.resolve_ref", side_effect=_mock_resolve_ref)
    def test_all_mode_includes_both(
        self, mock_resolve, mock_tags, mock_track, tmp_path, monkeypatch
    ):
        monkeypatch.chdir(tmp_path)
        monkeypatch.setenv("GITHUB_TOKEN", "fake-token")
        _setup_upgrade_project(tmp_path, with_lockfile=True)

        result = runner.invoke(app, ["deps", "upgrade", "--json", "--check"])
        assert result.exit_code == 0, result.output
        data = json.loads(result.output)
        assert "version_bumps" in data
        assert "lockfile_stale" in data


class TestUpgradeApply:
    """Tests for the default apply behavior."""

    @patch("ghagen.pin.sources.track_user_files", side_effect=_mock_track_user_files)
    @patch("ghagen.pin.github.GitHubClient.list_tags", side_effect=_mock_list_tags)
    def test_upgrade_modifies_source_files(
        self, mock_tags, mock_track, tmp_path, monkeypatch
    ):
        monkeypatch.chdir(tmp_path)
        monkeypatch.setenv("GITHUB_TOKEN", "fake-token")
        _setup_upgrade_project(tmp_path)

        result = runner.invoke(app, ["deps", "upgrade", "--mode", "versions"])
        assert result.exit_code == 0, result.output
        assert "Applied version bumps" in result.output
        assert "modified" in result.output

        # Verify the config file was actually modified
        config_content = (tmp_path / "ghagen_config.py").read_text()
        assert "actions/checkout@v7" in config_content
        assert "actions/setup-python@v7" in config_content

    @patch("ghagen.pin.sources.track_user_files", side_effect=_mock_track_user_files)
    @patch("ghagen.pin.github.GitHubClient.list_tags", side_effect=_mock_list_tags)
    def test_check_flag_does_not_modify_source_files(
        self, mock_tags, mock_track, tmp_path, monkeypatch
    ):
        monkeypatch.chdir(tmp_path)
        monkeypatch.setenv("GITHUB_TOKEN", "fake-token")
        _setup_upgrade_project(tmp_path)

        result = runner.invoke(
            app, ["deps", "upgrade", "--mode", "versions", "--check"]
        )
        assert result.exit_code == 0, result.output

        # Verify the config file was NOT modified
        config_content = (tmp_path / "ghagen_config.py").read_text()
        assert "actions/checkout@v4" in config_content
        assert "actions/setup-python@v5" in config_content


class TestUpgradeNoUpdates:
    """Tests for the clean exit when everything is up to date."""

    def test_no_updates_human_output(self, tmp_path, monkeypatch):
        monkeypatch.chdir(tmp_path)
        monkeypatch.setenv("GITHUB_TOKEN", "fake-token")
        _setup_upgrade_project(tmp_path)

        def mock_tags_up_to_date(owner, repo, *, token=None):
            if repo == "checkout":
                return ["v1", "v2", "v3", "v4"]  # v4 is latest
            if repo == "setup-python":
                return ["v4", "v5"]  # v5 is latest
            return []

        with (
            patch(
                "ghagen.pin.sources.track_user_files",
                side_effect=_mock_track_user_files,
            ),
            patch(
                "ghagen.pin.github.GitHubClient.list_tags",
                side_effect=mock_tags_up_to_date,
            ),
        ):
            result = runner.invoke(
                app, ["deps", "upgrade", "--mode", "versions", "--check"]
            )

        assert result.exit_code == 0, result.output
        assert "Everything is up to date" in result.output

    def test_no_updates_json_output(self, tmp_path, monkeypatch):
        monkeypatch.chdir(tmp_path)
        monkeypatch.setenv("GITHUB_TOKEN", "fake-token")
        _setup_upgrade_project(tmp_path)

        def mock_tags_up_to_date(owner, repo, *, token=None):
            if repo == "checkout":
                return ["v1", "v2", "v3", "v4"]
            if repo == "setup-python":
                return ["v4", "v5"]
            return []

        with (
            patch(
                "ghagen.pin.sources.track_user_files",
                side_effect=_mock_track_user_files,
            ),
            patch(
                "ghagen.pin.github.GitHubClient.list_tags",
                side_effect=mock_tags_up_to_date,
            ),
        ):
            result = runner.invoke(
                app, ["deps", "upgrade", "--mode", "versions", "--json", "--check"]
            )

        assert result.exit_code == 0, result.output
        data = json.loads(result.output)
        assert data["version_bumps"] == []


class TestUpgradeNonSemver:
    """Tests for non-semver refs handled gracefully."""

    def test_non_semver_skipped_in_versions_mode(self, tmp_path, monkeypatch):
        """Refs with non-semver tags (e.g. main, sha) are skipped."""
        monkeypatch.chdir(tmp_path)
        monkeypatch.setenv("GITHUB_TOKEN", "fake-token")

        config = tmp_path / "ghagen_config.py"
        config.write_text(
            """\
from ghagen import App, Job, On, PushTrigger, Step, Workflow

app = App()
ci = Workflow(
    name="CI",
    on=On(push=PushTrigger(branches=["main"])),
    jobs={"test": Job(
        runs_on="ubuntu-latest",
        steps=[Step(uses="actions/checkout@main")],
    )},
)
app.add_workflow(ci, "ci.yml")
"""
        )

        def mock_tags(owner, repo, *, token=None):
            return ["v1", "v2", "v3", "v4", "v5"]

        with (
            patch(
                "ghagen.pin.sources.track_user_files",
                side_effect=_mock_track_user_files,
            ),
            patch("ghagen.pin.github.GitHubClient.list_tags", side_effect=mock_tags),
        ):
            result = runner.invoke(
                app, ["deps", "upgrade", "--mode", "versions", "--json", "--check"]
            )

        assert result.exit_code == 0, result.output
        data = json.loads(result.output)
        # Non-semver ref "main" should be skipped — no version bumps.
        assert data["version_bumps"] == []


class TestUpgradeTokenHandling:
    """Tests for token resolution."""

    @patch("ghagen.pin.sources.track_user_files", side_effect=_mock_track_user_files)
    @patch("ghagen.pin.github.GitHubClient.list_tags", side_effect=_mock_list_tags)
    def test_no_token_warning(self, mock_tags, mock_track, tmp_path, monkeypatch):
        monkeypatch.chdir(tmp_path)
        monkeypatch.delenv("GITHUB_TOKEN", raising=False)
        monkeypatch.delenv("GH_TOKEN", raising=False)
        _setup_upgrade_project(tmp_path)

        result = runner.invoke(
            app, ["deps", "upgrade", "--mode", "versions", "--check"]
        )
        assert "no GitHub token found" in result.output

    @patch("ghagen.pin.sources.track_user_files", side_effect=_mock_track_user_files)
    @patch("ghagen.pin.github.GitHubClient.list_tags", side_effect=_mock_list_tags)
    def test_token_from_env(self, mock_tags, mock_track, tmp_path, monkeypatch):
        monkeypatch.chdir(tmp_path)
        monkeypatch.setenv("GITHUB_TOKEN", "my-token")
        monkeypatch.delenv("GH_TOKEN", raising=False)
        _setup_upgrade_project(tmp_path)

        result = runner.invoke(
            app, ["deps", "upgrade", "--mode", "versions", "--check"]
        )
        assert "no GitHub token found" not in result.output

    @patch("ghagen.pin.sources.track_user_files", side_effect=_mock_track_user_files)
    @patch("ghagen.pin.github.GitHubClient.list_tags", side_effect=_mock_list_tags)
    def test_gh_token_fallback(self, mock_tags, mock_track, tmp_path, monkeypatch):
        monkeypatch.chdir(tmp_path)
        monkeypatch.delenv("GITHUB_TOKEN", raising=False)
        monkeypatch.setenv("GH_TOKEN", "gh-token")
        _setup_upgrade_project(tmp_path)

        result = runner.invoke(
            app, ["deps", "upgrade", "--mode", "versions", "--check"]
        )
        assert "no GitHub token found" not in result.output


class TestUpgradeErrorHandling:
    """Tests for error handling."""

    def test_invalid_mode(self, tmp_path, monkeypatch):
        monkeypatch.chdir(tmp_path)
        monkeypatch.setenv("GITHUB_TOKEN", "fake-token")
        _setup_upgrade_project(tmp_path)

        result = runner.invoke(app, ["deps", "upgrade", "--mode", "invalid"])
        assert result.exit_code == 2
        assert "unknown --mode value" in result.output

    @patch("ghagen.pin.sources.track_user_files", side_effect=_mock_track_user_files)
    def test_api_error_continues_with_warning(self, mock_track, tmp_path, monkeypatch):
        """API errors for one repo should not stop processing."""
        monkeypatch.chdir(tmp_path)
        monkeypatch.setenv("GITHUB_TOKEN", "fake-token")
        _setup_upgrade_project(tmp_path)

        from ghagen.pin.github import ResolveError

        def mock_tags_with_error(owner, repo, *, token=None):
            if repo == "checkout":
                raise ResolveError("rate limited")
            return _SETUP_PYTHON_TAGS

        with patch(
            "ghagen.pin.github.GitHubClient.list_tags",
            side_effect=mock_tags_with_error,
        ):
            result = runner.invoke(
                app, ["deps", "upgrade", "--mode", "versions", "--json", "--check"]
            )

        assert result.exit_code == 0, result.output
        assert "rate limited" in result.output
        data = json.loads(result.stdout)
        # setup-python should still be reported
        uses_list = [b["uses"] for b in data["version_bumps"]]
        assert "actions/setup-python@v5" in uses_list


class TestUpgradeNoRefs:
    """Test behavior when there are no pinnable refs."""

    def test_no_refs_human(self, tmp_path, monkeypatch):
        monkeypatch.chdir(tmp_path)
        monkeypatch.setenv("GITHUB_TOKEN", "fake-token")

        config = tmp_path / "ghagen_config.py"
        config.write_text(
            """\
from ghagen import App, Job, On, PushTrigger, Step, Workflow

app = App()
ci = Workflow(
    name="CI",
    on=On(push=PushTrigger(branches=["main"])),
    jobs={"test": Job(
        runs_on="ubuntu-latest",
        steps=[Step(name="Test", run="echo hello")],
    )},
)
app.add_workflow(ci, "ci.yml")
"""
        )

        with patch(
            "ghagen.pin.sources.track_user_files",
            side_effect=_mock_track_user_files,
        ):
            result = runner.invoke(app, ["deps", "upgrade", "--check"])

        assert result.exit_code == 0, result.output
        assert "Everything is up to date" in result.output

    def test_no_refs_json(self, tmp_path, monkeypatch):
        monkeypatch.chdir(tmp_path)
        monkeypatch.setenv("GITHUB_TOKEN", "fake-token")

        config = tmp_path / "ghagen_config.py"
        config.write_text(
            """\
from ghagen import App, Job, On, PushTrigger, Step, Workflow

app = App()
ci = Workflow(
    name="CI",
    on=On(push=PushTrigger(branches=["main"])),
    jobs={"test": Job(
        runs_on="ubuntu-latest",
        steps=[Step(name="Test", run="echo hello")],
    )},
)
app.add_workflow(ci, "ci.yml")
"""
        )

        with patch(
            "ghagen.pin.sources.track_user_files",
            side_effect=_mock_track_user_files,
        ):
            result = runner.invoke(app, ["deps", "upgrade", "--json", "--check"])

        assert result.exit_code == 0, result.output
        data = json.loads(result.output)
        assert data == {
            "version_bumps": [],
            "lockfile_stale": [],
        }


# -- deps upgrade --json contract --------------------------------------------
#
# Pins the ``ghagen deps upgrade --json`` seam against the shared golden
# fixture (``fixtures/expected/upgrade_report.json``), asserted identically in
# the TypeScript port (``src/cli/deps.test.ts``). See
# docs/specs/0005-typed-engine-report-seam.md Part A.


class TestUpgradeJsonContract:
    """Serializer-level tests pinning the ``--json`` shape to the shared fixture."""

    def test_serializers_match_golden_fixture(self):
        """``_bump_to_json`` / ``_stale_to_json`` render exactly the shared fixture."""
        bumps = [
            VersionBump(
                uses="actions/checkout@v5",
                current="v5",
                latest="v6",
                severity="major",
                source_files=[".github/ghagen_workflows.py"],
            ),
            VersionBump(
                uses="actions/setup-node@v3",
                current="v3",
                latest="v4",
                severity="major",
                # No source_files -> key must be omitted entirely (not `[]`).
            ),
        ]
        stale = [
            LockfileStaleEntry(
                uses="actions/setup-python@v6",
                current_sha="ece7cb06caefa5fff74198d8649806c4678c61a1",
                latest_sha="aaaa1111bbbb2222cccc3333dddd4444eeee5555",
                source_files=[".github/ghagen_workflows.py"],
            ),
        ]

        rendered = {
            "version_bumps": [_bump_to_json(b) for b in bumps],
            "lockfile_stale": [_stale_to_json(s) for s in stale],
        }
        rendered_text = json.dumps(rendered, indent=2)

        fixture_text = (FIXTURES_DIR / "upgrade_report.json").read_text()
        assert json.loads(rendered_text) == json.loads(fixture_text)

        # The phantom `helper_provided` field must never appear.
        assert "helper_provided" not in rendered_text
        assert "helper_provided" not in rendered

    def test_source_files_omitted_when_empty(self):
        """A bump/stale entry with no source files omits the key (not `[]`)."""
        bump = VersionBump(
            uses="actions/setup-node@v3", current="v3", latest="v4", severity="major"
        )
        stale = LockfileStaleEntry(
            uses="actions/setup-python@v6",
            current_sha="a" * 40,
            latest_sha="b" * 40,
        )
        assert "source_files" not in _bump_to_json(bump)
        assert "source_files" not in _stale_to_json(stale)

    @patch("ghagen.pin.sources.track_user_files", side_effect=_mock_track_user_files)
    @patch("ghagen.pin.github.GitHubClient.list_tags", side_effect=_mock_list_tags)
    def test_mode_versions_omits_lockfile_stale_key(
        self, mock_tags, mock_track, tmp_path, monkeypatch
    ):
        monkeypatch.chdir(tmp_path)
        monkeypatch.setenv("GITHUB_TOKEN", "fake-token")
        _setup_upgrade_project(tmp_path)

        result = runner.invoke(
            app, ["deps", "upgrade", "--mode", "versions", "--json", "--check"]
        )
        assert result.exit_code == 0, result.output
        data = json.loads(result.output)
        assert "version_bumps" in data
        assert "lockfile_stale" not in data
        assert "helper_provided" not in result.output

    @patch("ghagen.pin.sources.track_user_files", side_effect=_mock_track_user_files)
    @patch("ghagen.pin.github.GitHubClient.resolve_ref", side_effect=_mock_resolve_ref)
    def test_mode_lockfile_omits_version_bumps_key(
        self, mock_resolve, mock_track, tmp_path, monkeypatch
    ):
        monkeypatch.chdir(tmp_path)
        monkeypatch.setenv("GITHUB_TOKEN", "fake-token")
        _setup_upgrade_project(tmp_path, with_lockfile=True)

        result = runner.invoke(
            app, ["deps", "upgrade", "--mode", "lockfile", "--json", "--check"]
        )
        assert result.exit_code == 0, result.output
        data = json.loads(result.output)
        assert "lockfile_stale" in data
        assert "version_bumps" not in data
        assert "helper_provided" not in result.output

    def test_empty_report_emits_both_keys_regardless_of_mode(
        self, tmp_path, monkeypatch
    ):
        """The 'everything up to date' early return always emits both keys.

        This holds even under ``--mode versions`` / ``--mode lockfile``, where
        the non-empty JSON path would otherwise omit one of the two keys.
        """
        monkeypatch.chdir(tmp_path)
        monkeypatch.setenv("GITHUB_TOKEN", "fake-token")

        config = tmp_path / "ghagen_config.py"
        config.write_text(
            """\
from ghagen import App, Job, On, PushTrigger, Step, Workflow

app = App()
ci = Workflow(
    name="CI",
    on=On(push=PushTrigger(branches=["main"])),
    jobs={"test": Job(
        runs_on="ubuntu-latest",
        steps=[Step(name="Test", run="echo hello")],
    )},
)
app.add_workflow(ci, "ci.yml")
"""
        )

        with patch(
            "ghagen.pin.sources.track_user_files",
            side_effect=_mock_track_user_files,
        ):
            for mode in ("versions", "lockfile", "all"):
                result = runner.invoke(
                    app, ["deps", "upgrade", "--mode", mode, "--json", "--check"]
                )
                assert result.exit_code == 0, result.output
                data = json.loads(result.output)
                assert data == {"version_bumps": [], "lockfile_stale": []}
                assert "helper_provided" not in result.output
