"""Tests for the ``ghagen deps`` CLI subcommands.

Scope, deliberately narrow: what is genuinely CLI. Argument parsing and
validation, token resolution, **which stream** each piece of output goes to,
and the end-to-end shape of the JSON payload.

What is *not* here, and why:

- Engine behaviour (bump detection, stale-lockfile detection, mode dispatch,
  warnings) is asserted directly, without a ``CliRunner``, in
  ``tests/test_pin/test_engine.py``.
- Output rendering (all four formats, the golden fixtures, the JSON key set) is
  asserted directly against ``ghagen.pin.render`` in
  ``tests/test_pin/test_render.py``.

Before proposal 17 this file was 911 lines, 542 of which spun up a temp
project, wrote a config, patched two ``GitHubClient`` methods and drove a Typer
command in order to re-assert facts those two files already assert in ~17 lines
with a canned transport. The renderer had no seam in Python -- the mode x
format dispatch lived inside ``deps_upgrade``, whose parameters are all Typer
``OptionInfo`` sentinels -- so a ``CliRunner`` was the only way in.
"""

from __future__ import annotations

import json
from pathlib import Path
from unittest.mock import patch

from typer.testing import CliRunner

from ghagen.cli.main import app

runner = CliRunner()


_CONFIG = """\
from ghagen import App, Job, On, PushTrigger, Step, Workflow

app = App()
ci = Workflow(
    name="CI",
    on=On(push=PushTrigger(branches=["main"])),
    jobs={"test": Job(
        runs_on="ubuntu-latest",
        steps=[Step(uses="actions/checkout@v4")],
    )},
)
app.add_workflow(ci, "ci.yml")
"""


_LOCKFILE = """\
# Auto-generated by `ghagen deps pin`. Do not edit manually.

pins:
  actions/checkout@v4:
    sha: "0123456789abcdef0123456789abcdef01234567"
    resolved_at: "2026-04-09T00:00:00+00:00"
"""


def test_deps_check_synced_passes_when_lockfile_in_sync(
    tmp_path: Path, monkeypatch: object
):
    monkeypatch.chdir(tmp_path)  # type: ignore[attr-defined]
    monkeypatch.delenv("GITHUB_TOKEN", raising=False)  # type: ignore[attr-defined]
    monkeypatch.delenv("GH_TOKEN", raising=False)  # type: ignore[attr-defined]

    (tmp_path / "ghagen_config.py").write_text(_CONFIG)
    lockfile = tmp_path / ".ghagen.lock.yml"
    lockfile.write_text(_LOCKFILE)

    result = runner.invoke(app, ["deps", "check-synced"])
    assert result.exit_code == 0, result.output
    assert "Lockfile is in sync." in result.output
    # check-synced never hits the network, so the no-token warning must NOT fire.
    assert "no GitHub token found" not in result.output


def test_deps_check_synced_fails_when_entry_missing(
    tmp_path: Path, monkeypatch: object
):
    monkeypatch.chdir(tmp_path)  # type: ignore[attr-defined]
    monkeypatch.delenv("GITHUB_TOKEN", raising=False)  # type: ignore[attr-defined]
    monkeypatch.delenv("GH_TOKEN", raising=False)  # type: ignore[attr-defined]

    (tmp_path / "ghagen_config.py").write_text(_CONFIG)
    # Deliberately create an empty lockfile so the check sees a missing entry.
    lockfile = tmp_path / ".ghagen.lock.yml"
    lockfile.write_text("# empty\n")

    result = runner.invoke(app, ["deps", "check-synced"])
    assert result.exit_code == 1
    assert "Missing lockfile entries" in result.output
    assert "actions/checkout@v4" in result.output
    assert "no GitHub token found" not in result.output


def test_deps_check_synced_fails_on_stale_entry_with_prune(
    tmp_path: Path, monkeypatch: object
):
    monkeypatch.chdir(tmp_path)  # type: ignore[attr-defined]
    monkeypatch.delenv("GITHUB_TOKEN", raising=False)  # type: ignore[attr-defined]
    monkeypatch.delenv("GH_TOKEN", raising=False)  # type: ignore[attr-defined]

    # Config references only checkout; lockfile has an extra unused entry.
    (tmp_path / "ghagen_config.py").write_text(_CONFIG)
    lockfile = tmp_path / ".ghagen.lock.yml"
    lockfile.write_text(
        _LOCKFILE
        + "  actions/unused@v1:\n"
        + '    sha: "fedcba9876543210fedcba9876543210fedcba98"\n'
        + '    resolved_at: "2026-04-09T00:00:00+00:00"\n'
    )

    result = runner.invoke(app, ["deps", "check-synced"])
    assert result.exit_code == 1
    assert "Stale lockfile entries" in result.output
    assert "actions/unused@v1" in result.output


# -- deps upgrade ------------------------------------------------------------

_UPGRADE_CONFIG = """\
from ghagen import App, Job, On, PushTrigger, Step, Workflow

app = App()
ci = Workflow(
    name="CI",
    on=On(push=PushTrigger(branches=["main"])),
    jobs={"test": Job(
        runs_on="ubuntu-latest",
        steps=[
            Step(uses="actions/checkout@v4"),
            Step(uses="actions/setup-python@v5"),
        ],
    )},
)
app.add_workflow(ci, "ci.yml")
"""

# Common mock values
_CHECKOUT_TAGS = ["v1", "v2", "v3", "v4", "v5", "v6", "v7"]
_SETUP_PYTHON_TAGS = ["v4", "v5", "v5.1.0", "v6", "v7"]


def _setup_upgrade_project(tmp_path: Path) -> Path:
    """Write the upgrade config file; return its path."""
    config_path = tmp_path / "ghagen_config.py"
    config_path.write_text(_UPGRADE_CONFIG)
    return config_path


def _mock_list_tags(owner: str, repo: str, *, token=None) -> list[str]:
    """Return fake tags for known repos."""
    if repo == "checkout":
        return _CHECKOUT_TAGS
    if repo == "setup-python":
        return _SETUP_PYTHON_TAGS
    return []


def _mock_track_user_files(config_path):
    """Load the app and return ``(app, files)`` with the config file tracked."""
    from ghagen.cli._common import _load_app

    loaded_app = _load_app(config_path)
    # Return the config file based on the root -- in tests we write
    # ghagen_config.py in tmp_path which is also the cwd.
    root = loaded_app.root
    config = root / "ghagen_config.py"
    files = {config} if config.is_file() else set()
    return loaded_app, files


class TestUpgradeLockfileMode:
    """The one path config loading has to survive: no lockfile at all."""

    @patch("ghagen.pin.sources.track_user_files", side_effect=_mock_track_user_files)
    def test_lockfile_mode_no_lockfile_configured(
        self, mock_track, tmp_path, monkeypatch
    ):
        """With ``lockfile=None`` the stage is skipped, but it was still asked for.

        The engine-level counterpart is
        ``test_pin/test_engine.py::TestUpgradeCheckedFlags``; only this test
        proves config loading and the full command survive a null lockfile.
        """
        monkeypatch.chdir(tmp_path)
        monkeypatch.setenv("GITHUB_TOKEN", "fake-token")

        # Config with lockfile=None
        config = tmp_path / "ghagen_config.py"
        config.write_text(
            """\
from ghagen import App, Job, On, PushTrigger, Step, Workflow

app = App(lockfile=None)
ci = Workflow(
    name="CI",
    on=On(push=PushTrigger(branches=["main"])),
    jobs={"test": Job(
        runs_on="ubuntu-latest",
        steps=[Step(uses="actions/checkout@v4")],
    )},
)
app.add_workflow(ci, "ci.yml")
"""
        )

        result = runner.invoke(
            app,
            ["deps", "upgrade", "--mode", "lockfile", "--format", "json", "--check"],
        )
        assert result.exit_code == 0, result.output
        data = json.loads(result.stdout)
        assert data["lockfile_stale"] == []


class TestUpgradeApply:
    """Where the apply-progress note lands -- the ``0cae9b1`` hotfix, both halves.

    The renderer returns a string and writes nothing, so it cannot interleave
    with the progress note; the command keeps sole ownership of destinations.
    These two tests pin that ownership, which is a routing fact, not a
    rendering one -- hence a CLI test rather than a renderer test.
    """

    @patch("ghagen.pin.sources.track_user_files", side_effect=_mock_track_user_files)
    @patch("ghagen.pin.github.GitHubClient.list_tags", side_effect=_mock_list_tags)
    def test_upgrade_modifies_source_files(
        self, mock_tags, mock_track, tmp_path, monkeypatch
    ):
        """Without ``--format`` the progress note belongs on **stdout**.

        Asserted against ``result.stdout``, not ``result.output``: under click
        8.3+ ``Result.output`` is an interleaved mix of stdout and stderr, so
        the previous ``in result.output`` assertion never pinned the stream.
        """
        monkeypatch.chdir(tmp_path)
        monkeypatch.setenv("GITHUB_TOKEN", "fake-token")
        _setup_upgrade_project(tmp_path)

        result = runner.invoke(app, ["deps", "upgrade", "--mode", "versions"])
        assert result.exit_code == 0, result.output
        assert "Applied version bumps" in result.stdout
        assert "modified" in result.stdout

        # Verify the config file was actually modified
        config_content = (tmp_path / "ghagen_config.py").read_text()
        assert "actions/checkout@v7" in config_content
        assert "actions/setup-python@v7" in config_content

    @patch("ghagen.pin.sources.track_user_files", side_effect=_mock_track_user_files)
    @patch("ghagen.pin.github.GitHubClient.list_tags", side_effect=_mock_list_tags)
    def test_apply_with_json_format_keeps_stdout_parseable(
        self, mock_tags, mock_track, tmp_path, monkeypatch
    ):
        """--format json without --check must not interleave progress on stdout."""
        monkeypatch.chdir(tmp_path)
        monkeypatch.setenv("GITHUB_TOKEN", "fake-token")
        _setup_upgrade_project(tmp_path)

        result = runner.invoke(
            app, ["deps", "upgrade", "--mode", "versions", "--format", "json"]
        )
        assert result.exit_code == 0, result.output
        assert "Applied version bumps" not in result.stdout
        data = json.loads(result.stdout)
        assert "version_bumps" in data
        assert "Applied version bumps" in result.stderr

        # Verify the config file was actually modified
        config_content = (tmp_path / "ghagen_config.py").read_text()
        assert "actions/checkout@v7" in config_content
        assert "actions/setup-python@v7" in config_content


class TestUpgradeTokenHandling:
    """Tests for token resolution (flag > $GITHUB_TOKEN > $GH_TOKEN)."""

    @patch("ghagen.pin.sources.track_user_files", side_effect=_mock_track_user_files)
    @patch("ghagen.pin.github.GitHubClient.list_tags", side_effect=_mock_list_tags)
    def test_no_token_warning(self, mock_tags, mock_track, tmp_path, monkeypatch):
        monkeypatch.chdir(tmp_path)
        monkeypatch.delenv("GITHUB_TOKEN", raising=False)
        monkeypatch.delenv("GH_TOKEN", raising=False)
        _setup_upgrade_project(tmp_path)

        result = runner.invoke(
            app, ["deps", "upgrade", "--mode", "versions", "--check"]
        )
        assert "no GitHub token found" in result.output

    @patch("ghagen.pin.sources.track_user_files", side_effect=_mock_track_user_files)
    @patch("ghagen.pin.github.GitHubClient.list_tags", side_effect=_mock_list_tags)
    def test_token_from_env(self, mock_tags, mock_track, tmp_path, monkeypatch):
        monkeypatch.chdir(tmp_path)
        monkeypatch.setenv("GITHUB_TOKEN", "my-token")
        monkeypatch.delenv("GH_TOKEN", raising=False)
        _setup_upgrade_project(tmp_path)

        result = runner.invoke(
            app, ["deps", "upgrade", "--mode", "versions", "--check"]
        )
        assert "no GitHub token found" not in result.output

    @patch("ghagen.pin.sources.track_user_files", side_effect=_mock_track_user_files)
    @patch("ghagen.pin.github.GitHubClient.list_tags", side_effect=_mock_list_tags)
    def test_gh_token_fallback(self, mock_tags, mock_track, tmp_path, monkeypatch):
        monkeypatch.chdir(tmp_path)
        monkeypatch.delenv("GITHUB_TOKEN", raising=False)
        monkeypatch.setenv("GH_TOKEN", "gh-token")
        _setup_upgrade_project(tmp_path)

        result = runner.invoke(
            app, ["deps", "upgrade", "--mode", "versions", "--check"]
        )
        assert "no GitHub token found" not in result.output


class TestUpgradeErrorHandling:
    """Flag validation and warning routing."""

    def test_invalid_mode(self, tmp_path, monkeypatch):
        monkeypatch.chdir(tmp_path)
        monkeypatch.setenv("GITHUB_TOKEN", "fake-token")
        _setup_upgrade_project(tmp_path)

        result = runner.invoke(app, ["deps", "upgrade", "--mode", "invalid"])
        assert result.exit_code == 2
        assert "unknown --mode value" in result.output

    def test_invalid_format(self, tmp_path, monkeypatch):
        """``--format`` validation stays at the CLI edge, beside ``--mode``.

        ``pin.render`` treats an unknown format as a programmer error; the
        command is what turns a bad flag into exit 2.
        """
        monkeypatch.chdir(tmp_path)
        monkeypatch.setenv("GITHUB_TOKEN", "fake-token")
        _setup_upgrade_project(tmp_path)

        result = runner.invoke(app, ["deps", "upgrade", "--format", "yaml"])
        assert result.exit_code == 2
        assert "unknown --format value" in result.output

    @patch("ghagen.pin.sources.track_user_files", side_effect=_mock_track_user_files)
    def test_warnings_are_echoed_to_stderr(self, mock_track, tmp_path, monkeypatch):
        """A ``report.warnings`` entry reaches stderr with the ``warning: `` prefix.

        The engine fact -- that a failed tag lookup becomes a warning rather
        than an exception -- is asserted in
        ``test_pin/test_engine.py::TestUpgrade``. This is the CLI half: the
        echo loop's routing, which must not pollute the machine-readable
        stdout payload.
        """
        monkeypatch.chdir(tmp_path)
        monkeypatch.setenv("GITHUB_TOKEN", "fake-token")
        _setup_upgrade_project(tmp_path)

        from ghagen.pin.github import ResolveError

        def mock_tags_with_error(owner, repo, *, token=None):
            if repo == "checkout":
                raise ResolveError("rate limited")
            return _SETUP_PYTHON_TAGS

        with patch(
            "ghagen.pin.github.GitHubClient.list_tags",
            side_effect=mock_tags_with_error,
        ):
            result = runner.invoke(
                app,
                [
                    "deps",
                    "upgrade",
                    "--mode",
                    "versions",
                    "--format",
                    "json",
                    "--check",
                ],
            )

        assert result.exit_code == 0, result.output
        assert "warning: failed to list tags for actions/checkout" in result.stderr
        assert "rate limited" in result.stderr
        assert "warning:" not in result.stdout

        # The other repo is still reported on a parseable stdout.
        data = json.loads(result.stdout)
        uses_list = [b["uses"] for b in data["version_bumps"]]
        assert "actions/setup-python@v5" in uses_list


class TestUpgradeJsonContract:
    """The end-to-end key-set contract.

    The rule itself -- key presence follows ``checked_versions`` /
    ``checked_lockfile`` -- is asserted directly on the renderer in
    ``tests/test_pin/test_render.py``. This is the one place it is pinned
    through the real command, because it is a user-visible payload change.
    """

    def test_empty_report_emits_only_the_keys_the_mode_asked_for(
        self, tmp_path, monkeypatch
    ):
        """An empty report emits the same key set as a non-empty one.

        The key set depends only on ``--mode``, which the caller chose, and
        never on whether the run happened to find anything.  This inverts the
        behaviour the 'everything up to date' early return used to have, and
        resolves the open choice recorded in
        ``docs/specs/0005-typed-engine-report-seam.md`` Section 2.2.
        """
        monkeypatch.chdir(tmp_path)
        monkeypatch.setenv("GITHUB_TOKEN", "fake-token")

        config = tmp_path / "ghagen_config.py"
        config.write_text(
            """\
from ghagen import App, Job, On, PushTrigger, Step, Workflow

app = App()
ci = Workflow(
    name="CI",
    on=On(push=PushTrigger(branches=["main"])),
    jobs={"test": Job(
        runs_on="ubuntu-latest",
        steps=[Step(name="Test", run="echo hello")],
    )},
)
app.add_workflow(ci, "ci.yml")
"""
        )

        with patch(
            "ghagen.pin.sources.track_user_files",
            side_effect=_mock_track_user_files,
        ):
            expected_per_mode = {
                "versions": {"version_bumps": []},
                "lockfile": {"lockfile_stale": []},
                "all": {"version_bumps": [], "lockfile_stale": []},
            }
            for mode, expected in expected_per_mode.items():
                result = runner.invoke(
                    app,
                    ["deps", "upgrade", "--mode", mode, "--format", "json", "--check"],
                )
                assert result.exit_code == 0, result.output
                data = json.loads(result.stdout)
                assert data == expected, mode
                assert "helper_provided" not in result.output


# -- deps update -------------------------------------------------------------

_LOCKFILE_NONE_CONFIG = """\
from ghagen import App, Job, On, PushTrigger, Step, Workflow

app = App(lockfile=None)
ci = Workflow(
    name="CI",
    on=On(push=PushTrigger(branches=["main"])),
    jobs={"test": Job(
        runs_on="ubuntu-latest",
        steps=[Step(uses="actions/checkout@v4")],
    )},
)
app.add_workflow(ci, "ci.yml")
"""

#: The field set `--format github` and `--format json` both carry.
_PLAN_FIELDS = {
    "action",
    "total_updates",
    "apply_version_bumps",
    "refresh_lockfile",
    "branch",
    "title",
    "commit_message",
    "labels",
    "body_format",
    "changed",
}


def _github_outputs(stdout: str) -> dict[str, str]:
    """Parse ``--format github`` back into the mapping a runner would build."""
    return dict(line.split("=", 1) for line in stdout.splitlines() if line)


class TestDepsUpdate:
    """The automation verb: one sweep, one plan, one answer.

    Decision rules themselves are asserted offline in
    ``tests/test_pin/test_plan.py``; body bytes in ``tests/test_pin/test_render.py``.
    What is here is what is genuinely CLI -- flag validation, stream ownership,
    the two wire shapes, and the end-to-end proof that the command does not do
    the thing the shipped action's bash did.
    """

    @patch("ghagen.pin.sources.track_user_files", side_effect=_mock_track_user_files)
    @patch("ghagen.pin.github.GitHubClient.list_tags", side_effect=_mock_list_tags)
    def test_lockfile_none_project_never_reaches_deps_pin(
        self, mock_tags, mock_track, tmp_path, monkeypatch
    ):
        """H7, end to end: a bump on a ``lockfile=None`` project must not cascade.

        The shipped action's guard is
        ``lockfile_stale != 0 || version_bumps != 0``, which fires here --
        ``lockfile_stale`` is always ``0`` under ``lockfile=None`` because the
        stage is skipped, but the bump is real. It then runs
        ``ghagen deps pin --update``, which exits 1 with "lockfile is disabled",
        killing the step under ``set -euo pipefail`` after the source edits were
        written and before any commit.

        This command applies the bump and stops, because ``plan_update`` holds
        the ``App``.
        """
        monkeypatch.chdir(tmp_path)
        monkeypatch.setenv("GITHUB_TOKEN", "fake-token")
        (tmp_path / "ghagen_config.py").write_text(_LOCKFILE_NONE_CONFIG)

        result = runner.invoke(app, ["deps", "update", "--format", "json"])

        assert result.exit_code == 0, result.output
        assert "lockfile is disabled" not in result.output
        plan = json.loads(result.stdout)
        assert plan["refresh_lockfile"] is False
        assert plan["apply_version_bumps"] is True
        assert plan["action"] == "create-pr"
        # The bump really was applied -- the command did the half that is safe.
        assert "actions/checkout@v7" in (tmp_path / "ghagen_config.py").read_text()
        assert plan["changed"] is True

    @patch("ghagen.pin.sources.track_user_files", side_effect=_mock_track_user_files)
    @patch("ghagen.pin.github.GitHubClient.list_tags", side_effect=_mock_list_tags)
    def test_github_format_is_github_output_shaped_and_owns_stdout(
        self, mock_tags, mock_track, tmp_path, monkeypatch
    ):
        """``--format github`` appends straight to ``$GITHUB_OUTPUT``.

        Nothing human may share that stream: the action's plan step is a single
        ``>> "$GITHUB_OUTPUT"`` redirect, so a stray progress line would become
        a malformed output entry.
        """
        monkeypatch.chdir(tmp_path)
        monkeypatch.delenv("GITHUB_TOKEN", raising=False)
        monkeypatch.delenv("GH_TOKEN", raising=False)
        (tmp_path / "ghagen_config.py").write_text(_LOCKFILE_NONE_CONFIG)

        result = runner.invoke(
            app, ["deps", "update", "--dry-run", "--labels", " a , b ,, c "]
        )

        assert result.exit_code == 0, result.output
        outputs = _github_outputs(result.stdout)
        assert set(outputs) == _PLAN_FIELDS
        assert outputs["action"] == "create-pr"
        assert outputs["total_updates"] == "1"
        assert outputs["refresh_lockfile"] == "false"
        assert outputs["apply_version_bumps"] == "true"
        assert outputs["changed"] == "false"
        assert outputs["labels"] == "a,b,c"
        assert outputs["commit_message"] == "update ghagen action dependencies"
        # The no-token warning is real output and must not land in the payload.
        assert "no GitHub token found" in result.stderr
        assert "no GitHub token found" not in result.stdout

    @patch("ghagen.pin.sources.track_user_files", side_effect=_mock_track_user_files)
    @patch("ghagen.pin.github.GitHubClient.list_tags", side_effect=_mock_list_tags)
    def test_json_and_github_carry_the_same_fields(
        self, mock_tags, mock_track, tmp_path, monkeypatch
    ):
        """Two encodings of one shape -- a field added to either must appear in both."""
        monkeypatch.chdir(tmp_path)
        monkeypatch.setenv("GITHUB_TOKEN", "fake-token")
        (tmp_path / "ghagen_config.py").write_text(_LOCKFILE_NONE_CONFIG)

        as_json = runner.invoke(
            app, ["deps", "update", "--dry-run", "--format", "json"]
        )
        as_github = runner.invoke(
            app, ["deps", "update", "--dry-run", "--format", "github"]
        )

        assert as_json.exit_code == 0, as_json.output
        assert as_github.exit_code == 0, as_github.output
        assert set(json.loads(as_json.stdout)) == _PLAN_FIELDS
        assert set(_github_outputs(as_github.stdout)) == _PLAN_FIELDS

    @patch("ghagen.pin.sources.track_user_files", side_effect=_mock_track_user_files)
    @patch("ghagen.pin.github.GitHubClient.list_tags", side_effect=_mock_list_tags)
    def test_dry_run_writes_nothing(self, mock_tags, mock_track, tmp_path, monkeypatch):
        monkeypatch.chdir(tmp_path)
        monkeypatch.setenv("GITHUB_TOKEN", "fake-token")
        config = tmp_path / "ghagen_config.py"
        config.write_text(_LOCKFILE_NONE_CONFIG)
        before = config.read_text()

        result = runner.invoke(app, ["deps", "update", "--dry-run", "--format", "json"])

        assert result.exit_code == 0, result.output
        assert config.read_text() == before
        assert json.loads(result.stdout)["changed"] is False

    @patch("ghagen.pin.sources.track_user_files", side_effect=_mock_track_user_files)
    @patch("ghagen.pin.github.GitHubClient.list_tags", side_effect=_mock_list_tags)
    def test_body_file_is_written_in_the_plan_s_format(
        self, mock_tags, mock_track, tmp_path, monkeypatch
    ):
        """The body is a file path, never an output value.

        Keeping bytes out of ``$GITHUB_OUTPUT`` sidesteps the multiline
        delimiter dance entirely, which is why the plan carries ``body_format``
        rather than a body.
        """
        monkeypatch.chdir(tmp_path)
        monkeypatch.setenv("GITHUB_TOKEN", "fake-token")
        (tmp_path / "ghagen_config.py").write_text(_LOCKFILE_NONE_CONFIG)
        body = tmp_path / "body.md"

        result = runner.invoke(
            app,
            [
                "deps",
                "update",
                "--dry-run",
                "--body-file",
                str(body),
                "--format",
                "json",
            ],
        )

        assert result.exit_code == 0, result.output
        assert json.loads(result.stdout)["body_format"] == "pr-body"
        assert body.read_text().startswith("## ghagen dependency update")
        assert "actions/checkout@v4" in body.read_text()

    @patch("ghagen.pin.sources.track_user_files", side_effect=_mock_track_user_files)
    @patch("ghagen.pin.github.GitHubClient.list_tags", side_effect=_mock_list_tags)
    def test_no_body_file_is_written_when_there_is_nothing_to_raise(
        self, mock_tags, mock_track, tmp_path, monkeypatch
    ):
        monkeypatch.chdir(tmp_path)
        monkeypatch.setenv("GITHUB_TOKEN", "fake-token")
        # No pinnable refs at all -> empty report -> action == "none".
        (tmp_path / "ghagen_config.py").write_text(
            _LOCKFILE_NONE_CONFIG.replace(
                'Step(uses="actions/checkout@v4")', 'Step(run="echo hi")'
            )
        )
        body = tmp_path / "body.md"

        result = runner.invoke(
            app,
            ["deps", "update", "--body-file", str(body), "--format", "json"],
        )

        assert result.exit_code == 0, result.output
        plan = json.loads(result.stdout)
        assert plan["action"] == "none"
        assert plan["body_format"] is None
        assert not body.exists()


class TestDepsUpdateFlagValidation:
    """Bad flag values exit 2 with one line -- never a traceback.

    The construct being replaced turned every diagnosable CLI failure into
    exit 1 plus a ``JSONDecodeError`` traceback from the *reader*, because the
    detect step ended in ``|| true`` and the next line parsed the empty file it
    was supposed to have written.
    """

    def _project(self, tmp_path, monkeypatch):
        monkeypatch.chdir(tmp_path)
        monkeypatch.setenv("GITHUB_TOKEN", "fake-token")
        (tmp_path / "ghagen_config.py").write_text(_LOCKFILE_NONE_CONFIG)

    def test_invalid_mode(self, tmp_path, monkeypatch):
        self._project(tmp_path, monkeypatch)
        result = runner.invoke(app, ["deps", "update", "--mode", "bogus"])
        assert result.exit_code == 2
        assert "unknown --mode value" in result.stderr
        assert "Traceback" not in result.output
        assert len(result.stderr.strip().splitlines()) == 1

    def test_invalid_output(self, tmp_path, monkeypatch):
        self._project(tmp_path, monkeypatch)
        result = runner.invoke(app, ["deps", "update", "--output", "bogus"])
        assert result.exit_code == 2
        assert "unknown --output value" in result.stderr

    def test_invalid_format(self, tmp_path, monkeypatch):
        self._project(tmp_path, monkeypatch)
        result = runner.invoke(app, ["deps", "update", "--format", "yaml"])
        assert result.exit_code == 2
        assert "unknown --format value" in result.stderr

    def test_newline_in_a_prefix_is_rejected(self, tmp_path, monkeypatch):
        """A newline would forge extra ``$GITHUB_OUTPUT`` entries.

        ``commit-message-prefix`` is a workflow-author-supplied action input
        that lands verbatim in a ``key=value`` line, so an embedded newline is
        an output-injection vector, not a formatting nit.
        """
        self._project(tmp_path, monkeypatch)
        result = runner.invoke(
            app,
            ["deps", "update", "--commit-message-prefix", "x\naction=create-pr"],
        )
        assert result.exit_code == 2
        assert "must not contain a newline" in result.stderr
