#!/usr/bin/env node
/** ghagen CLI — generate GitHub Actions workflows from TS/JS. */

import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { Command } from "commander";
import { CliError, findConfig, loadApp } from "./_common.js";
import { buildDepsCommand } from "./deps.js";

const INIT_TEMPLATE = `// GitHub Actions workflow definitions.
//
// Generated by \`ghagen init\`. Run \`ghagen synth\` to emit the YAML
// files into \`.github/workflows/\`.

import {
  App,
  job,
  prTrigger,
  pushTrigger,
  step,
  workflow,
} from "@ghagen/ghagen";

export const app = new App();

const ci = workflow({
  name: "CI",
  on: {
    push: pushTrigger({ branches: ["main"] }),
    pullRequest: prTrigger({ branches: ["main"] }),
  },
  jobs: {
    test: job({
      runsOn: "ubuntu-latest",
      timeoutMinutes: 10,
      steps: [
        step({ uses: "actions/checkout@v4" }),
        step({ name: "Run tests", run: "echo 'Add your test command here'" }),
      ],
    }),
  },
});

app.addWorkflow(ci, "ci.yml");
`;

interface SynthOpts {
  config?: string;
}

/** Synthesize workflow YAML files from the user's config and write them to disk. */
async function cmdSynth(opts: SynthOpts): Promise<void> {
  const configPath = findConfig(opts.config);
  const app = await loadApp(configPath);
  const written = await app.synth();
  for (const path of written) {
    process.stdout.write(`  wrote ${path}\n`);
  }
  process.stdout.write(`Synthesized ${written.length} file(s).\n`);
}

/** Verify that generated YAML files are up-to-date with the config (exit 1 if stale). */
async function cmdCheckSynced(opts: SynthOpts): Promise<void> {
  const configPath = findConfig(opts.config);
  const app = await loadApp(configPath);
  const stale = await app.check();
  if (stale.length === 0) {
    process.stdout.write("All files are up-to-date.\n");
    return;
  }
  process.stderr.write(`${stale.length} file(s) are out of date:\n\n`);
  for (const [path, diff] of stale) {
    process.stderr.write(`--- ${path} ---\n`);
    process.stderr.write(`${diff}\n`);
  }
  throw new CliError("", 1);
}

interface InitOpts {
  outdir: string;
}

/** Scaffold a minimal ghagen config file into the target directory. */
async function cmdInit(opts: InitOpts): Promise<void> {
  const target = resolve(process.cwd(), opts.outdir, "ghagen.workflows.ts");
  if (existsSync(target)) {
    throw new CliError(`Config file already exists: ${target}`);
  }
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, INIT_TEMPLATE);
  process.stdout.write(`Created ${target}\n`);
  process.stdout.write("Run `ghagen synth` to generate workflow YAML files.\n");
}

function buildCli(): Command {
  const program = new Command()
    .name("ghagen")
    .description("Generate GitHub Actions workflow YAML from TypeScript/JavaScript code.")
    .showHelpAfterError();

  program
    .command("synth")
    .description("Generate workflow YAML files from TS/JS definitions.")
    .option("-c, --config <path>", "Path to config file")
    .action(async (opts: SynthOpts) => cmdSynth(opts));

  program
    .command("check-synced")
    .description("Check whether generated YAML files are up-to-date.")
    .option("-c, --config <path>", "Path to config file")
    .action(async (opts: SynthOpts) => cmdCheckSynced(opts));

  program
    .command("init")
    .description("Scaffold a minimal ghagen config file.")
    .option("-o, --outdir <dir>", "Output directory", ".github")
    .action(async (opts: InitOpts) => cmdInit(opts));

  program.addCommand(buildDepsCommand());
  return program;
}

/** Run the CLI. Returns the exit code. */
export async function main(argv: readonly string[]): Promise<number> {
  const program = buildCli();
  try {
    await program.parseAsync(argv as string[], { from: "user" });
    return 0;
  } catch (err) {
    if (err instanceof CliError) {
      if (err.message) {
        process.stderr.write(`${err.message}\n`);
      }
      return err.exitCode;
    }
    process.stderr.write(`Error: ${(err as Error).message}\n`);
    return 1;
  }
}

// Entry point when invoked directly via the bin shim.
if (process.argv[1] && import.meta.url === `file://${process.argv[1]}`) {
  main(process.argv.slice(2)).then((code) => process.exit(code));
}
