#!/usr/bin/env node
/** ghagen CLI — generate GitHub Actions workflows from TS/JS. */

import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { Command, CommanderError } from "commander";
import { findConfig, loadApp } from "./_common.js";
import { CliError } from "./_errors.js";
import { buildDepsCommand } from "./deps.js";

const INIT_TEMPLATE = `// GitHub Actions workflow definitions.
//
// Generated by \`ghagen init\`. Run \`ghagen synth\` to emit the YAML
// files into \`.github/workflows/\`.

import {
  App,
  job,
  prTrigger,
  pushTrigger,
  step,
  workflow,
} from "@ghagen/ghagen";

export const app = new App();

const ci = workflow({
  name: "CI",
  on: {
    push: pushTrigger({ branches: ["main"] }),
    pullRequest: prTrigger({ branches: ["main"] }),
  },
  jobs: {
    test: job({
      runsOn: "ubuntu-latest",
      timeoutMinutes: 10,
      steps: [
        step({ uses: "actions/checkout@v4" }),
        step({ name: "Run tests", run: "echo 'Add your test command here'" }),
      ],
    }),
  },
});

app.addWorkflow(ci, "ci.yml");
`;

interface SynthOpts {
  config?: string;
}

/** Synthesize workflow YAML files from the user's config and write them to disk. */
async function cmdSynth(opts: SynthOpts): Promise<void> {
  const configPath = findConfig(opts.config);
  const app = await loadApp(configPath);
  const written = await app.synth();
  for (const path of written) {
    process.stdout.write(`  wrote ${path}\n`);
  }
  process.stdout.write(`Synthesized ${written.length} file(s).\n`);
}

/** Verify that generated YAML files are up-to-date with the config (exit 1 if stale). */
async function cmdCheckSynced(opts: SynthOpts): Promise<void> {
  const configPath = findConfig(opts.config);
  const app = await loadApp(configPath);
  const stale = await app.check();
  if (stale.length === 0) {
    process.stdout.write("All files are up-to-date.\n");
    return;
  }
  process.stderr.write(`${stale.length} file(s) are out of date:\n\n`);
  for (const [path, diff] of stale) {
    process.stderr.write(`--- ${path} ---\n`);
    process.stderr.write(`${diff}\n`);
  }
  throw new CliError("", 1);
}

interface InitOpts {
  outdir: string;
}

/** Scaffold a minimal ghagen config file into the target directory. */
async function cmdInit(opts: InitOpts): Promise<void> {
  const target = resolve(process.cwd(), opts.outdir, "ghagen.workflows.ts");
  if (existsSync(target)) {
    throw new CliError(`Config file already exists: ${target}`);
  }
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, INIT_TEMPLATE);
  process.stdout.write(`Created ${target}\n`);
  process.stdout.write("Run `ghagen synth` to generate workflow YAML files.\n");
}

function buildCli(): Command {
  const program = new Command()
    .name("ghagen")
    .description("Generate GitHub Actions workflow YAML from TypeScript/JavaScript code.")
    .showHelpAfterError();

  program
    .command("synth")
    .description("Generate workflow YAML files from TS/JS definitions.")
    .option("-c, --config <path>", "Path to config file")
    .action(async (opts: SynthOpts) => cmdSynth(opts));

  program
    .command("check-synced")
    .description("Check whether generated YAML files are up-to-date.")
    .option("-c, --config <path>", "Path to config file")
    .action(async (opts: SynthOpts) => cmdCheckSynced(opts));

  program
    .command("init")
    .description("Scaffold a minimal ghagen config file.")
    .option("-o, --outdir <dir>", "Output directory", ".github")
    .action(async (opts: InitOpts) => cmdInit(opts));

  program.addCommand(buildDepsCommand());
  return program;
}

/** Exit code for a usage error, per `fixtures/cli-exit-codes.yml`. */
const EXIT_USAGE = 2;

/**
 * Hand every command in the tree back to {@link main} instead of `process.exit`.
 *
 * A root-only `program.exitOverride()` reaches nothing: commander stores
 * `_exitCallback` per-`Command` and never looks it up through the parent chain.
 * `.command()` children copy it from the parent at *creation* time
 * (`copyInheritedSettings`), and `.addCommand()` children -- which is how the
 * `deps` subtree is mounted -- never copy it at all. So the trap has to be
 * applied to the already-built tree, node by node.
 */
function trapExits(cmd: Command): void {
  cmd.exitOverride();
  for (const sub of cmd.commands) {
    trapExits(sub);
  }
}

/**
 * Run the CLI. Returns the exit code, for every argv -- `0` success, `1`
 * expected failure, `2` usage error (`fixtures/cli-exit-codes.yml`).
 *
 * The frameworks render the text; this function decides the number.
 */
export async function main(argv: readonly string[]): Promise<number> {
  const program = buildCli();
  trapExits(program);
  try {
    await program.parseAsync(argv as string[], { from: "user" });
    return 0;
  } catch (err) {
    // CommanderError must be tested before CliError: both extend Error.
    if (err instanceof CommanderError) {
      // commander has already written the help/error text; only the code is
      // ours. `exitCode` is the discriminator, not `code`: `commander.help`
      // carries 0 for an explicit `help` command and 1 for the no-args path.
      return err.exitCode === 0 ? 0 : EXIT_USAGE;
    }
    if (err instanceof CliError) {
      if (err.message) {
        process.stderr.write(`${err.message}\n`);
      }
      return err.exitCode;
    }
    process.stderr.write(`Error: ${(err as Error).message}\n`);
    return 1;
  }
}

// Entry point when invoked directly via the bin shim. `process.exitCode` rather
// than `process.exit()`: the latter does not wait for pending async writes, so a
// large piped payload (`ghagen deps upgrade --check --format json | jq`) can be
// truncated where a `> file` redirect would not.
if (process.argv[1] && import.meta.url === `file://${process.argv[1]}`) {
  main(process.argv.slice(2)).then((code) => {
    process.exitCode = code;
  });
}
