"""Tests for the ``ghagen outdated`` CLI command."""

from __future__ import annotations

import json
from pathlib import Path
from unittest.mock import patch

from typer.testing import CliRunner

from ghagen.cli.main import app

runner = CliRunner()

_CONFIG = """\
from ghagen import App, Job, On, PushTrigger, Step, Workflow

app = App()
ci = Workflow(
    name="CI",
    on=On(push=PushTrigger(branches=["main"])),
    jobs={"test": Job(
        runs_on="ubuntu-latest",
        steps=[
            Step(uses="actions/checkout@v4"),
            Step(uses="actions/setup-python@v5"),
        ],
    )},
)
app.add_workflow(ci, "ci.yml")
"""


_LOCKFILE = """\
# Auto-generated by `ghagen pin`. Do not edit manually.

[pins."actions/checkout@v4"]
sha = "0123456789abcdef0123456789abcdef01234567"
resolved_at = "2026-04-09T00:00:00+00:00"

[pins."actions/setup-python@v5"]
sha = "abcdef0123456789abcdef0123456789abcdef01"
resolved_at = "2026-04-09T00:00:00+00:00"
"""

# Common mock values
_CHECKOUT_TAGS = ["v1", "v2", "v3", "v4", "v5"]
_SETUP_PYTHON_TAGS = ["v4", "v5", "v5.1.0", "v6"]
_NEW_CHECKOUT_SHA = "f" * 40
_NEW_SETUP_PY_SHA = "e" * 40


def _setup_project(tmp_path: Path, *, with_lockfile: bool = False) -> Path:
    """Write a config file and optionally a lockfile; return the config path."""
    config_path = tmp_path / "ghagen_config.py"
    config_path.write_text(_CONFIG)
    if with_lockfile:
        lockfile = tmp_path / ".github" / "ghagen.lock.toml"
        lockfile.parent.mkdir(parents=True)
        lockfile.write_text(_LOCKFILE)
    return config_path


def _mock_list_tags(owner: str, repo: str, *, token=None) -> list[str]:
    """Return fake tags for known repos."""
    if repo == "checkout":
        return _CHECKOUT_TAGS
    if repo == "setup-python":
        return _SETUP_PYTHON_TAGS
    return []


def _mock_resolve_ref(owner: str, repo: str, ref: str, *, token=None) -> str:
    """Return a fake SHA that differs from the lockfile entries."""
    if repo == "checkout":
        return _NEW_CHECKOUT_SHA
    if repo == "setup-python":
        return _NEW_SETUP_PY_SHA
    return "0" * 40


def _mock_track_user_files(app_loader):
    """Call the loader and return the config file path."""
    loaded_app = app_loader()
    # Return the config file based on the root -- in tests we write
    # ghagen_config.py in tmp_path which is also the cwd.
    root = loaded_app.root
    config = root / "ghagen_config.py"
    if config.is_file():
        return {config}
    return set()


class TestOutdatedVersionsMode:
    """Tests for version bump detection."""

    @patch("ghagen.pin.sources.track_user_files", side_effect=_mock_track_user_files)
    @patch("ghagen.pin.resolve.list_tags", side_effect=_mock_list_tags)
    def test_human_output_shows_version_bumps(
        self, mock_tags, mock_track, tmp_path, monkeypatch
    ):
        monkeypatch.chdir(tmp_path)
        monkeypatch.setenv("GITHUB_TOKEN", "fake-token")
        _setup_project(tmp_path)

        result = runner.invoke(app, ["outdated", "--mode", "versions"])
        assert result.exit_code == 0, result.output
        assert "Version updates available" in result.output
        assert "actions/checkout@v4" in result.output
        assert "v5" in result.output
        assert "[major]" in result.output

    @patch("ghagen.pin.sources.track_user_files", side_effect=_mock_track_user_files)
    @patch("ghagen.pin.resolve.list_tags", side_effect=_mock_list_tags)
    def test_json_output(self, mock_tags, mock_track, tmp_path, monkeypatch):
        monkeypatch.chdir(tmp_path)
        monkeypatch.setenv("GITHUB_TOKEN", "fake-token")
        _setup_project(tmp_path)

        result = runner.invoke(app, ["outdated", "--mode", "versions", "--json"])
        assert result.exit_code == 0, result.output
        data = json.loads(result.output)
        assert "version_bumps" in data
        assert "helper_provided" in data
        bumps = data["version_bumps"]
        assert len(bumps) >= 1
        # Check structure of a bump entry
        bump = bumps[0]
        assert "uses" in bump
        assert "current" in bump
        assert "latest" in bump
        assert "severity" in bump

    @patch("ghagen.pin.sources.track_user_files", side_effect=_mock_track_user_files)
    @patch("ghagen.pin.resolve.list_tags", side_effect=_mock_list_tags)
    def test_json_output_has_source_files_for_user_refs(
        self, mock_tags, mock_track, tmp_path, monkeypatch
    ):
        monkeypatch.chdir(tmp_path)
        monkeypatch.setenv("GITHUB_TOKEN", "fake-token")
        _setup_project(tmp_path)

        result = runner.invoke(app, ["outdated", "--mode", "versions", "--json"])
        assert result.exit_code == 0, result.output
        data = json.loads(result.output)
        for bump in data["version_bumps"]:
            if bump["origin"] == "user":
                assert "source_files" in bump
                assert len(bump["source_files"]) > 0


class TestOutdatedLockfileMode:
    """Tests for lockfile staleness detection."""

    @patch("ghagen.pin.sources.track_user_files", side_effect=_mock_track_user_files)
    @patch("ghagen.pin.resolve.resolve_ref", side_effect=_mock_resolve_ref)
    def test_lockfile_stale_detection(
        self, mock_resolve, mock_track, tmp_path, monkeypatch
    ):
        monkeypatch.chdir(tmp_path)
        monkeypatch.setenv("GITHUB_TOKEN", "fake-token")
        _setup_project(tmp_path, with_lockfile=True)

        result = runner.invoke(app, ["outdated", "--mode", "lockfile"])
        assert result.exit_code == 0, result.output
        assert "Stale lockfile entries" in result.output
        assert "actions/checkout@v4" in result.output

    @patch("ghagen.pin.sources.track_user_files", side_effect=_mock_track_user_files)
    @patch("ghagen.pin.resolve.resolve_ref", side_effect=_mock_resolve_ref)
    def test_lockfile_json_output(
        self, mock_resolve, mock_track, tmp_path, monkeypatch
    ):
        monkeypatch.chdir(tmp_path)
        monkeypatch.setenv("GITHUB_TOKEN", "fake-token")
        _setup_project(tmp_path, with_lockfile=True)

        result = runner.invoke(app, ["outdated", "--mode", "lockfile", "--json"])
        assert result.exit_code == 0, result.output
        data = json.loads(result.output)
        assert "lockfile_stale" in data
        stale = data["lockfile_stale"]
        assert len(stale) >= 1
        entry = stale[0]
        assert "current_sha" in entry
        assert "latest_sha" in entry

    @patch("ghagen.pin.sources.track_user_files", side_effect=_mock_track_user_files)
    def test_lockfile_mode_no_lockfile_configured(
        self, mock_track, tmp_path, monkeypatch
    ):
        """When lockfile_path is None, lockfile mode finds nothing stale."""
        monkeypatch.chdir(tmp_path)
        monkeypatch.setenv("GITHUB_TOKEN", "fake-token")

        # Config with lockfile=None
        config = tmp_path / "ghagen_config.py"
        config.write_text(
            """\
from ghagen import App, Job, On, PushTrigger, Step, Workflow

app = App(lockfile=None)
ci = Workflow(
    name="CI",
    on=On(push=PushTrigger(branches=["main"])),
    jobs={"test": Job(
        runs_on="ubuntu-latest",
        steps=[Step(uses="actions/checkout@v4")],
    )},
)
app.add_workflow(ci, "ci.yml")
"""
        )

        result = runner.invoke(app, ["outdated", "--mode", "lockfile", "--json"])
        assert result.exit_code == 0, result.output
        data = json.loads(result.output)
        assert data["lockfile_stale"] == []


class TestOutdatedAllMode:
    """Tests for the default 'all' mode."""

    @patch("ghagen.pin.sources.track_user_files", side_effect=_mock_track_user_files)
    @patch("ghagen.pin.resolve.list_tags", side_effect=_mock_list_tags)
    @patch("ghagen.pin.resolve.resolve_ref", side_effect=_mock_resolve_ref)
    def test_all_mode_includes_both(
        self, mock_resolve, mock_tags, mock_track, tmp_path, monkeypatch
    ):
        monkeypatch.chdir(tmp_path)
        monkeypatch.setenv("GITHUB_TOKEN", "fake-token")
        _setup_project(tmp_path, with_lockfile=True)

        result = runner.invoke(app, ["outdated", "--json"])
        assert result.exit_code == 0, result.output
        data = json.loads(result.output)
        assert "version_bumps" in data
        assert "lockfile_stale" in data
        assert "helper_provided" in data


class TestOutdatedApply:
    """Tests for the --apply flag."""

    @patch("ghagen.pin.sources.track_user_files", side_effect=_mock_track_user_files)
    @patch("ghagen.pin.resolve.list_tags", side_effect=_mock_list_tags)
    def test_apply_modifies_source_files(
        self, mock_tags, mock_track, tmp_path, monkeypatch
    ):
        monkeypatch.chdir(tmp_path)
        monkeypatch.setenv("GITHUB_TOKEN", "fake-token")
        _setup_project(tmp_path)

        result = runner.invoke(
            app, ["outdated", "--mode", "versions", "--apply"]
        )
        assert result.exit_code == 0, result.output
        assert "Applied version bumps" in result.output
        assert "modified" in result.output

        # Verify the config file was actually modified
        config_content = (tmp_path / "ghagen_config.py").read_text()
        assert "actions/checkout@v5" in config_content
        assert "actions/setup-python@v6" in config_content


class TestOutdatedHelperRefs:
    """Tests for helper-provided refs reported separately."""

    @patch("ghagen.pin.resolve.list_tags", side_effect=_mock_list_tags)
    def test_helper_refs_in_json(
        self, mock_tags, tmp_path, monkeypatch
    ):
        monkeypatch.chdir(tmp_path)
        monkeypatch.setenv("GITHUB_TOKEN", "fake-token")

        # Config where all refs come from helper (track_user_files returns empty)
        _setup_project(tmp_path)

        with patch(
            "ghagen.pin.sources.track_user_files",
            side_effect=lambda loader: (loader(), set())[1],
        ):
            result = runner.invoke(
                app, ["outdated", "--mode", "versions", "--json"]
            )

        assert result.exit_code == 0, result.output
        data = json.loads(result.output)
        assert len(data["helper_provided"]) >= 1
        for hp in data["helper_provided"]:
            assert "helper" in hp
            assert hp["helper"] == "ghagen built-in"

    @patch("ghagen.pin.resolve.list_tags", side_effect=_mock_list_tags)
    def test_helper_refs_in_human_output(
        self, mock_tags, tmp_path, monkeypatch
    ):
        monkeypatch.chdir(tmp_path)
        monkeypatch.setenv("GITHUB_TOKEN", "fake-token")
        _setup_project(tmp_path)

        with patch(
            "ghagen.pin.sources.track_user_files",
            side_effect=lambda loader: (loader(), set())[1],
        ):
            result = runner.invoke(
                app, ["outdated", "--mode", "versions"]
            )

        assert result.exit_code == 0, result.output
        assert "Helper-provided action updates" in result.output
        assert "ghagen built-in" in result.output


class TestOutdatedNoUpdates:
    """Tests for the clean exit when everything is up to date."""

    def test_no_updates_human_output(self, tmp_path, monkeypatch):
        monkeypatch.chdir(tmp_path)
        monkeypatch.setenv("GITHUB_TOKEN", "fake-token")
        _setup_project(tmp_path)

        def mock_tags_up_to_date(owner, repo, *, token=None):
            if repo == "checkout":
                return ["v1", "v2", "v3", "v4"]  # v4 is latest
            if repo == "setup-python":
                return ["v4", "v5"]  # v5 is latest
            return []

        with (
            patch(
                "ghagen.pin.sources.track_user_files",
                side_effect=_mock_track_user_files,
            ),
            patch(
                "ghagen.pin.resolve.list_tags",
                side_effect=mock_tags_up_to_date,
            ),
        ):
            result = runner.invoke(app, ["outdated", "--mode", "versions"])

        assert result.exit_code == 0, result.output
        assert "Everything is up to date" in result.output

    def test_no_updates_json_output(self, tmp_path, monkeypatch):
        monkeypatch.chdir(tmp_path)
        monkeypatch.setenv("GITHUB_TOKEN", "fake-token")
        _setup_project(tmp_path)

        def mock_tags_up_to_date(owner, repo, *, token=None):
            if repo == "checkout":
                return ["v1", "v2", "v3", "v4"]
            if repo == "setup-python":
                return ["v4", "v5"]
            return []

        with (
            patch(
                "ghagen.pin.sources.track_user_files",
                side_effect=_mock_track_user_files,
            ),
            patch(
                "ghagen.pin.resolve.list_tags",
                side_effect=mock_tags_up_to_date,
            ),
        ):
            result = runner.invoke(
                app, ["outdated", "--mode", "versions", "--json"]
            )

        assert result.exit_code == 0, result.output
        data = json.loads(result.output)
        assert data["version_bumps"] == []
        assert data["helper_provided"] == []


class TestOutdatedNonSemver:
    """Tests for non-semver refs handled gracefully."""

    def test_non_semver_skipped_in_versions_mode(self, tmp_path, monkeypatch):
        """Refs with non-semver tags (e.g. main, sha) are skipped."""
        monkeypatch.chdir(tmp_path)
        monkeypatch.setenv("GITHUB_TOKEN", "fake-token")

        config = tmp_path / "ghagen_config.py"
        config.write_text(
            """\
from ghagen import App, Job, On, PushTrigger, Step, Workflow

app = App()
ci = Workflow(
    name="CI",
    on=On(push=PushTrigger(branches=["main"])),
    jobs={"test": Job(
        runs_on="ubuntu-latest",
        steps=[Step(uses="actions/checkout@main")],
    )},
)
app.add_workflow(ci, "ci.yml")
"""
        )

        def mock_tags(owner, repo, *, token=None):
            return ["v1", "v2", "v3", "v4", "v5"]

        with (
            patch(
                "ghagen.pin.sources.track_user_files",
                side_effect=_mock_track_user_files,
            ),
            patch("ghagen.pin.resolve.list_tags", side_effect=mock_tags),
        ):
            result = runner.invoke(
                app, ["outdated", "--mode", "versions", "--json"]
            )

        assert result.exit_code == 0, result.output
        data = json.loads(result.output)
        # Non-semver ref "main" should be skipped — no version bumps.
        assert data["version_bumps"] == []


class TestOutdatedTokenHandling:
    """Tests for token resolution."""

    @patch("ghagen.pin.sources.track_user_files", side_effect=_mock_track_user_files)
    @patch("ghagen.pin.resolve.list_tags", side_effect=_mock_list_tags)
    def test_no_token_warning(
        self, mock_tags, mock_track, tmp_path, monkeypatch
    ):
        monkeypatch.chdir(tmp_path)
        monkeypatch.delenv("GITHUB_TOKEN", raising=False)
        monkeypatch.delenv("GH_TOKEN", raising=False)
        _setup_project(tmp_path)

        result = runner.invoke(app, ["outdated", "--mode", "versions"])
        assert "no GitHub token found" in result.output

    @patch("ghagen.pin.sources.track_user_files", side_effect=_mock_track_user_files)
    @patch("ghagen.pin.resolve.list_tags", side_effect=_mock_list_tags)
    def test_token_from_env(
        self, mock_tags, mock_track, tmp_path, monkeypatch
    ):
        monkeypatch.chdir(tmp_path)
        monkeypatch.setenv("GITHUB_TOKEN", "my-token")
        monkeypatch.delenv("GH_TOKEN", raising=False)
        _setup_project(tmp_path)

        result = runner.invoke(app, ["outdated", "--mode", "versions"])
        assert "no GitHub token found" not in result.output

    @patch("ghagen.pin.sources.track_user_files", side_effect=_mock_track_user_files)
    @patch("ghagen.pin.resolve.list_tags", side_effect=_mock_list_tags)
    def test_gh_token_fallback(
        self, mock_tags, mock_track, tmp_path, monkeypatch
    ):
        monkeypatch.chdir(tmp_path)
        monkeypatch.delenv("GITHUB_TOKEN", raising=False)
        monkeypatch.setenv("GH_TOKEN", "gh-token")
        _setup_project(tmp_path)

        result = runner.invoke(app, ["outdated", "--mode", "versions"])
        assert "no GitHub token found" not in result.output


class TestOutdatedErrorHandling:
    """Tests for error handling."""

    def test_invalid_mode(self, tmp_path, monkeypatch):
        monkeypatch.chdir(tmp_path)
        monkeypatch.setenv("GITHUB_TOKEN", "fake-token")
        _setup_project(tmp_path)

        result = runner.invoke(app, ["outdated", "--mode", "invalid"])
        assert result.exit_code == 2
        assert "unknown --mode value" in result.output

    @patch("ghagen.pin.sources.track_user_files", side_effect=_mock_track_user_files)
    def test_api_error_continues_with_warning(
        self, mock_track, tmp_path, monkeypatch
    ):
        """API errors for one repo should not stop processing."""
        monkeypatch.chdir(tmp_path)
        monkeypatch.setenv("GITHUB_TOKEN", "fake-token")
        _setup_project(tmp_path)

        from ghagen.pin.resolve import ResolveError

        def mock_tags_with_error(owner, repo, *, token=None):
            if repo == "checkout":
                raise ResolveError("rate limited")
            return _SETUP_PYTHON_TAGS

        with patch(
            "ghagen.pin.resolve.list_tags", side_effect=mock_tags_with_error
        ):
            result = runner.invoke(
                app, ["outdated", "--mode", "versions", "--json"]
            )

        assert result.exit_code == 0, result.output
        assert "rate limited" in result.output
        data = json.loads(result.stdout)
        # setup-python should still be reported
        uses_list = [b["uses"] for b in data["version_bumps"]]
        assert "actions/setup-python@v5" in uses_list


class TestOutdatedNoRefs:
    """Test behavior when there are no pinnable refs."""

    def test_no_refs_human(self, tmp_path, monkeypatch):
        monkeypatch.chdir(tmp_path)
        monkeypatch.setenv("GITHUB_TOKEN", "fake-token")

        config = tmp_path / "ghagen_config.py"
        config.write_text(
            """\
from ghagen import App, Job, On, PushTrigger, Step, Workflow

app = App()
ci = Workflow(
    name="CI",
    on=On(push=PushTrigger(branches=["main"])),
    jobs={"test": Job(
        runs_on="ubuntu-latest",
        steps=[Step(name="Test", run="echo hello")],
    )},
)
app.add_workflow(ci, "ci.yml")
"""
        )

        with patch(
            "ghagen.pin.sources.track_user_files",
            side_effect=_mock_track_user_files,
        ):
            result = runner.invoke(app, ["outdated"])

        assert result.exit_code == 0, result.output
        assert "Everything is up to date" in result.output

    def test_no_refs_json(self, tmp_path, monkeypatch):
        monkeypatch.chdir(tmp_path)
        monkeypatch.setenv("GITHUB_TOKEN", "fake-token")

        config = tmp_path / "ghagen_config.py"
        config.write_text(
            """\
from ghagen import App, Job, On, PushTrigger, Step, Workflow

app = App()
ci = Workflow(
    name="CI",
    on=On(push=PushTrigger(branches=["main"])),
    jobs={"test": Job(
        runs_on="ubuntu-latest",
        steps=[Step(name="Test", run="echo hello")],
    )},
)
app.add_workflow(ci, "ci.yml")
"""
        )

        with patch(
            "ghagen.pin.sources.track_user_files",
            side_effect=_mock_track_user_files,
        ):
            result = runner.invoke(app, ["outdated", "--json"])

        assert result.exit_code == 0, result.output
        data = json.loads(result.output)
        assert data == {
            "version_bumps": [],
            "lockfile_stale": [],
            "helper_provided": [],
        }
