/**
 * Lockfile data model and YAML I/O for pinned action references.
 *
 * The lockfile maps `uses:` strings (as written in user code) to
 * resolved commit SHAs. On-disk format:
 *
 *     # Auto-generated by `ghagen pin`. Do not edit manually.
 *
 *     pins:
 *       actions/checkout@v4:
 *         sha: 3df4ab11eba7bda6032a0b82a6bb43b11571feac
 *         resolved_at: "2026-04-09T14:30:00+00:00"
 *
 * Note that the on-disk keys are snake_case (`sha`, `resolved_at`)
 * for cross-language interop, while the in-memory shape uses
 * camelCase (`sha`, `resolvedAt`).
 */

import { existsSync, mkdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";
import { parse, stringify } from "yaml";

/** Default lockfile path relative to `App.root`. */
export const DEFAULT_LOCKFILE_PATH = ".ghagen.lock.yml";

const HEADER = "# Auto-generated by `ghagen pin`. Do not edit manually.\n\n";

/** A single resolved pin entry. */
export interface PinEntry {
  /** 40-character commit SHA. */
  readonly sha: string;
  /** UTC timestamp of when this entry was resolved. */
  readonly resolvedAt: Date;
}

/**
 * In-memory representation of a `.ghagen.lock.yml` file.
 *
 * Mutable: callers may add or remove entries via the `pins` map.
 */
export class Lockfile {
  readonly pins: Map<string, PinEntry>;

  constructor(pins?: Map<string, PinEntry> | Iterable<readonly [string, PinEntry]>) {
    this.pins = pins instanceof Map ? pins : new Map(pins ?? []);
  }

  /** Look up a pin entry by the full `uses:` string. */
  get(uses: string): PinEntry | undefined {
    return this.pins.get(uses);
  }

  /** Merge new entries, overwriting existing keys. */
  merge(other: Iterable<readonly [string, PinEntry]>): void {
    for (const [k, v] of other) this.pins.set(k, v);
  }

  /** Remove entries not in *keep*. Returns count of removed entries. */
  prune(keep: ReadonlySet<string>): number {
    let removed = 0;
    for (const k of [...this.pins.keys()]) {
      if (!keep.has(k)) {
        this.pins.delete(k);
        removed++;
      }
    }
    return removed;
  }
}

/** Read a lockfile from disk. Returns an empty `Lockfile` when missing. */
export function readLockfile(path: string): Lockfile {
  if (!existsSync(path) || !statSync(path).isFile()) {
    return new Lockfile();
  }

  const text = readFileSync(path, "utf8");
  let raw: Record<string, unknown>;
  try {
    raw = parse(text);
  } catch (err) {
    throw new Error(`${path}: failed to parse lockfile YAML: ${(err as Error).message}`, {
      cause: err,
    });
  }
  if (!raw) return new Lockfile();

  const pinsRaw = (raw["pins"] ?? {}) as Record<string, unknown>;
  const pins = new Map<string, PinEntry>();
  for (const [uses, entryRaw] of Object.entries(pinsRaw)) {
    if (typeof entryRaw !== "object" || entryRaw === null) {
      throw new Error(`${path}: pin entry for ${uses} must be a table`);
    }
    const entry = entryRaw as Record<string, unknown>;
    const sha = entry["sha"];
    const resolvedAt = entry["resolved_at"];
    if (typeof sha !== "string") {
      throw new Error(`${path}: pin ${uses}: 'sha' must be a string`);
    }
    let resolvedDate: Date;
    if (resolvedAt instanceof Date) {
      resolvedDate = resolvedAt;
    } else if (typeof resolvedAt === "string") {
      resolvedDate = new Date(resolvedAt);
      if (Number.isNaN(resolvedDate.getTime())) {
        throw new Error(`${path}: pin ${uses}: invalid 'resolved_at' timestamp: ${resolvedAt}`);
      }
    } else {
      throw new Error(`${path}: pin ${uses}: 'resolved_at' must be a string or datetime`);
    }
    pins.set(uses, { sha, resolvedAt: resolvedDate });
  }
  return new Lockfile(pins);
}

/** Write a lockfile to disk in sorted order. */
export function writeLockfile(lockfile: Lockfile, path: string): void {
  const sortedKeys = [...lockfile.pins.keys()].sort();
  const pinsObj: Record<string, Record<string, string>> = {};
  for (const uses of sortedKeys) {
    const entry = lockfile.pins.get(uses)!;
    pinsObj[uses] = {
      sha: entry.sha,
      resolved_at: entry.resolvedAt.toISOString().replace(/\.\d{3}Z$/, "+00:00"),
    };
  }

  const body = stringify({ pins: pinsObj });
  const content = HEADER + body;

  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
}
