import { describe, it, expect, beforeEach, afterEach } from "vitest";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { Lockfile, readLockfile, writeLockfile } from "./lockfile.js";

let tmp: string;
beforeEach(() => {
  tmp = mkdtempSync(join(tmpdir(), "ghagen-lockfile-"));
});
afterEach(() => {
  rmSync(tmp, { recursive: true, force: true });
});

describe("Lockfile", () => {
  it("get/merge/prune", () => {
    const lf = new Lockfile();
    lf.merge([
      ["actions/checkout@v4", { sha: "a".repeat(40), resolvedAt: new Date() }],
      ["actions/setup-node@v4", { sha: "b".repeat(40), resolvedAt: new Date() }],
    ]);
    expect(lf.get("actions/checkout@v4")?.sha).toBe("a".repeat(40));
    expect(lf.prune(new Set(["actions/checkout@v4"]))).toBe(1);
    expect(lf.pins.size).toBe(1);
  });
});

describe("readLockfile / writeLockfile", () => {
  it("returns empty lockfile when file missing", () => {
    const lf = readLockfile(join(tmp, "missing.toml"));
    expect(lf.pins.size).toBe(0);
  });

  it("round-trips entries with sorted keys and snake_case on disk", () => {
    const path = join(tmp, "lock.toml");
    const lf = new Lockfile();
    lf.merge([
      [
        "owner/repo-b@v2",
        {
          sha: "b".repeat(40),
          resolvedAt: new Date("2026-04-09T14:30:00Z"),
        },
      ],
      [
        "owner/repo-a@v1",
        {
          sha: "a".repeat(40),
          resolvedAt: new Date("2026-04-08T00:00:00Z"),
        },
      ],
    ]);
    writeLockfile(lf, path);
    const text = readFileSync(path, "utf8");

    // Header is exact.
    expect(text.startsWith("# Auto-generated by `ghagen pin`. Do not edit manually.\n\n")).toBe(
      true,
    );
    // Snake_case keys on disk.
    expect(text).toContain("sha = ");
    expect(text).toContain("resolved_at = ");
    // Sorted: a-pin before b-pin.
    const idxA = text.indexOf("owner/repo-a");
    const idxB = text.indexOf("owner/repo-b");
    expect(idxA).toBeGreaterThan(0);
    expect(idxB).toBeGreaterThan(idxA);

    const round = readLockfile(path);
    expect(round.pins.size).toBe(2);
    const a = round.get("owner/repo-a@v1");
    expect(a?.sha).toBe("a".repeat(40));
    expect(a?.resolvedAt.toISOString()).toBe("2026-04-08T00:00:00.000Z");
  });

  it("reads a Python-written lockfile (string-typed resolved_at)", () => {
    const path = join(tmp, "py.toml");
    writeFileSync(
      path,
      [
        "# Auto-generated by `ghagen pin`. Do not edit manually.",
        "",
        '[pins."actions/checkout@v4"]',
        'sha = "3df4ab11eba7bda6032a0b82a6bb43b11571feac"',
        'resolved_at = "2026-04-09T14:30:00+00:00"',
        "",
      ].join("\n"),
    );
    const lf = readLockfile(path);
    const entry = lf.get("actions/checkout@v4");
    expect(entry?.sha).toBe("3df4ab11eba7bda6032a0b82a6bb43b11571feac");
    expect(entry?.resolvedAt.toISOString()).toBe("2026-04-09T14:30:00.000Z");
  });
});
