/**
 * Lockfile data model and YAML I/O for pinned action references.
 *
 * The lockfile maps `uses:` strings (as written in user code) to resolved
 * commit SHAs. This module is the single home of the on-disk **encoding** and
 * of the accepted **decoding**; neither is delegated to the `yaml` package's
 * scalar-style heuristics or to `new Date()`'s tolerance. The Python port
 * states the same grammar in `packages/python/src/ghagen/pin/lockfile.py`.
 *
 * `.ghagen.lock.yml` grammar:
 *
 * 1. The header line ``# Auto-generated by `ghagen deps pin`. Do not edit
 *    manually.``, followed by a blank line.
 * 2. A single top-level `pins:` mapping, block style, two-space indent. An
 *    empty lockfile is `pins: {}`.
 * 3. Keys are the authored `uses:` strings, ASCII-sorted, emitted plain.
 * 4. **Every value ghagen writes is a double-quoted scalar** — `sha` as well
 *    as `resolved_at` — so the scalar style is ghagen's decision and not the
 *    YAML library's.
 * 5. `resolved_at` is written as UTC, ISO-8601, **whole seconds**, with an
 *    explicit `+00:00` offset. Whole seconds is the only precision both ports
 *    can represent: `Date` has millisecond resolution.
 * 6. A trailing newline; no other trailing whitespace.
 * 7. `resolved_at` is **read** under one grammar in both ports: an ISO-8601
 *    date-time with an explicit UTC designator (`+00:00` or `Z`), quoted or
 *    unquoted, with optional fractional seconds (accepted, truncated to whole
 *    seconds). Everything else throws `LockfileError` — a bare date, a quoted
 *    date, a naive date-time, a non-ISO string such as `April 9, 2026`, and a
 *    non-UTC offset such as `+02:00`.
 *
 * On-disk format:
 *
 *     # Auto-generated by `ghagen deps pin`. Do not edit manually.
 *
 *     pins:
 *       actions/checkout@v4:
 *         sha: "3df4ab11eba7bda6032a0b82a6bb43b11571feac"
 *         resolved_at: "2026-04-09T14:30:00+00:00"
 *
 * `fixtures/expected/lockfile_golden.yml` is the byte oracle: both ports write
 * exactly those bytes and read them back to the same entries.
 *
 * Note that the on-disk keys are snake_case (`sha`, `resolved_at`)
 * for cross-language interop, while the in-memory shape uses
 * camelCase (`sha`, `resolvedAt`).
 */

import { existsSync, mkdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";
import { parse, stringify, Scalar } from "yaml";

// The default lockfile literal is single-homed in the config module.
export { DEFAULT_LOCKFILE_PATH } from "../config.js";

const HEADER = "# Auto-generated by `ghagen deps pin`. Do not edit manually.\n\n";

/** Grammar rule 7: ISO-8601 date-time, optional fraction, explicit UTC. */
const TIMESTAMP_RE = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|\+00:00)$/;

/** A single resolved pin entry. */
export interface PinEntry {
  /** 40-character commit SHA. */
  readonly sha: string;
  /** UTC timestamp of when this entry was resolved. */
  readonly resolvedAt: Date;
}

/** Raised when a lockfile on disk is malformed. */
export class LockfileError extends Error {
  constructor(message: string, options?: { cause?: unknown }) {
    super(message, options);
    this.name = "LockfileError";
  }
}

/**
 * In-memory representation of a `.ghagen.lock.yml` file.
 *
 * The entry map is private: seed it through the constructor, mutate it through
 * `set` and `prune`, and read it through `get`, `has`, `keys`, and `size`. This
 * keeps the invariant that a lockfile only ever holds valid entries.
 */
export class Lockfile {
  readonly #pins: Map<string, PinEntry>;

  constructor(pins?: Map<string, PinEntry> | Iterable<readonly [string, PinEntry]>) {
    this.#pins = pins instanceof Map ? pins : new Map(pins ?? []);
  }

  /** Look up a pin entry by the full `uses:` string. */
  get(uses: string): PinEntry | undefined {
    return this.#pins.get(uses);
  }

  /** Add or replace a single entry. */
  set(uses: string, entry: PinEntry): void {
    this.#pins.set(uses, entry);
  }

  /** Remove entries not in *keep*. Returns count of removed entries. */
  prune(keep: ReadonlySet<string>): number {
    let removed = 0;
    for (const k of [...this.#pins.keys()]) {
      if (!keep.has(k)) {
        this.#pins.delete(k);
        removed++;
      }
    }
    return removed;
  }

  /** Return whether *uses* has an entry. */
  has(uses: string): boolean {
    return this.#pins.has(uses);
  }

  /** Iterate over the `uses:` keys. */
  keys(): IterableIterator<string> {
    return this.#pins.keys();
  }

  /** Number of entries. */
  get size(): number {
    return this.#pins.size;
  }
}

/**
 * The one on-disk timestamp form: UTC, whole seconds, explicit offset (rule 5).
 *
 * The Python peer additionally rejects a naive value; a `Date` is always an
 * absolute instant, so that failure is unrepresentable here.
 */
function encodeTimestamp(d: Date): string {
  return `${d.toISOString().slice(0, 19)}+00:00`;
}

/** The one accepted on-disk timestamp grammar (rule 7). */
function decodeTimestamp(raw: unknown, path: string, uses: string): Date {
  if (typeof raw !== "string" || !TIMESTAMP_RE.test(raw)) {
    throw new LockfileError(
      `${path}: pin ${uses}: 'resolved_at' must be an ISO-8601 UTC timestamp ` +
        `(+00:00 or Z): ${JSON.stringify(raw)}`,
    );
  }
  // Truncate to whole seconds, matching the Python decoder: a `Date` would
  // otherwise keep milliseconds the Python port drops.
  const d = new Date(`${raw.slice(0, 19)}Z`);
  if (Number.isNaN(d.getTime())) {
    throw new LockfileError(`${path}: pin ${uses}: invalid 'resolved_at' timestamp: ${raw}`);
  }
  return d;
}

/** A double-quoted scalar: ghagen decides the style, not `stringify` (rule 4). */
function quoted(s: string): Scalar {
  const sc = new Scalar(s);
  sc.type = Scalar.QUOTE_DOUBLE;
  return sc;
}

/**
 * Read a lockfile from disk, validating every entry.
 *
 * Returns an empty `Lockfile` for exactly two inputs: the file is missing, and
 * the YAML document is empty. Throws `LockfileError` for everything else.
 */
export function readLockfile(path: string): Lockfile {
  if (!existsSync(path) || !statSync(path).isFile()) {
    return new Lockfile();
  }

  const text = readFileSync(path, "utf8");
  let parsed: unknown;
  try {
    parsed = parse(text);
  } catch (err) {
    throw new LockfileError(`${path}: failed to parse lockfile YAML: ${(err as Error).message}`, {
      cause: err,
    });
  }
  // An empty document is the only falsy value that means "empty lockfile";
  // `0`, `""` and `false` are malformed top levels and must reach the check.
  if (parsed === null || parsed === undefined) {
    return new Lockfile();
  }
  if (typeof parsed !== "object" || Array.isArray(parsed)) {
    throw new LockfileError(`${path}: lockfile must be a mapping`);
  }
  const raw = parsed as Record<string, unknown>;

  const pinsValue = raw["pins"];
  if (pinsValue === undefined || pinsValue === null) {
    return new Lockfile();
  }
  if (typeof pinsValue !== "object" || Array.isArray(pinsValue)) {
    throw new LockfileError(`${path}: 'pins' must be a table`);
  }

  const pinsRaw = pinsValue as Record<string, unknown>;
  const pins = new Map<string, PinEntry>();
  for (const [uses, entryRaw] of Object.entries(pinsRaw)) {
    if (typeof entryRaw !== "object" || entryRaw === null || Array.isArray(entryRaw)) {
      throw new LockfileError(`${path}: pin entry for ${uses} must be a table`);
    }
    const entry = entryRaw as Record<string, unknown>;
    const sha = entry["sha"];
    if (typeof sha !== "string") {
      throw new LockfileError(`${path}: pin ${uses}: 'sha' must be a string`);
    }
    pins.set(uses, { sha, resolvedAt: decodeTimestamp(entry["resolved_at"], path, uses) });
  }
  return new Lockfile(pins);
}

/** Write a lockfile to disk in the canonical encoding (grammar rules 1-6). */
export function writeLockfile(lockfile: Lockfile, path: string): void {
  const sortedKeys = [...lockfile.keys()].sort();
  const pinsObj: Record<string, Record<string, Scalar>> = {};
  for (const uses of sortedKeys) {
    const entry = lockfile.get(uses)!;
    pinsObj[uses] = {
      sha: quoted(entry.sha),
      resolved_at: quoted(encodeTimestamp(entry.resolvedAt)),
    };
  }

  const body = stringify({ pins: pinsObj });
  const content = HEADER + body;

  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
}
