"""Tests for the Workflow model."""

from ruamel.yaml.comments import CommentedMap

from ghagen import Job, On, Step, Workflow
from ghagen.models.trigger import PushTrigger


def test_basic_workflow():
    workflow = Workflow(
        name="CI",
        on=On(push=PushTrigger(branches=["main"])),
        jobs={
            "test": Job(
                runs_on="ubuntu-latest",
                steps=[Step(uses="actions/checkout@v4")],
            ),
        },
    )
    yaml_str = workflow.to_yaml()
    assert "name: CI" in yaml_str
    assert "runs-on: ubuntu-latest" in yaml_str
    assert "uses: actions/checkout@v4" in yaml_str


def test_workflow_header():
    workflow = Workflow(
        name="Test",
        jobs={"test": Job(runs_on="ubuntu-latest", steps=[])},
    )
    yaml_str = workflow.to_yaml()
    assert "# This file is generated by ghagen" in yaml_str


def test_workflow_custom_header():
    workflow = Workflow(
        name="Test",
        jobs={"test": Job(runs_on="ubuntu-latest", steps=[])},
    )
    yaml_str = workflow.to_yaml(header="Custom header line")
    assert "# Custom header line" in yaml_str


def test_workflow_no_header():
    workflow = Workflow(
        name="Test",
        jobs={"test": Job(runs_on="ubuntu-latest", steps=[])},
    )
    yaml_str = workflow.to_yaml(include_header=False)
    assert "# " not in yaml_str.split("\n")[0]


def test_workflow_key_ordering():
    workflow = Workflow(
        name="CI",
        env={"CI": "true"},
        on=On(push=PushTrigger(branches=["main"])),
        jobs={"test": Job(runs_on="ubuntu-latest", steps=[])},
    )
    cm = workflow.to_commented_map()
    keys = list(cm.keys())
    assert keys.index("name") < keys.index("on")
    assert keys.index("on") < keys.index("env")
    assert keys.index("env") < keys.index("jobs")


def test_workflow_with_raw_job():
    workflow = Workflow(
        name="Mixed",
        jobs={
            "typed": Job(runs_on="ubuntu-latest", steps=[]),
            "raw": CommentedMap({"runs-on": "self-hosted"}),
        },
    )
    cm = workflow.to_commented_map()
    assert isinstance(cm["jobs"]["raw"], CommentedMap)
    assert cm["jobs"]["raw"]["runs-on"] == "self-hosted"
