"""Lockfile data model and YAML I/O for pinned action references.

The lockfile maps ``uses:`` strings (as written in user code) to resolved
commit SHAs. This module is the single home of the on-disk **encoding** and of
the accepted **decoding**; neither is delegated to ruamel's scalar-style
heuristics or to :mod:`datetime`'s tolerance. The TypeScript port states the
same grammar in ``packages/typescript/src/pin/lockfile.ts``.

``.ghagen.lock.yml`` grammar:

1. The header line ``# Auto-generated by `ghagen deps pin`. Do not edit
   manually.``, followed by a blank line.
2. A single top-level ``pins:`` mapping, block style, two-space indent. An
   empty lockfile is ``pins: {}``.
3. Keys are the authored ``uses:`` strings, ASCII-sorted, emitted plain --
   except a key that would be misread as a different YAML scalar type if
   left unquoted (a bool/null keyword, something that parses as a number) or
   that contains a YAML structural character, which is double-quoted. No
   ``uses:`` string produced by normal ghagen usage needs this; see
   ``_key_needs_quoting``.
4. **Every value ghagen writes is a double-quoted scalar** — ``sha`` as well
   as ``resolved_at`` — so the scalar style is ghagen's decision and not the
   YAML library's.
5. ``resolved_at`` is written as UTC, ISO-8601, **whole seconds**, with an
   explicit ``+00:00`` offset. Whole seconds is the only precision both ports
   can represent: TypeScript's ``Date`` has millisecond resolution.
6. A trailing newline; no other trailing whitespace.
7. ``resolved_at`` is **read** under one grammar in both ports, checked with
   the same regular expression both sides name explicitly rather than
   delegating to a standard-library parser's default leniency:
   ``YYYY-MM-DDTHH:MM:SS(.fraction)?(Z|+00:00)``, quoted or unquoted,
   fractional seconds optional and truncated to whole seconds. Neither
   :meth:`datetime.fromisoformat` (which additionally accepts a space
   separator, offsets without a colon or without minutes, a comma decimal
   separator, basic format with no separators, and non-``:00`` UTC spellings
   such as ``+00:00:00`` or ``-00:00``) nor ruamel's implicit ``!!timestamp``
   resolver for unquoted scalars (which additionally accepts a bare
   space-separated date/time with no offset at all) gets to decide on its
   own — both an unquoted (``TimeStamp``/``datetime``) and a quoted (``str``)
   value are re-serialized to text and re-checked against the same regex
   before being accepted. Everything the regex rejects raises
   :class:`LockfileError` — a bare date, a quoted date, a naive date-time, a
   non-ISO string such as ``April 9, 2026``, and a non-UTC offset such as
   ``+02:00``.

Format::

    # Auto-generated by `ghagen deps pin`. Do not edit manually.

    pins:
      actions/checkout@v4:
        sha: "3df4ab11eba7bda6032a0b82a6bb43b11571feac"
        resolved_at: "2026-04-09T14:30:00+00:00"

``fixtures/expected/lockfile_golden.yml`` is the byte oracle: both ports write
exactly those bytes and read them back to the same entries.

A :class:`Lockfile` always holds valid entries: :func:`read_lockfile`
validates every on-disk entry and raises :class:`LockfileError` on malformed
input — including a YAML syntax error — and the pins map is private so callers
cannot smuggle in invalid state.
"""

from __future__ import annotations

import re
from collections.abc import KeysView, Mapping
from dataclasses import dataclass
from datetime import UTC, datetime, timedelta
from pathlib import Path

from ruamel.yaml import YAML, YAMLError
from ruamel.yaml.scalarstring import DoubleQuotedScalarString

_HEADER = "# Auto-generated by `ghagen deps pin`. Do not edit manually.\n\n"

# Grammar rule 7's one accepted on-disk timestamp shape. Matches the
# TypeScript port's ``TIMESTAMP_RE`` in ``pin/lockfile.ts`` exactly:
# ``datetime.fromisoformat`` (space separators, colonless/minuteless
# offsets, comma decimals, basic format, non-``:00`` UTC spellings such as
# ``+00:00:00`` or ``-00:00``) and ruamel's implicit ``!!timestamp``
# resolver (space-separated date/time, no explicit offset) are both more
# permissive than this regex, and that extra permissiveness is exactly the
# byte divergence this rule closes.
_TIMESTAMP_RE = re.compile(
    r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|\+00:00)$"
)

# Grammar rule 3: a key is quoted only when writing it plain would change
# what it reads back as -- an indicator character, a YAML 1.1 bool/null
# keyword, or something that parses as a number. ghagen decides this once,
# identically in both ports (``_KEY_NEEDS_QUOTING_RE`` here, the same
# pattern as ``KEY_NEEDS_QUOTING_RE`` in the TypeScript peer), rather than
# delegating to either YAML library's own quoting heuristic -- which is
# exactly what diverges: ruamel single-quotes a key like this, the
# TypeScript ``yaml`` package double-quotes it. No ``uses:`` string produced
# by normal ghagen usage hits this (it always contains ``/`` or ``@`` or a
# ``docker://`` prefix), so this only fires for an entry set directly
# through the ``Lockfile`` API.
_KEY_NEEDS_QUOTING_RE = re.compile(
    r"""
    ^$                                                    # empty
    | ^[\[\]{},\#&\*!|>'"%@`]                             # starts with indicator char
    | ^[-?:](?:\s|$)                                      # -, ?, : as block indicator
    | :(?:\s|$)                                           # mapping-value indicator
    | \s\#                                                # inline comment start
    | ^\s | \s$                                           # leading/trailing whitespace
    | ^(?:y|Y|n|N|yes|Yes|YES|no|No|NO|true|True|TRUE
         |false|False|FALSE|on|On|ON|off|Off|OFF
         |null|Null|NULL|~)$                              # YAML 1.1 bool/null keywords
    | ^[-+]?[0-9][0-9_]*$                                 # decimal int
    | ^0[xX][0-9a-fA-F_]+$                                # hex int
    | ^0[oO][0-7_]+$                                      # octal int
    | ^[-+]?(?:\.[0-9]+|[0-9][0-9_]*(?:\.[0-9_]*)?)(?:[eE][-+]?[0-9]+)?$  # float
    | ^[-+]?\.(?:inf|Inf|INF)$ | ^\.(?:nan|NaN|NAN)$      # special floats
    """,
    re.VERBOSE,
)


def _key_needs_quoting(key: str) -> bool:
    """Whether *key* needs an explicit double quote to round-trip as a string."""
    return bool(_KEY_NEEDS_QUOTING_RE.search(key))


class LockfileError(Exception):
    """Raised when a lockfile on disk is malformed."""


@dataclass(frozen=True)
class PinEntry:
    """A single resolved pin entry."""

    sha: str
    """40-character commit SHA."""

    resolved_at: datetime
    """UTC timestamp of when this entry was resolved."""


class Lockfile:
    """In-memory representation of a ``.ghagen.lock.yml`` file.

    The entry map is private: seed it through the constructor, mutate it
    through :meth:`set` and :meth:`prune`, and read it through :meth:`get`,
    :meth:`keys`, ``in`` and ``len()``. This keeps the invariant that a
    lockfile only ever holds valid entries.
    """

    def __init__(self, pins: Mapping[str, PinEntry] | None = None) -> None:
        self._pins: dict[str, PinEntry] = dict(pins) if pins else {}

    def get(self, uses: str) -> PinEntry | None:
        """Look up a pin entry by the full ``uses:`` string."""
        return self._pins.get(uses)

    def set(self, uses: str, entry: PinEntry) -> None:
        """Add or replace a single entry."""
        self._pins[uses] = entry

    def prune(self, keep: set[str]) -> int:
        """Remove entries not in *keep*. Return count of removed entries."""
        to_remove = set(self._pins) - keep
        for key in to_remove:
            del self._pins[key]
        return len(to_remove)

    def __contains__(self, uses: object) -> bool:
        return uses in self._pins

    def keys(self) -> KeysView[str]:
        """Return a view over the ``uses:`` keys."""
        return self._pins.keys()

    def __len__(self) -> int:
        return len(self._pins)


def _encode_timestamp(dt: datetime) -> str:
    """The one on-disk timestamp form: UTC, whole seconds, explicit offset.

    Grammar rule 5. Raises :class:`LockfileError` on a naive *dt*, because
    ``astimezone`` would silently read it as host-local and make the encoder's
    own output machine-dependent. The TypeScript peer needs no such guard: a
    ``Date`` is always an absolute instant.
    """
    if dt.utcoffset() is None:
        raise LockfileError(f"resolved_at must be timezone-aware, got {dt!r}")
    return dt.astimezone(UTC).replace(microsecond=0).isoformat()


def _decode_timestamp(raw: object, path: Path, uses: str) -> datetime:
    """The one accepted on-disk timestamp grammar (rule 7).

    Both branches are checked against the same ``_TIMESTAMP_RE`` before
    either ``datetime.fromisoformat`` or a ruamel ``TimeStamp`` gets a say:
    each is individually more permissive than rule 7 (see ``_TIMESTAMP_RE``),
    and delegating to either verbatim is exactly the divergence this
    function closes. ``str(TimeStamp)`` recovers the scalar's original
    separator character (space vs. ``T``), unlike ``.isoformat()``, which
    normalizes it away and would silently defeat the regex check.
    """
    if isinstance(raw, datetime):
        # ruamel yields a TimeStamp for an unquoted scalar. Note that a bare
        # date yields ``datetime.date``, which is not a ``datetime`` and so
        # falls through to the type error below.
        text = str(raw)
    elif isinstance(raw, str):
        text = raw
    else:
        raise LockfileError(
            f"{path}: pin {uses}: 'resolved_at' must be a string or datetime"
        )
    if not _TIMESTAMP_RE.match(text):
        raise LockfileError(
            f"{path}: pin {uses}: 'resolved_at' must be an ISO-8601 UTC "
            f"timestamp (+00:00 or Z): {raw!r}"
        )
    dt = datetime.fromisoformat(text)
    if dt.utcoffset() != timedelta(0):  # belt and suspenders: regex already enforces
        raise LockfileError(
            f"{path}: pin {uses}: 'resolved_at' must carry an explicit UTC "
            f"offset (+00:00 or Z): {raw!r}"
        )
    return dt.astimezone(UTC).replace(microsecond=0)


def read_lockfile(path: Path) -> Lockfile:
    """Read a lockfile from disk, validating every entry.

    Returns an empty ``Lockfile`` for exactly two inputs: the file is missing,
    and the YAML document is empty. Raises :class:`LockfileError` (naming the
    path and offending key) for everything else — a YAML syntax error, a
    top-level document that is not a mapping, a ``pins`` value that is not a
    mapping, an entry that is not a mapping, a missing or non-string ``sha``,
    and a ``resolved_at`` that is missing or outside grammar rule 7.
    """
    if not path.is_file():
        return Lockfile()

    yaml = YAML()
    try:
        raw = yaml.load(path)
    except YAMLError as exc:
        raise LockfileError(f"{path}: failed to parse lockfile YAML: {exc}") from exc
    if raw is None:
        return Lockfile()
    if not isinstance(raw, Mapping):
        raise LockfileError(f"{path}: lockfile must be a mapping")

    pins_raw = raw.get("pins", {})
    if pins_raw is None:
        return Lockfile()
    if not isinstance(pins_raw, Mapping):
        raise LockfileError(f"{path}: 'pins' must be a mapping")

    pins: dict[str, PinEntry] = {}
    for uses, entry in pins_raw.items():
        if not isinstance(entry, Mapping):
            raise LockfileError(f"{path}: pin entry for {uses} must be a table")

        sha = entry.get("sha")
        if not isinstance(sha, str):
            raise LockfileError(f"{path}: pin {uses}: 'sha' must be a string")

        resolved_dt = _decode_timestamp(entry.get("resolved_at"), path, uses)
        pins[uses] = PinEntry(sha=sha, resolved_at=resolved_dt)
    return Lockfile(pins=pins)


def write_lockfile(lockfile: Lockfile, path: Path) -> None:
    """Write a lockfile to disk in the canonical encoding (grammar rules 1-6).

    Raises :class:`LockfileError` if an entry carries a naive ``resolved_at``.
    """
    pins_dict: dict[str | DoubleQuotedScalarString, dict[str, str]] = {}
    for uses in sorted(lockfile.keys()):
        entry = lockfile.get(uses)
        assert entry is not None  # keys() guarantees presence
        key: str | DoubleQuotedScalarString = (
            DoubleQuotedScalarString(uses) if _key_needs_quoting(uses) else uses
        )
        pins_dict[key] = {
            "sha": DoubleQuotedScalarString(entry.sha),
            "resolved_at": DoubleQuotedScalarString(
                _encode_timestamp(entry.resolved_at)
            ),
        }

    yaml = YAML()
    yaml.default_flow_style = False

    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w") as fh:
        fh.write(_HEADER)
        yaml.dump({"pins": pins_dict}, fh)
