"""Lockfile data model and YAML I/O for pinned action references.

The lockfile maps ``uses:`` strings (as written in user code) to resolved
commit SHAs. This module is the single home of the on-disk **encoding** and of
the accepted **decoding**; neither is delegated to ruamel's scalar-style
heuristics or to :mod:`datetime`'s tolerance. The TypeScript port states the
same grammar in ``packages/typescript/src/pin/lockfile.ts``.

``.ghagen.lock.yml`` grammar:

1. The header line ``# Auto-generated by `ghagen deps pin`. Do not edit
   manually.``, followed by a blank line.
2. A single top-level ``pins:`` mapping, block style, two-space indent. An
   empty lockfile is ``pins: {}``.
3. Keys are the authored ``uses:`` strings, ASCII-sorted, emitted plain.
4. **Every value ghagen writes is a double-quoted scalar** — ``sha`` as well
   as ``resolved_at`` — so the scalar style is ghagen's decision and not the
   YAML library's.
5. ``resolved_at`` is written as UTC, ISO-8601, **whole seconds**, with an
   explicit ``+00:00`` offset. Whole seconds is the only precision both ports
   can represent: TypeScript's ``Date`` has millisecond resolution.
6. A trailing newline; no other trailing whitespace.
7. ``resolved_at`` is **read** under one grammar in both ports: an ISO-8601
   date-time with an explicit UTC designator (``+00:00`` or ``Z``), quoted or
   unquoted, with optional fractional seconds (accepted, truncated to whole
   seconds). Everything else raises :class:`LockfileError` — a bare date, a
   quoted date, a naive date-time, a non-ISO string such as ``April 9, 2026``,
   and a non-UTC offset such as ``+02:00``.

Format::

    # Auto-generated by `ghagen deps pin`. Do not edit manually.

    pins:
      actions/checkout@v4:
        sha: "3df4ab11eba7bda6032a0b82a6bb43b11571feac"
        resolved_at: "2026-04-09T14:30:00+00:00"

``fixtures/expected/lockfile_golden.yml`` is the byte oracle: both ports write
exactly those bytes and read them back to the same entries.

A :class:`Lockfile` always holds valid entries: :func:`read_lockfile`
validates every on-disk entry and raises :class:`LockfileError` on malformed
input — including a YAML syntax error — and the pins map is private so callers
cannot smuggle in invalid state.
"""

from __future__ import annotations

from collections.abc import KeysView, Mapping
from dataclasses import dataclass
from datetime import UTC, datetime, timedelta
from pathlib import Path

from ruamel.yaml import YAML, YAMLError
from ruamel.yaml.scalarstring import DoubleQuotedScalarString

_HEADER = "# Auto-generated by `ghagen deps pin`. Do not edit manually.\n\n"


class LockfileError(Exception):
    """Raised when a lockfile on disk is malformed."""


@dataclass(frozen=True)
class PinEntry:
    """A single resolved pin entry."""

    sha: str
    """40-character commit SHA."""

    resolved_at: datetime
    """UTC timestamp of when this entry was resolved."""


class Lockfile:
    """In-memory representation of a ``.ghagen.lock.yml`` file.

    The entry map is private: seed it through the constructor, mutate it
    through :meth:`set` and :meth:`prune`, and read it through :meth:`get`,
    :meth:`keys`, ``in`` and ``len()``. This keeps the invariant that a
    lockfile only ever holds valid entries.
    """

    def __init__(self, pins: Mapping[str, PinEntry] | None = None) -> None:
        self._pins: dict[str, PinEntry] = dict(pins) if pins else {}

    def get(self, uses: str) -> PinEntry | None:
        """Look up a pin entry by the full ``uses:`` string."""
        return self._pins.get(uses)

    def set(self, uses: str, entry: PinEntry) -> None:
        """Add or replace a single entry."""
        self._pins[uses] = entry

    def prune(self, keep: set[str]) -> int:
        """Remove entries not in *keep*. Return count of removed entries."""
        to_remove = set(self._pins) - keep
        for key in to_remove:
            del self._pins[key]
        return len(to_remove)

    def __contains__(self, uses: object) -> bool:
        return uses in self._pins

    def keys(self) -> KeysView[str]:
        """Return a view over the ``uses:`` keys."""
        return self._pins.keys()

    def __len__(self) -> int:
        return len(self._pins)


def _encode_timestamp(dt: datetime) -> str:
    """The one on-disk timestamp form: UTC, whole seconds, explicit offset.

    Grammar rule 5. Raises :class:`LockfileError` on a naive *dt*, because
    ``astimezone`` would silently read it as host-local and make the encoder's
    own output machine-dependent. The TypeScript peer needs no such guard: a
    ``Date`` is always an absolute instant.
    """
    if dt.utcoffset() is None:
        raise LockfileError(f"resolved_at must be timezone-aware, got {dt!r}")
    return dt.astimezone(UTC).replace(microsecond=0).isoformat()


def _decode_timestamp(raw: object, path: Path, uses: str) -> datetime:
    """The one accepted on-disk timestamp grammar (rule 7)."""
    if isinstance(raw, datetime):
        # ruamel yields a TimeStamp for an unquoted scalar. Note that a bare
        # date yields ``datetime.date``, which is not a ``datetime`` and so
        # falls through to the type error below.
        dt = raw
    elif isinstance(raw, str):
        try:
            dt = datetime.fromisoformat(raw)
        except ValueError as exc:
            raise LockfileError(
                f"{path}: pin {uses}: invalid 'resolved_at' timestamp: {raw!r}"
            ) from exc
    else:
        raise LockfileError(
            f"{path}: pin {uses}: 'resolved_at' must be a string or datetime"
        )
    if dt.utcoffset() != timedelta(0):  # naive (None) and non-UTC both fail
        raise LockfileError(
            f"{path}: pin {uses}: 'resolved_at' must carry an explicit UTC "
            f"offset (+00:00 or Z): {raw!r}"
        )
    return dt.astimezone(UTC).replace(microsecond=0)


def read_lockfile(path: Path) -> Lockfile:
    """Read a lockfile from disk, validating every entry.

    Returns an empty ``Lockfile`` for exactly two inputs: the file is missing,
    and the YAML document is empty. Raises :class:`LockfileError` (naming the
    path and offending key) for everything else — a YAML syntax error, a
    top-level document that is not a mapping, a ``pins`` value that is not a
    mapping, an entry that is not a mapping, a missing or non-string ``sha``,
    and a ``resolved_at`` that is missing or outside grammar rule 7.
    """
    if not path.is_file():
        return Lockfile()

    yaml = YAML()
    try:
        raw = yaml.load(path)
    except YAMLError as exc:
        raise LockfileError(f"{path}: failed to parse lockfile YAML: {exc}") from exc
    if raw is None:
        return Lockfile()
    if not isinstance(raw, Mapping):
        raise LockfileError(f"{path}: lockfile must be a mapping")

    pins_raw = raw.get("pins", {})
    if pins_raw is None:
        return Lockfile()
    if not isinstance(pins_raw, Mapping):
        raise LockfileError(f"{path}: 'pins' must be a mapping")

    pins: dict[str, PinEntry] = {}
    for uses, entry in pins_raw.items():
        if not isinstance(entry, Mapping):
            raise LockfileError(f"{path}: pin entry for {uses} must be a table")

        sha = entry.get("sha")
        if not isinstance(sha, str):
            raise LockfileError(f"{path}: pin {uses}: 'sha' must be a string")

        resolved_dt = _decode_timestamp(entry.get("resolved_at"), path, uses)
        pins[uses] = PinEntry(sha=sha, resolved_at=resolved_dt)
    return Lockfile(pins=pins)


def write_lockfile(lockfile: Lockfile, path: Path) -> None:
    """Write a lockfile to disk in the canonical encoding (grammar rules 1-6).

    Raises :class:`LockfileError` if an entry carries a naive ``resolved_at``.
    """
    pins_dict: dict[str, dict[str, str]] = {}
    for uses in sorted(lockfile.keys()):
        entry = lockfile.get(uses)
        assert entry is not None  # keys() guarantees presence
        pins_dict[uses] = {
            "sha": DoubleQuotedScalarString(entry.sha),
            "resolved_at": DoubleQuotedScalarString(
                _encode_timestamp(entry.resolved_at)
            ),
        }

    yaml = YAML()
    yaml.default_flow_style = False

    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w") as fh:
        fh.write(_HEADER)
        yaml.dump({"pins": pins_dict}, fh)
