"""Tests for ghagen.emitter.header (closure-based API)."""

from __future__ import annotations

from pathlib import Path

import pytest

from ghagen.emitter.header import (
    DEFAULT_HEADER_FN,
    HEADER_VARIABLES,
    HeaderVariables,
    _UNSET,
    build_header_variables,
    format_header,
)

# --- format_header ---------------------------------------------------------


def test_format_header_default_when_unset() -> None:
    """_UNSET sentinel produces the default header."""
    result = format_header(_UNSET, None)
    assert result is not None
    assert "# This file is generated by ghagen from <unknown>." in result
    assert "# Do not edit manually." in result


def test_format_header_static_string_verbatim() -> None:
    """A plain string is wrapped with # but not interpolated."""
    result = format_header("hello\nworld", None)
    assert result == "# hello\n# world\n"


def test_format_header_static_string_no_interpolation() -> None:
    """{placeholders} in strings are NOT interpolated."""
    result = format_header("{source_file} is literal", None)
    assert result == "# {source_file} is literal\n"


def test_format_header_closure_receives_variables() -> None:
    """A callable header receives a HeaderVariables and its result is wrapped."""
    result = format_header(
        lambda vars: f"Generated from {vars.source_file}.",
        None,
    )
    assert result == "# Generated from <unknown>.\n"


def test_format_header_closure_with_source_location(tmp_path: Path) -> None:
    """Closure receives resolved source_file from the source location."""
    (tmp_path / ".ghagen.yml").write_text("")
    src = tmp_path / "ci" / "workflows.py"
    src.parent.mkdir()
    src.write_text("# stub")

    result = format_header(
        lambda vars: f"from {vars.source_file}:{vars.source_line}",
        (str(src), 12),
    )
    assert result == "# from ci/workflows.py:12\n"


def test_format_header_null_suppresses() -> None:
    """None suppresses the header entirely."""
    assert format_header(None, None) is None


def test_format_header_blank_line_renders_bare_hash() -> None:
    result = format_header("line1\n\nline3", None)
    assert result == "# line1\n#\n# line3\n"


def test_format_header_ends_with_newline() -> None:
    result = format_header("x", None)
    assert result is not None
    assert result.endswith("\n")


# --- DEFAULT_HEADER_FN -----------------------------------------------------


def test_default_header_fn_produces_standard_text() -> None:
    vars = HeaderVariables(
        source_file="ci/workflows.py",
        source_line="10",
        tool="ghagen",
        version="1.0.0",
    )
    result = DEFAULT_HEADER_FN(vars)
    assert result == (
        "This file is generated by ghagen from ci/workflows.py.\n"
        "Do not edit manually."
    )


# --- build_header_variables ------------------------------------------------


def test_build_variables_none_source_location() -> None:
    variables = build_header_variables(None)
    assert variables.source_file == "<unknown>"
    assert variables.source_line == "0"
    assert variables.tool == "ghagen"
    assert variables.version  # whatever the installed version is


def test_build_variables_relative_to_app_root(tmp_path: Path) -> None:
    """{source_file} is resolved relative to the .ghagen.yml root."""
    (tmp_path / ".ghagen.yml").write_text("")

    src = tmp_path / "ci" / "workflows.py"
    src.parent.mkdir()
    src.write_text("# stub")

    variables = build_header_variables((str(src), 12))
    assert variables.source_file == "ci/workflows.py"
    assert variables.source_line == "12"


def test_build_variables_fallback_when_no_app_root(tmp_path: Path) -> None:
    """Without a marker file, {source_file} falls back to the absolute path."""
    src = tmp_path / "orphan.py"
    src.write_text("# stub")

    variables = build_header_variables((str(src), 1))
    assert variables.source_file.endswith("orphan.py")


def test_build_variables_tool_is_ghagen() -> None:
    variables = build_header_variables(None)
    assert variables.tool == "ghagen"


def test_build_variables_returns_named_tuple() -> None:
    """build_header_variables returns a HeaderVariables NamedTuple."""
    variables = build_header_variables(None)
    assert isinstance(variables, HeaderVariables)
    # NamedTuple supports tuple unpacking
    source_file, source_line, tool, version = variables
    assert source_file == "<unknown>"
    assert tool == "ghagen"


# --- HEADER_VARIABLES contract ---------------------------------------------


def test_header_variables_contract() -> None:
    """The public contract lists exactly the four supported variables."""
    assert set(HEADER_VARIABLES.keys()) == {
        "source_file",
        "source_line",
        "tool",
        "version",
    }
    # Every entry has a non-empty description.
    for name, desc in HEADER_VARIABLES.items():
        assert desc, f"HEADER_VARIABLES[{name!r}] must have a description"
