"""Auto-generated header comment for YAML output."""

from __future__ import annotations

from importlib.metadata import PackageNotFoundError, version
from pathlib import Path

from ghagen.paths import find_app_root

#: Default template used when ``App(header=...)`` is not set. References
#: ``{source_file}`` so the emitted header automatically points at the
#: Python file that defined the workflow/action.
DEFAULT_HEADER = (
    "This file is generated by ghagen from {source_file}.\n"
    "Do not edit manually."
)

#: Public contract of every variable that can appear in a header template.
#: Maps variable name to a human-readable description. Used by the
#: ``App(header=...)`` docstring, by the error message raised on unknown
#: variables, and by ``docs/comments.md``.
HEADER_VARIABLES: dict[str, str] = {
    "source_file": (
        "Path to the Python file that defined this workflow/action, "
        "relative to the app root (the directory containing "
        ".github/ghagen.toml). Falls back to the absolute path when no "
        "app root can be located."
    ),
    "source_line": (
        "Line number in the source file where the Workflow/Action was "
        "constructed."
    ),
    "tool": "The string 'ghagen'.",
    "version": "The installed ghagen version (e.g. '0.2.1').",
}


def _ghagen_version() -> str:
    try:
        return version("ghagen")
    except PackageNotFoundError:  # pragma: no cover — defensive
        return "unknown"


def build_header_variables(
    source_location: tuple[str, int] | None,
) -> dict[str, str]:
    """Build the substitution dict for one item's header.

    Resolves ``{source_file}`` relative to the app root discovered by
    walking upward from the source file looking for
    ``.github/ghagen.toml``. Falls back to the absolute path when no
    marker is found. Falls back to ``"<unknown>"`` when
    ``source_location`` is None (shouldn't happen for user-defined
    models but is handled defensively).

    Args:
        source_location: The ``(filename, lineno)`` tuple captured by
            :class:`~ghagen.models._base.GhagenModel` during
            construction, or ``None`` if no user frame was recorded.

    Returns:
        A mapping of every name in :data:`HEADER_VARIABLES` to its
        concrete value for this item.
    """
    if source_location is None:
        source_file = "<unknown>"
        source_line = "0"
    else:
        abs_path = Path(source_location[0]).resolve()
        root = find_app_root(abs_path.parent)
        if root is not None:
            try:
                source_file = str(abs_path.relative_to(root))
            except ValueError:
                source_file = str(abs_path)
        else:
            source_file = str(abs_path)
        source_line = str(source_location[1])

    return {
        "source_file": source_file,
        "source_line": source_line,
        "tool": "ghagen",
        "version": _ghagen_version(),
    }


def format_header(template: str, variables: dict[str, str]) -> str:
    """Render a header template and wrap every line with ``# ``.

    Uses :meth:`str.format_map` so users can write ``{source_file}`` in
    their custom header. Literal braces are escaped as ``{{`` / ``}}``
    per Python's standard format-string rules.

    Args:
        template: The raw header template. May contain any subset of
            the names in :data:`HEADER_VARIABLES` as ``{name}``
            placeholders.
        variables: The substitution dict, typically from
            :func:`build_header_variables`.

    Returns:
        The rendered, ``#``-prefixed comment block, always terminated
        with a trailing newline.

    Raises:
        ValueError: If ``template`` references a variable that is not
            present in ``variables``. The error message lists every
            valid name and the brace-escaping hint.
    """
    try:
        text = template.format_map(variables)
    except KeyError as exc:
        unknown = exc.args[0]
        valid = ", ".join(f"{{{name}}}" for name in sorted(HEADER_VARIABLES))
        raise ValueError(
            f"Unknown variable {{{unknown}}} in header template. "
            f"Available variables: {valid}. "
            f"To include a literal brace, double it: {{{{ or }}}}."
        ) from exc

    lines = text.splitlines() or [""]
    return "\n".join(f"# {line}" if line else "#" for line in lines) + "\n"
