"""Auto-generated header comment for YAML output."""

DEFAULT_HEADER = "This file is generated by ghagen. Do not edit manually."


def format_header(header: str | None = None, source: str | None = None) -> str:
    """Format the header comment block for a generated YAML file.

    Args:
        header: Custom header text. If None, uses the default header.
        source: Optional source file path to include in the header.

    Returns:
        A comment block string (with leading # on each line).
    """
    text = header if header is not None else DEFAULT_HEADER
    lines = text.splitlines()

    if source:
        lines.append(f"Source: {source}")

    return "\n".join(f"# {line}" if line else "#" for line in lines) + "\n"
