"""End-to-end header rendering with closure-based API."""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

import pytest

_WORKFLOW_SRC = """\
from ghagen import App, Job, On, PushTrigger, Step, Workflow

ci = Workflow(
    name="CI",
    on=On(push=PushTrigger(branches=["main"])),
    jobs={"test": Job(
        runs_on="ubuntu-latest",
        steps=[Step(uses="actions/checkout@v4")],
    )},
)

app = App(root=".")
app.add_workflow(ci, "ci.yml")
"""


def _load_app(config_path: Path):
    """Dynamically import a workflow Python file and return its ``app``."""
    name = f"_wf_{config_path.stem}_{id(config_path)}"
    spec = importlib.util.spec_from_file_location(name, config_path)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    try:
        spec.loader.exec_module(module)
        return module.app
    finally:
        sys.modules.pop(name, None)


def test_synth_renders_default_header_with_source_file(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """App.synth() writes a header that auto-mentions the source .py file."""
    (tmp_path / ".ghagen.yml").write_text("")

    wf_py = tmp_path / "ci" / "workflows.py"
    wf_py.parent.mkdir()
    wf_py.write_text(_WORKFLOW_SRC)

    monkeypatch.chdir(tmp_path)
    app = _load_app(wf_py)
    written = app.synth()

    assert len(written) == 1
    content = Path(written[0]).read_text()

    expected = "# This file is generated by ghagen from ci/workflows.py.\n"
    assert content.startswith(expected), f"unexpected header:\n{content[:200]}"
    assert "# Do not edit manually." in content
    assert "name: CI" in content


def test_synth_renders_closure_header(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Users can override the header with a closure."""
    (tmp_path / ".ghagen.yml").write_text("")

    wf_py = tmp_path / "wf.py"
    wf_py.write_text(
        "from ghagen import App, Job, On, PushTrigger, Step, Workflow\n"
        "\n"
        "ci = Workflow(\n"
        '    name="CI",\n'
        '    on=On(push=PushTrigger(branches=["main"])),\n'
        '    jobs={"test": Job(runs_on="ubuntu-latest", steps=[])},\n'
        ")\n"
        "\n"
        'app = App(root=".", header=lambda vars: f"AUTO: from {vars.source_file} via {vars.tool}")\n'
        'app.add_workflow(ci, "ci.yml")\n'
    )

    monkeypatch.chdir(tmp_path)
    app = _load_app(wf_py)
    written = app.synth()

    content = Path(written[0]).read_text()
    assert content.startswith("# AUTO: from wf.py via ghagen\n"), (
        f"unexpected header:\n{content[:200]}"
    )


def test_synth_renders_static_string_header(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """A static string header is emitted verbatim (no interpolation)."""
    (tmp_path / ".ghagen.yml").write_text("")

    wf_py = tmp_path / "wf.py"
    wf_py.write_text(
        "from ghagen import App, Job, On, PushTrigger, Step, Workflow\n"
        "\n"
        "ci = Workflow(\n"
        '    name="CI",\n'
        '    on=On(push=PushTrigger(branches=["main"])),\n'
        '    jobs={"test": Job(runs_on="ubuntu-latest", steps=[])},\n'
        ")\n"
        "\n"
        'app = App(root=".", header="Static header with {braces}")\n'
        'app.add_workflow(ci, "ci.yml")\n'
    )

    monkeypatch.chdir(tmp_path)
    app = _load_app(wf_py)
    written = app.synth()

    content = Path(written[0]).read_text()
    assert content.startswith("# Static header with {braces}\n"), (
        f"unexpected header:\n{content[:200]}"
    )


def test_synth_null_header_suppresses(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """header=None suppresses the header entirely."""
    (tmp_path / ".ghagen.yml").write_text("")

    wf_py = tmp_path / "wf.py"
    wf_py.write_text(
        "from ghagen import App, Job, On, PushTrigger, Step, Workflow\n"
        "\n"
        "ci = Workflow(\n"
        '    name="CI",\n'
        '    on=On(push=PushTrigger(branches=["main"])),\n'
        '    jobs={"test": Job(runs_on="ubuntu-latest", steps=[])},\n'
        ")\n"
        "\n"
        'app = App(root=".", header=None)\n'
        'app.add_workflow(ci, "ci.yml")\n'
    )

    monkeypatch.chdir(tmp_path)
    app = _load_app(wf_py)
    written = app.synth()

    content = Path(written[0]).read_text()
    assert not content.startswith("#"), (
        f"expected no header comment:\n{content[:200]}"
    )
    assert "name: CI" in content


def test_synth_per_workflow_source_file(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Two workflows from two different .py files each get their own source."""
    (tmp_path / ".ghagen.yml").write_text("")

    wfs = tmp_path / "wfs"
    wfs.mkdir()
    (wfs / "a.py").write_text(
        "from ghagen import Job, On, PushTrigger, Step, Workflow\n"
        "\n"
        "wf_a = Workflow(\n"
        '    name="A",\n'
        '    on=On(push=PushTrigger(branches=["main"])),\n'
        '    jobs={"test": Job(runs_on="ubuntu-latest", steps=[])},\n'
        ")\n"
    )
    (wfs / "b.py").write_text(
        "from ghagen import Job, On, PushTrigger, Step, Workflow\n"
        "\n"
        "wf_b = Workflow(\n"
        '    name="B",\n'
        '    on=On(push=PushTrigger(branches=["main"])),\n'
        '    jobs={"test": Job(runs_on="ubuntu-latest", steps=[])},\n'
        ")\n"
    )
    entry = tmp_path / "entry.py"
    entry.write_text(
        "import sys\n"
        "from pathlib import Path\n"
        'sys.path.insert(0, str(Path(__file__).parent / "wfs"))\n'
        "from ghagen import App\n"
        "import a, b\n"
        "\n"
        'app = App(root=".")\n'
        'app.add_workflow(a.wf_a, "a.yml")\n'
        'app.add_workflow(b.wf_b, "b.yml")\n'
    )

    monkeypatch.chdir(tmp_path)
    app = _load_app(entry)
    written = app.synth()

    assert len(written) == 2
    by_name = {Path(p).name: Path(p).read_text() for p in written}

    assert by_name["a.yml"].startswith(
        "# This file is generated by ghagen from wfs/a.py.\n"
    ), f"a.yml header:\n{by_name['a.yml'][:200]}"
    assert by_name["b.yml"].startswith(
        "# This file is generated by ghagen from wfs/b.py.\n"
    ), f"b.yml header:\n{by_name['b.yml'][:200]}"
