"""Lockfile data model and TOML I/O for pinned action references.

The lockfile maps ``uses:`` strings (as written in user code) to resolved
commit SHAs.  Format::

    # Auto-generated by ``ghagen pin``. Do not edit manually.

    [pins."actions/checkout@v4"]
    sha = "3df4ab11eba7bda6032a0b82a6bb43b11571feac"
    resolved_at = "2026-04-09T14:30:00Z"
"""

from __future__ import annotations

import tomllib
from dataclasses import dataclass, field
from datetime import UTC, datetime
from pathlib import Path

import tomli_w

#: Default lockfile path relative to ``App.root``.
DEFAULT_LOCKFILE_PATH = Path(".github/ghagen.lock.toml")

_HEADER = "# Auto-generated by `ghagen pin`. Do not edit manually.\n\n"


@dataclass(frozen=True)
class PinEntry:
    """A single resolved pin entry."""

    sha: str
    """40-character commit SHA."""

    resolved_at: datetime
    """UTC timestamp of when this entry was resolved."""


@dataclass
class Lockfile:
    """In-memory representation of a ``ghagen.lock.toml`` file."""

    pins: dict[str, PinEntry] = field(default_factory=dict)

    def get(self, uses: str) -> PinEntry | None:
        """Look up a pin entry by the full ``uses:`` string."""
        return self.pins.get(uses)

    def merge(self, other: dict[str, PinEntry]) -> None:
        """Merge new entries into this lockfile, overwriting existing keys."""
        self.pins.update(other)

    def prune(self, keep: set[str]) -> int:
        """Remove entries not in *keep*. Return count of removed entries."""
        to_remove = set(self.pins) - keep
        for key in to_remove:
            del self.pins[key]
        return len(to_remove)


def read_lockfile(path: Path) -> Lockfile:
    """Read a lockfile from disk. Returns empty ``Lockfile`` if missing."""
    if not path.is_file():
        return Lockfile()

    raw = tomllib.loads(path.read_text())
    pins: dict[str, PinEntry] = {}
    for uses, entry in raw.get("pins", {}).items():
        pins[uses] = PinEntry(
            sha=entry["sha"],
            resolved_at=datetime.fromisoformat(entry["resolved_at"]),
        )
    return Lockfile(pins=pins)


def write_lockfile(lockfile: Lockfile, path: Path) -> None:
    """Write a lockfile to disk in sorted order."""
    pins_dict: dict[str, dict[str, str]] = {}
    for uses in sorted(lockfile.pins):
        entry = lockfile.pins[uses]
        pins_dict[uses] = {
            "sha": entry.sha,
            "resolved_at": entry.resolved_at.astimezone(UTC).isoformat(),
        }

    path.parent.mkdir(parents=True, exist_ok=True)
    content = _HEADER + tomli_w.dumps({"pins": pins_dict})
    path.write_text(content)
