"""Auto-generated header comment for YAML output."""

from __future__ import annotations

from importlib.metadata import PackageNotFoundError, version
from pathlib import Path
from typing import Callable, NamedTuple

from ghagen.paths import find_app_root

#: Public contract of every variable that can appear in a header
#: closure. Maps variable name to a human-readable description. Used by
#: the ``App(header=...)`` docstring and by ``docs/comments.md``.
HEADER_VARIABLES: dict[str, str] = {
    "source_file": (
        "Path to the Python file that defined this workflow/action, "
        "relative to the app root (the directory containing "
        ".ghagen.yml). Falls back to the absolute path when no "
        "app root can be located."
    ),
    "source_line": (
        "Line number in the source file where the Workflow/Action was constructed."
    ),
    "tool": "The string 'ghagen'.",
    "version": "The installed ghagen version (e.g. '0.2.1').",
}


class HeaderVariables(NamedTuple):
    """Variables passed to a header closure."""

    source_file: str
    source_line: str
    tool: str
    version: str


#: A closure that receives header variables and returns plain text.
HeaderFn = Callable[[HeaderVariables], str]

#: The header option accepted by ``App``, ``to_yaml``, and ``to_yaml_file``.
#:
#: - **callable** — called with a :class:`HeaderVariables` object, returns
#:   plain text
#: - **str** — output verbatim (no interpolation)
#: - **None** — suppress header entirely
#: - **omitted** (``_UNSET`` sentinel) — use :data:`DEFAULT_HEADER_FN`
HeaderOption = HeaderFn | str | None

#: Sentinel for "header not provided" — distinct from ``None`` which
#: means "suppress header".
_UNSET: object = object()


def _ghagen_version() -> str:
    try:
        return version("ghagen")
    except PackageNotFoundError:  # pragma: no cover — defensive
        return "unknown"


def default_header_fn(vars: HeaderVariables) -> str:
    """Default header closure. Produces the standard ghagen header text."""
    return (
        f"This file is generated by ghagen from {vars.source_file}.\n"
        "Do not edit manually."
    )


#: The default header closure, used when no ``header`` option is provided.
DEFAULT_HEADER_FN: HeaderFn = default_header_fn


def build_header_variables(
    source_location: tuple[str, int] | None,
) -> HeaderVariables:
    """Build the variables for one item's header.

    Resolves ``source_file`` relative to the app root discovered by
    walking upward from the source file looking for
    ``.ghagen.yml``. Falls back to the absolute path when no
    marker is found. Falls back to ``"<unknown>"`` when
    ``source_location`` is None (shouldn't happen for user-defined
    models but is handled defensively).

    Args:
        source_location: The ``(filename, lineno)`` tuple captured by
            :class:`~ghagen.models._base.GhagenModel` during
            construction, or ``None`` if no user frame was recorded.

    Returns:
        A :class:`HeaderVariables` instance with concrete values for
        this item.
    """
    if source_location is None:
        source_file = "<unknown>"
        source_line = "0"
    else:
        abs_path = Path(source_location[0]).resolve()
        root = find_app_root(abs_path.parent)
        if root is not None:
            try:
                source_file = str(abs_path.relative_to(root))
            except ValueError:
                source_file = str(abs_path)
        else:
            source_file = str(abs_path)
        source_line = str(source_location[1])

    return HeaderVariables(
        source_file=source_file,
        source_line=source_line,
        tool="ghagen",
        version=_ghagen_version(),
    )


def format_header(
    header: HeaderOption | object,
    source_location: tuple[str, int] | None,
) -> str | None:
    """Resolve a header option to a ``#``-prefixed comment block.

    Args:
        header: The header option — a callable, a static string,
            ``None`` (suppress), or ``_UNSET`` (use default).
        source_location: Source location tuple for variable building.

    Returns:
        The rendered, ``#``-prefixed comment block terminated with a
        trailing newline, or ``None`` if the header is suppressed.
    """
    if header is None:
        return None

    if header is _UNSET:
        fn: HeaderFn | str = DEFAULT_HEADER_FN
    else:
        fn = header  # type: ignore[assignment]

    if isinstance(fn, str):
        text = fn
    else:
        variables = build_header_variables(source_location)
        text = fn(variables)

    lines = text.splitlines() or [""]
    return "\n".join(f"# {line}" if line else "#" for line in lines) + "\n"
