"""Auto-generated header comment for YAML output."""

from __future__ import annotations

from collections.abc import Callable
from importlib.metadata import PackageNotFoundError, version
from pathlib import Path
from typing import TypedDict

from ghagen.paths import find_app_root

#: Default template used when ``App(header=...)`` is not set. References
#: ``{source_file}`` so the emitted header automatically points at the
#: Python file that defined the workflow/action.
DEFAULT_HEADER = (
    "This file is generated by ghagen from {source_file}.\nDo not edit manually."
)

#: Public contract of every variable available to a header closure. Maps
#: variable name to a human-readable description. Used by the
#: ``App(header=...)`` docstring and by ``docs/comments.md``.
HEADER_VARIABLES: dict[str, str] = {
    "source_file": (
        "Path to the Python file that defined this workflow/action, "
        "relative to the app root (the directory containing "
        ".ghagen.yml). Falls back to the absolute path when no "
        "app root can be located."
    ),
    "source_line": (
        "Line number in the source file where the Workflow/Action was constructed."
    ),
    "tool": "The string 'ghagen'.",
    "version": "The installed ghagen version (e.g. '0.2.1').",
}


class HeaderVariables(TypedDict):
    """Typed shape of the variables passed to a header closure.

    Mirrors :class:`ghagen.emitter.header.HeaderVariables` in the
    TypeScript package so closures written against the typed API behave
    identically across both languages.
    """

    source_file: str
    source_line: str
    tool: str
    version: str


class _DefaultSentinel:
    """Marker for "use ghagen's default header".

    Distinguishes "argument not passed" from "argument explicitly
    ``None``" — under the new contract ``None`` means "skip header
    emission", so a separate sentinel is needed for the default-template
    case.
    """

    _instance: _DefaultSentinel | None = None

    def __new__(cls) -> _DefaultSentinel:
        if cls._instance is None:
            cls._instance = super().__new__(cls)
        return cls._instance

    def __repr__(self) -> str:  # pragma: no cover — diagnostic helper
        return "<DEFAULT>"


#: Singleton sentinel. Use ``is`` for identity checks.
DEFAULT: _DefaultSentinel = _DefaultSentinel()

#: Type alias for the four shapes a ``header`` argument may take.
HeaderInput = str | None | Callable[[HeaderVariables], str] | _DefaultSentinel


def _ghagen_version() -> str:
    try:
        return version("ghagen")
    except PackageNotFoundError:  # pragma: no cover — defensive
        return "unknown"


def build_header_variables(
    source_location: tuple[str, int] | None,
) -> HeaderVariables:
    """Build the substitution dict for one item's header.

    Resolves ``{source_file}`` relative to the app root discovered by
    walking upward from the source file looking for
    ``.ghagen.yml``. Falls back to the absolute path when no
    marker is found. Falls back to ``"<unknown>"`` when
    ``source_location`` is None (shouldn't happen for user-defined
    models but is handled defensively).

    Args:
        source_location: The ``(filename, lineno)`` tuple captured by
            :class:`~ghagen.models._base.GhagenModel` during
            construction, or ``None`` if no user frame was recorded.

    Returns:
        A mapping of every name in :data:`HEADER_VARIABLES` to its
        concrete value for this item.
    """
    if source_location is None:
        source_file = "<unknown>"
        source_line = "0"
    else:
        abs_path = Path(source_location[0]).resolve()
        root = find_app_root(abs_path.parent)
        if root is not None:
            try:
                source_file = str(abs_path.relative_to(root))
            except ValueError:
                source_file = str(abs_path)
        else:
            source_file = str(abs_path)
        source_line = str(source_location[1])

    return {
        "source_file": source_file,
        "source_line": source_line,
        "tool": "ghagen",
        "version": _ghagen_version(),
    }


def _wrap_as_comment(text: str) -> str:
    """Wrap *text* with ``# `` line prefixes, terminated by a newline."""
    lines = text.splitlines() or [""]
    return "\n".join(f"# {line}" if line else "#" for line in lines) + "\n"


def format_header(
    header: HeaderInput,
    source_location: tuple[str, int] | None,
) -> str | None:
    """Resolve a ``header`` argument into a ``#``-prefixed comment block.

    Branching:

    - :data:`DEFAULT` — render the internal default template with the
      captured source-file variables. This is the only place
      ``{variable}`` substitution happens.
    - ``None``        — return ``None``; the caller skips emitting any
      header.
    - ``str``         — emit verbatim. No placeholder substitution on
      user-supplied strings; literal braces survive unchanged.
    - callable        — invoke with a fully-populated
      :class:`HeaderVariables` and emit the returned string.

    Args:
        header: One of the four shapes documented above.
        source_location: Captured ``(filename, lineno)`` tuple for the
            workflow/action being emitted.

    Returns:
        The wrapped header comment, terminated with a trailing
        newline, or ``None`` to indicate "no header".
    """
    if header is None:
        return None

    if isinstance(header, str):
        return _wrap_as_comment(header)

    variables = build_header_variables(source_location)

    if isinstance(header, _DefaultSentinel):
        text = DEFAULT_HEADER.format_map(variables)
        return _wrap_as_comment(text)

    # callable — typed as Callable[[HeaderVariables], str]
    text = header(variables)
    return _wrap_as_comment(text)
