import { describe, it, expect } from "vitest";
import {
  buildHeaderVariables,
  DEFAULT_HEADER,
  formatHeader,
  HEADER_VARIABLES,
} from "./header.js";

describe("formatHeader()", () => {
  it("uses the default template when called with no template", () => {
    // Default header references {source_file} — passing null location
    // makes it render as <unknown>.
    const result = formatHeader();
    expect(result).toContain("This file is generated by ghagen from <unknown>");
    expect(result).toContain("Do not edit manually.");
  });

  it("uses a custom template as-is when it has no placeholders", () => {
    expect(formatHeader("Custom header text")).toBe("Custom header text");
  });

  it("substitutes {tool} and {version} placeholders", () => {
    const result = formatHeader("Built with {tool} v{version}");
    expect(result).toMatch(/^Built with ghagen v\d+\.\d+\.\d+$/);
  });

  it("falls back to default when null is passed", () => {
    expect(formatHeader(null)).toBe(formatHeader());
  });

  it("substitutes {source_file} and {source_line}", () => {
    const result = formatHeader(
      "from {source_file}:{source_line}",
      { file: "/repo/.github/workflows.ts", line: 42 },
    );
    // Without an app root in /repo, source_file falls back to abs path.
    expect(result).toContain(":42");
    expect(result).toContain("workflows.ts");
  });

  it("throws on unknown placeholders", () => {
    expect(() => formatHeader("Hello {unknown}")).toThrow(/Unknown variable/);
  });
});

describe("buildHeaderVariables()", () => {
  it("falls back to <unknown>/0 when location is null", () => {
    const vars = buildHeaderVariables(null);
    expect(vars.source_file).toBe("<unknown>");
    expect(vars.source_line).toBe("0");
    expect(vars.tool).toBe("ghagen");
    expect(vars.version).toMatch(/^\d+\.\d+\.\d+$/);
  });
});

describe("DEFAULT_HEADER", () => {
  it("references the source file placeholder", () => {
    expect(DEFAULT_HEADER).toContain("{source_file}");
  });
});

describe("HEADER_VARIABLES", () => {
  it("documents every variable used by the default template", () => {
    expect(HEADER_VARIABLES).toHaveProperty("source_file");
    expect(HEADER_VARIABLES).toHaveProperty("source_line");
    expect(HEADER_VARIABLES).toHaveProperty("tool");
    expect(HEADER_VARIABLES).toHaveProperty("version");
  });
});
