/**
 * Auto-generated header comment for YAML output.
 *
 * `formatHeader` owns the emitted header bytes end to end: the `#` prefix, the
 * line-break set, blank-line rendering and the trailing newline are all decided
 * here, and the writer concatenates the result. The backend stringifier never
 * sees header text — it separates a document `commentBefore` from the body with
 * a blank line and silently drops a falsy one, neither of which is
 * configurable, so a header routed through the document node could not match
 * the Python port's bytes.
 *
 * Peer of `packages/python/src/ghagen/emitter/header.py`. The two return
 * byte-identical blocks for byte-identical inputs, and
 * `fixtures/expected/header_*.yml` is the assertion of that — read
 * byte-for-byte by both suites.
 */

import { readFileSync } from "node:fs";
import { dirname, isAbsolute, relative, resolve } from "node:path";
import type { SourceLocation } from "../_source_location.js";
import { findAppRoot } from "../config.js";
import { renderBlockComment } from "./comment-geometry.js";

/**
 * Default template used when `App({ header: ... })` is not set.
 * References `{source_file}` so the emitted header automatically points
 * at the TS/JS file that defined the workflow/action.
 */
export const DEFAULT_HEADER =
  "This file is generated by ghagen from {source_file}.\nDo not edit manually.";

/**
 * Public contract of every variable that can appear in a header
 * template. Maps variable name to a human-readable description.
 */
export const HEADER_VARIABLES: Record<string, string> = {
  source_file:
    "Path to the TS/JS file that defined this workflow/action, relative " +
    "to the app root (the directory containing .ghagen.yml). " +
    "Falls back to the absolute path when no app root can be located.",
  source_line: "Line number in the source file where the workflow/action was constructed.",
  tool: "The string 'ghagen'.",
  version: "The installed ghagen version (e.g. '0.3.0').",
};

/**
 * Read the package version from package.json. Computed once at module
 * load. Resolves package.json relative to this file via
 * `import.meta.url` so the lookup works whether ghagen is installed
 * from npm or run from source.
 */
const GHAGEN_VERSION: string = (() => {
  try {
    const url = new URL("../../package.json", import.meta.url);
    const text = readFileSync(url, "utf8");
    const pkg = JSON.parse(text) as { version?: string };
    return pkg.version ?? "unknown";
  } catch {
    return "unknown";
  }
})();

/** Variables substituted into a header template. */
export interface HeaderVariables {
  source_file: string;
  source_line: string;
  tool: string;
  version: string;
}

/**
 * Build the substitution dict for one item's header.
 *
 * Resolves `{source_file}` relative to the app root discovered by
 * walking upward from the source file looking for
 * `.ghagen.yml`. Falls back to the absolute path when no
 * marker is found. Falls back to `<unknown>` when `sourceLocation` is
 * `null`.
 */
export function buildHeaderVariables(sourceLocation: SourceLocation | null): HeaderVariables {
  let sourceFile: string;
  let sourceLine: string;
  if (sourceLocation === null) {
    sourceFile = "<unknown>";
    sourceLine = "0";
  } else {
    const absPath = isAbsolute(sourceLocation.file)
      ? sourceLocation.file
      : resolve(sourceLocation.file);
    const root = findAppRoot(dirname(absPath));
    if (root !== null) {
      const rel = relative(root, absPath);
      sourceFile = rel === "" || rel.startsWith("..") ? absPath : rel;
    } else {
      sourceFile = absPath;
    }
    sourceLine = String(sourceLocation.line);
  }
  return {
    source_file: sourceFile,
    source_line: sourceLine,
    tool: "ghagen",
    version: GHAGEN_VERSION,
  };
}

/**
 * Split header text into lines, dropping one trailing break.
 *
 * The break set is Python `str.splitlines()`'s, written out rather than
 * inherited, so both ports implement the same *stated* rule. It is not an
 * arbitrary choice: ruamel rejects VT/FF/FS/GS/RS outright inside a comment
 * ("unacceptable character") and rescans NEL/U+2028/U+2029 as line breaks, so
 * any of them surviving into the emitted comment produces a document the
 * Python port cannot read back.
 */
// eslint-disable-next-line no-control-regex -- the control characters are the point
const HEADER_BREAK = /\r\n|[\n\r\v\f\x1c\x1d\x1e\x85\u2028\u2029]/;

function splitHeaderLines(text: string): string[] {
  const lines = text.split(HEADER_BREAK);
  if (lines.length > 0 && lines[lines.length - 1] === "") {
    lines.pop();
  }
  return lines.length === 0 ? [""] : lines;
}

/**
 * Wrap header text as a `#`-prefixed block terminated by exactly one "\n".
 *
 * The per-line prefixing is `renderBlockComment`'s, shared with TypeScript's
 * in-document block comments so the two cannot drift on it.
 */
function wrapAsComment(text: string): string {
  return renderBlockComment(splitHeaderLines(text).join("\n")) + "\n";
}

/**
 * Resolve a header value into the exact bytes that precede the YAML body.
 *
 * Branching:
 *
 * - `null`      → return `null`; the caller skips emitting any header.
 * - `undefined` → render `DEFAULT_HEADER` with the captured source-file
 *   variables. This is the only place `{variable}` substitution happens.
 * - `string`    → wrap the string as-is. No placeholder substitution
 *   on user-supplied strings — literal `{` survives unchanged.
 * - function    → invoke with a fully-populated `HeaderVariables` and
 *   wrap its result.
 *
 * Returns a `#`-prefixed comment block terminated by exactly one "\n": every
 * line gains a "# " prefix, a blank line renders as a bare "#", one trailing
 * line break in the input is dropped, and CRLF, CR, LF, VT, FF, FS, GS, RS,
 * NEL, LINE SEPARATOR and PARAGRAPH SEPARATOR are all line breaks. Returns
 * `null`, and only `null`, to mean "emit no header". `""` is a header: it
 * renders as "#\n".
 */
export function formatHeader(
  header: string | null | ((vars: HeaderVariables) => string) | undefined,
  sourceLocation?: SourceLocation | null,
): string | null {
  if (header === null) {
    return null;
  }
  if (typeof header === "string") {
    return wrapAsComment(header);
  }
  const variables = buildHeaderVariables(sourceLocation ?? null);
  if (header === undefined) {
    return wrapAsComment(
      DEFAULT_HEADER.replace(/\{(\w+)\}/g, (_, key: string) => {
        const value = variables[key as keyof HeaderVariables];
        if (value === undefined) {
          throw new Error(`Internal error: DEFAULT_HEADER references unknown variable {${key}}.`);
        }
        return value;
      }),
    );
  }
  return wrapAsComment(header(variables));
}
