/**
 * Auto-generated header comment for YAML output.
 *
 * Mirrors `packages/python/src/ghagen/emitter/header.py` so the two
 * implementations emit identical headers given identical inputs.
 */

import { readFileSync } from "node:fs";
import { dirname, isAbsolute, relative, resolve } from "node:path";
import type { SourceLocation } from "../_source_location.js";
import { findAppRoot } from "../paths.js";

/**
 * Default template used when `App({ header: ... })` is not set.
 * References `{source_file}` so the emitted header automatically points
 * at the TS/JS file that defined the workflow/action.
 */
export const DEFAULT_HEADER =
  "This file is generated by ghagen from {source_file}.\nDo not edit manually.";

/**
 * Public contract of every variable that can appear in a header
 * template. Maps variable name to a human-readable description.
 */
export const HEADER_VARIABLES: Record<string, string> = {
  source_file:
    "Path to the TS/JS file that defined this workflow/action, relative " +
    "to the app root (the directory containing .ghagen.yml). " +
    "Falls back to the absolute path when no app root can be located.",
  source_line: "Line number in the source file where the workflow/action was constructed.",
  tool: "The string 'ghagen'.",
  version: "The installed ghagen version (e.g. '0.3.0').",
};

/**
 * Read the package version from package.json. Computed once at module
 * load. Resolves package.json relative to this file via
 * `import.meta.url` so the lookup works whether ghagen is installed
 * from npm or run from source.
 */
const GHAGEN_VERSION: string = (() => {
  try {
    const url = new URL("../../package.json", import.meta.url);
    const text = readFileSync(url, "utf8");
    const pkg = JSON.parse(text) as { version?: string };
    return pkg.version ?? "unknown";
  } catch {
    return "unknown";
  }
})();

/** Variables substituted into a header template. */
export interface HeaderVariables {
  source_file: string;
  source_line: string;
  tool: string;
  version: string;
}

/**
 * Build the substitution dict for one item's header.
 *
 * Resolves `{source_file}` relative to the app root discovered by
 * walking upward from the source file looking for
 * `.ghagen.yml`. Falls back to the absolute path when no
 * marker is found. Falls back to `<unknown>` when `sourceLocation` is
 * `null`.
 */
export function buildHeaderVariables(sourceLocation: SourceLocation | null): HeaderVariables {
  let sourceFile: string;
  let sourceLine: string;
  if (sourceLocation === null) {
    sourceFile = "<unknown>";
    sourceLine = "0";
  } else {
    const absPath = isAbsolute(sourceLocation.file)
      ? sourceLocation.file
      : resolve(sourceLocation.file);
    const root = findAppRoot(dirname(absPath));
    if (root !== null) {
      const rel = relative(root, absPath);
      sourceFile = rel === "" || rel.startsWith("..") ? absPath : rel;
    } else {
      sourceFile = absPath;
    }
    sourceLine = String(sourceLocation.line);
  }
  return {
    source_file: sourceFile,
    source_line: sourceLine,
    tool: "ghagen",
    version: GHAGEN_VERSION,
  };
}

/**
 * Resolve a header value into the string that should be emitted (or `null`
 * to skip the header).
 *
 * Branching:
 *
 * - `null`      → return `null`; the caller skips emitting any header.
 * - `undefined` → render `DEFAULT_HEADER` with the captured source-file
 *   variables. This is the only place `{variable}` substitution happens.
 * - `string`    → return the string as-is. No placeholder substitution
 *   on user-supplied strings — literal `{` survives unchanged.
 * - function    → invoke with a fully-populated `HeaderVariables` and
 *   return its result.
 *
 * Returns the comment text without `#` prefixes — the yaml library handles
 * comment formatting automatically.
 */
export function formatHeader(
  header: string | null | ((vars: HeaderVariables) => string) | undefined,
  sourceLocation?: SourceLocation | null,
): string | null {
  if (header === null) {
    return null;
  }
  if (typeof header === "string") {
    return header;
  }
  const variables = buildHeaderVariables(sourceLocation ?? null);
  if (header === undefined) {
    return DEFAULT_HEADER.replace(/\{(\w+)\}/g, (_, key: string) => {
      const value = variables[key as keyof HeaderVariables];
      if (value === undefined) {
        throw new Error(`Internal error: DEFAULT_HEADER references unknown variable {${key}}.`);
      }
      return value;
    });
  }
  return header(variables);
}
