import { describe, it, expect } from "vitest";
import { mkdirSync, mkdtempSync, readFileSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import type { HeaderVariables } from "./header.js";
import { buildHeaderVariables, DEFAULT_HEADER, formatHeader, HEADER_VARIABLES } from "./header.js";
import { EXPECTED_DIR } from "../paths.js";

describe("formatHeader()", () => {
  it("renders the default template when header is undefined", () => {
    // Default header references {source_file} — passing null location
    // makes it render as <unknown>.
    const result = formatHeader(undefined);
    expect(result).toBe(
      "# This file is generated by ghagen from <unknown>.\n# Do not edit manually.\n",
    );
  });

  it("wraps user strings as a comment block", () => {
    expect(formatHeader("Custom header text")).toBe("# Custom header text\n");
  });

  it("does not substitute {variable} placeholders in user strings", () => {
    // The string is emitted verbatim; literal braces survive.
    expect(formatHeader("Built with {tool} v{version}")).toBe("# Built with {tool} v{version}\n");
  });

  it("returns null when header is null", () => {
    expect(formatHeader(null)).toBeNull();
  });

  it("invokes a closure with HeaderVariables and returns its result", () => {
    const result = formatHeader((v: HeaderVariables) => `built by ${v.tool} v${v.version}`);
    expect(result).toMatch(/^# built by ghagen v\d+\.\d+\.\d+\n$/);
  });

  it("passes resolved source_file/source_line to the closure", () => {
    const result = formatHeader((v: HeaderVariables) => `from ${v.source_file}:${v.source_line}`, {
      file: "/repo/.github/workflows.ts",
      line: 42,
    });
    expect(result).toContain(":42");
    expect(result).toContain("workflows.ts");
    expect(result?.startsWith("# ")).toBe(true);
    expect(result?.endsWith("\n")).toBe(true);
  });
});

// ---------------------------------------------------------------------------
// The header shape contract — the peer of
// `packages/python/tests/test_emitter/test_header.py`. `null` is the *only*
// skip signal; every other input yields a `#`-prefixed block ending in exactly
// one "\n".
// ---------------------------------------------------------------------------
describe("formatHeader() shape contract", () => {
  it('renders "" as a bare "#" line rather than skipping the header', () => {
    expect(formatHeader("")).toBe("#\n");
  });

  it("renders a blank interior line as a bare #", () => {
    expect(formatHeader("line1\n\nline3")).toBe("# line1\n#\n# line3\n");
  });

  it("drops exactly one trailing line break", () => {
    expect(formatHeader("x\n")).toBe("# x\n");
    expect(formatHeader("x\n\n")).toBe("# x\n#\n");
    expect(formatHeader("\r\n")).toBe("#\n");
  });

  it("treats CRLF as one break and lets no CR through", () => {
    expect(formatHeader("a\r\nb")).toBe("# a\n# b\n");
  });

  it("treats a bare CR as a break", () => {
    expect(formatHeader("a\rb\rc")).toBe("# a\n# b\n# c\n");
  });

  it("treats the non-LF Unicode breaks as breaks", () => {
    // ruamel rejects VT/FF/FS/GS/RS inside a comment outright and rescans
    // NEL/U+2028/U+2029 as line breaks, so none of them may survive.
    expect(formatHeader("a\vb")).toBe("# a\n# b\n");
    expect(formatHeader("a\fb")).toBe("# a\n# b\n");
    expect(formatHeader("a\x1cb")).toBe("# a\n# b\n");
    expect(formatHeader("a\x1db")).toBe("# a\n# b\n");
    expect(formatHeader("a\x1eb")).toBe("# a\n# b\n");
    expect(formatHeader("a\x85b")).toBe("# a\n# b\n");
    expect(formatHeader("a\u2028b")).toBe("# a\n# b\n");
    expect(formatHeader("a\u2029b")).toBe("# a\n# b\n");
  });

  it("does not collapse a leading break", () => {
    expect(formatHeader("\nx")).toBe("#\n# x\n");
  });

  it("prefixes an already-hashed line rather than passing it through", () => {
    expect(formatHeader("# already hashed")).toBe("# # already hashed\n");
  });

  it("preserves interior whitespace", () => {
    expect(formatHeader("   ")).toBe("#    \n");
  });
});

describe("buildHeaderVariables()", () => {
  it("falls back to <unknown>/0 when location is null", () => {
    const vars = buildHeaderVariables(null);
    expect(vars.source_file).toBe("<unknown>");
    expect(vars.source_line).toBe("0");
    expect(vars.tool).toBe("ghagen");
    expect(vars.version).toMatch(/^\d+\.\d+\.\d+$/);
  });

  it("does not resolve source_file through a symlink", () => {
    // Regression for docs/issues/23 item 6: Python's Path.resolve() follows
    // symlinks for existing path components; this port's resolve() from
    // node:path never touches the filesystem. Puts a real (marker-bearing)
    // project root behind a directory symlink whose own lexical ancestor
    // has a *different* marker-bearing root, so the two root-discovery
    // strategies would disagree if either resolved the link: resolving
    // would walk from tmp/project/sub and find no marker; not resolving
    // walks from tmp/other/link and finds tmp/other/.ghagen.yml.
    //
    // fixtures/expected/header_source_file_symlink.txt is the shared byte
    // oracle: the Python peer builds the identical directory layout and
    // asserts the same string.
    const tmp = mkdtempSync(join(tmpdir(), "ghagen-header-symlink-"));
    try {
      // The symlink's target -- nobody should ever be resolved into this tree.
      const realProject = join(tmp, "project", "sub");
      mkdirSync(realProject, { recursive: true });

      // The symlink's own lexical ancestor -- the root the lexical walk finds.
      const linkParent = join(tmp, "other");
      mkdirSync(linkParent);
      writeFileSync(join(linkParent, ".ghagen.yml"), "");
      symlinkSync(realProject, join(linkParent, "link"), "dir");

      const src = join(linkParent, "link", "workflows.py"); // never created -- lexical only

      const vars = buildHeaderVariables({ file: src, line: 1 });

      const expected = readFileSync(
        join(EXPECTED_DIR, "header_source_file_symlink.txt"),
        "utf8",
      ).trim();
      expect(vars.source_file).toBe(expected);
    } finally {
      rmSync(tmp, { recursive: true, force: true });
    }
  });
});

describe("DEFAULT_HEADER", () => {
  it("references the source file placeholder", () => {
    expect(DEFAULT_HEADER).toContain("{source_file}");
  });
});

describe("HEADER_VARIABLES", () => {
  it("documents every variable used by the default template", () => {
    expect(HEADER_VARIABLES).toHaveProperty("source_file");
    expect(HEADER_VARIABLES).toHaveProperty("source_line");
    expect(HEADER_VARIABLES).toHaveProperty("tool");
    expect(HEADER_VARIABLES).toHaveProperty("version");
  });
});
