import { describe, it, expect } from "vitest";
import { formatHeader, DEFAULT_HEADER } from "./header.js";

describe("formatHeader()", () => {
  it("returns the default header when called with no arguments", () => {
    expect(formatHeader()).toBe("Auto-generated by ghagen. Do not edit.");
  });

  it("uses a custom template as-is when it has no placeholders", () => {
    expect(formatHeader("Custom header text")).toBe("Custom header text");
  });

  it("substitutes {tool} and {version} placeholders", () => {
    const result = formatHeader("Built with {tool} v{version}");
    expect(result).toBe("Built with ghagen v0.0.1");
  });

  it("falls back to default when null is passed", () => {
    expect(formatHeader(null)).toBe(DEFAULT_HEADER);
  });

  it("preserves unknown placeholders unchanged", () => {
    expect(formatHeader("Hello {unknown}")).toBe("Hello {unknown}");
  });
});
