/** Default header template. */
export const DEFAULT_HEADER =
  "Auto-generated by ghagen. Do not edit.";

/** Available variables for header templates. */
export interface HeaderVariables {
  tool: string;
  version: string;
}

const HEADER_VARIABLES: HeaderVariables = {
  tool: "ghagen",
  version: "0.0.1", // TODO: read from package.json
};

/**
 * Format a header template string, replacing `{variable}` placeholders.
 * Returns the formatted string without `#` prefixes — the yaml library
 * handles comment formatting automatically.
 */
export function formatHeader(template?: string | null): string {
  const tmpl = template ?? DEFAULT_HEADER;
  return tmpl.replace(/\{(\w+)\}/g, (_, key) => {
    const value = HEADER_VARIABLES[key as keyof HeaderVariables];
    return value ?? `{${key}}`;
  });
}
