import { Document, Scalar, YAMLMap, YAMLSeq } from "yaml";
import type { Document as GhagenDocument } from "../models/_base.js";
import { formatHeader, type HeaderVariables } from "./header.js";
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname } from "node:path";

/** Options for controlling YAML serialization output. */
export interface ToYamlOptions {
  /**
   * Header comment for the generated file.
   *
   * - omit / `undefined` — emit ghagen's default header.
   * - `null`             — emit no header.
   * - `string`           — emit the string verbatim. No `{variable}`
   *   substitution; literal braces are preserved.
   * - `(vars) => string` — invoke the closure with a fully-populated
   *   {@link HeaderVariables} and emit the returned string.
   */
  header?: string | null | ((vars: HeaderVariables) => string);
}

/** Format a YAML comment by prefixing each line with `#`. */
function formatYamlComment(comment: string): string {
  return comment
    .split("\n")
    .map((line) => (line ? `# ${line}` : "#"))
    .join("\n");
}

/** Prepend a block comment before the first key in the map. */
function attachBlockComment(map: YAMLMap, comment: string): void {
  const firstPair = map.items[0];
  if (!firstPair) {
    return;
  }
  const key = firstPair.key instanceof Scalar ? firstPair.key : new Scalar(firstPair.key);
  const existing = key.commentBefore;
  key.commentBefore = existing ? `${comment}\n${existing}` : comment;
  firstPair.key = key;
}

/** Attach an end-of-line comment to the last value in the map. */
function attachEolComment(map: YAMLMap, comment: string): void {
  const lastPair = map.items[map.items.length - 1];
  if (!lastPair) {
    return;
  }
  if (
    lastPair.value instanceof Scalar ||
    lastPair.value instanceof YAMLMap ||
    lastPair.value instanceof YAMLSeq
  ) {
    lastPair.value.comment = comment;
  } else {
    const val = new Scalar(lastPair.value);
    val.comment = comment;
    lastPair.value = val;
  }
}

/**
 * Widen the gap before inline `#` comments from 1 space to 2 to match
 * ruamel.yaml's convention. The lookbehind condition (non-whitespace,
 * non-colon) leaves block comments (indented `#`) and key-only comments
 * (`key: #`) alone.
 */
function fixInlineCommentSpacing(yaml: string): string {
  return yaml.replace(/([^\s:]) (# )/g, "$1  $2");
}

/**
 * Serialize a workflow or action model to a YAML string.
 *
 * Keys are emitted in canonical order, comments are attached, and multiline
 * strings use block-literal style. A header comment identifying the
 * generating tool is prepended by default.
 *
 * @param model   - The model to serialize (e.g. from {@link workflow} or {@link action}).
 * @param options - Optional settings for header customization.
 * @returns The rendered YAML string, including a trailing newline.
 *
 * @example
 * ```ts
 * const yaml = toYaml(myWorkflow);
 * console.log(yaml);
 * ```
 */
export function toYaml(model: GhagenDocument, options?: ToYamlOptions): string {
  const doc = new Document();
  doc.contents = model.toYamlMap();

  const headerStr = formatHeader(options?.header, model.sourceLocation);
  if (headerStr !== null) {
    doc.commentBefore = headerStr;
  }

  if (doc.contents instanceof YAMLMap) {
    if (model.meta.comment) {
      attachBlockComment(doc.contents, model.meta.comment);
    }
    if (model.meta.eolComment) {
      attachEolComment(doc.contents, model.meta.eolComment);
    }
  }

  const yaml = doc.toString({
    lineWidth: 0,
    indentSeq: false,
    singleQuote: true,
    commentString: formatYamlComment,
  });

  return fixInlineCommentSpacing(yaml);
}

/**
 * Serialize a model to a YAML file.
 *
 * Creates any intermediate directories that do not yet exist and writes the
 * YAML output synchronously. This is a convenience wrapper around
 * {@link toYaml} for the common "write to disk" use case.
 *
 * @param model   - The model to serialize.
 * @param path    - Destination file path (absolute or relative to cwd).
 * @param options - Optional settings forwarded to {@link toYaml}.
 *
 * @example
 * ```ts
 * toYamlFile(myWorkflow, ".github/workflows/ci.yml");
 *
 * // With a custom header — strings are emitted verbatim:
 * toYamlFile(myAction, "action.yml", { header: "Hand-written header" });
 *
 * // For interpolation, pass a closure:
 * toYamlFile(myAction, "action.yml", {
 *   header: (v) => `Generated by ${v.tool} v${v.version}`,
 * });
 * ```
 */
export function toYamlFile(model: GhagenDocument, path: string, options?: ToYamlOptions): void {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, toYaml(model, options));
}
