import { Document, Scalar, YAMLMap, YAMLSeq, Pair } from "yaml";
import type { Model } from "../models/_base.js";
import { formatHeader } from "./header.js";
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname } from "node:path";

/** Options for controlling YAML serialization output. */
export interface ToYamlOptions {
  /** Custom header comment template. Supports `{tool}` and `{version}` placeholders. */
  header?: string | null;
  /** Whether to include the header comment. Defaults to true. */
  includeHeader?: boolean;
}

/**
 * Serialize a workflow or action model to a YAML string.
 *
 * Keys are emitted in canonical order, comments are attached, and multiline
 * strings use block-literal style. A header comment identifying the
 * generating tool is prepended by default.
 *
 * @param model   - The model to serialize (e.g. from {@link workflow} or {@link action}).
 * @param options - Optional settings for header customization.
 * @returns The rendered YAML string, including a trailing newline.
 *
 * @example
 * ```ts
 * const yaml = toYaml(myWorkflow);
 * console.log(yaml);
 *
 * // Suppress the auto-generated header comment:
 * const bare = toYaml(myWorkflow, { includeHeader: false });
 * ```
 */
export function toYaml(model: Model, options?: ToYamlOptions): string {
  const doc = new Document();
  doc.contents = model.toYamlMap();

  if (options?.includeHeader !== false) {
    doc.commentBefore = formatHeader(options?.header, model.sourceLocation);
  }

  // Attach top-level block comment if set (prepend before any existing field comment)
  if (model.meta.comment && doc.contents instanceof YAMLMap) {
    const firstPair = doc.contents.items[0];
    if (firstPair) {
      const key = firstPair.key instanceof Scalar ? firstPair.key : new Scalar(firstPair.key);
      const existing = key.commentBefore;
      key.commentBefore = existing ? `${model.meta.comment}\n${existing}` : model.meta.comment;
      firstPair.key = key;
    }
  }

  // Attach top-level EOL comment to the last value
  if (model.meta.eolComment && doc.contents instanceof YAMLMap) {
    const items = doc.contents.items;
    const lastPair = items[items.length - 1] as Pair | undefined;
    if (lastPair) {
      if (
        lastPair.value instanceof Scalar ||
        lastPair.value instanceof YAMLMap ||
        lastPair.value instanceof YAMLSeq
      ) {
        (lastPair.value as Scalar | YAMLMap | YAMLSeq).comment = model.meta.eolComment;
      } else {
        const val = new Scalar(lastPair.value);
        val.comment = model.meta.eolComment;
        lastPair.value = val;
      }
    }
  }

  let result = doc.toString({
    lineWidth: 0,
    indentSeq: false,
    singleQuote: true,
    commentString: (comment: string) =>
      comment
        .split("\n")
        .map((line) => (line ? `# ${line}` : "#"))
        .join("\n"),
  });

  // Add extra space before inline comments to match ruamel.yaml convention
  // (yaml library uses 1 space before #, ruamel.yaml uses 2).
  // Only match when preceded by a non-whitespace, non-colon character
  // to avoid affecting block comments (indented #) and key comments (on: #).
  result = result.replace(/([^\s:]) (# )/g, "$1  $2");

  return result;
}

/**
 * Serialize a model to a YAML file.
 *
 * Creates any intermediate directories that do not yet exist and writes the
 * YAML output synchronously. This is a convenience wrapper around
 * {@link toYaml} for the common "write to disk" use case.
 *
 * @param model   - The model to serialize.
 * @param path    - Destination file path (absolute or relative to cwd).
 * @param options - Optional settings forwarded to {@link toYaml}.
 *
 * @example
 * ```ts
 * toYamlFile(myWorkflow, ".github/workflows/ci.yml");
 *
 * // With a custom header:
 * toYamlFile(myAction, "action.yml", {
 *   header: "Generated by {tool} v{version}",
 * });
 * ```
 */
export function toYamlFile(model: Model, path: string, options?: ToYamlOptions): void {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, toYaml(model, options));
}
