import { describe, it, expect } from "vitest";
import { mkdtempSync, readFileSync, rmSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import YAML, { YAMLMap, Scalar, Pair } from "yaml";
import { toYaml, toYamlFile, toData } from "./yaml-writer.js";
import { EOL_GUTTER } from "./comment-geometry.js";
import type { HeaderVariables } from "./header.js";
import { Model, raw, withComment, withEolComment } from "../models/_base.js";
import type { ModelMeta, ModelSpec } from "../models/_base.js";
import { JOB_SPEC, job } from "../models/job.js";
import { workflow } from "../models/workflow.js";
import { step } from "../models/step.js";

// ---------------------------------------------------------------------------
// helpers
// ---------------------------------------------------------------------------

/** Build a bare Model with an ad-hoc spec for testing serialization in isolation. */
function simpleModel(
  data: Record<string, unknown> = {},
  meta: Record<string, unknown> = {},
  order: readonly string[] = [],
) {
  const spec = {
    kind: "step",
    fieldMap: {},
    order: { kind: "explicit", keys: order },
  } as unknown as ModelSpec;
  return new Model(spec, data, meta as ModelMeta);
}

// ---------------------------------------------------------------------------
// toYaml basics
// ---------------------------------------------------------------------------
describe("toYaml()", () => {
  // These five assert whole emitted bytes, not substrings: the header sits
  // flush against the body, so a blank line, a spurious trailing `#` or a
  // stray CR would all be invisible to a `toContain`.
  it("produces YAML with default header comment", () => {
    const m = simpleModel({ name: "ci" });
    const yaml = toYaml(m);
    // Whole output, modulo the {source_file} path this test file resolves to.
    expect(yaml).toMatch(
      /^# This file is generated by ghagen from .+\.\n# Do not edit manually\.\nname: ci\n$/,
    );
  });

  it("omits header when header is null", () => {
    const m = simpleModel({ name: "ci" });
    const yaml = toYaml(m, { header: null });
    expect(yaml).toBe("name: ci\n");
  });

  it("uses a custom header string", () => {
    const m = simpleModel({ name: "ci" });
    const yaml = toYaml(m, { header: "Custom header" });
    expect(yaml).toBe("# Custom header\nname: ci\n");
  });

  it("emits string header literally without {variable} substitution", () => {
    const m = simpleModel({ name: "ci" });
    const yaml = toYaml(m, { header: "literal {tool} stays literal" });
    expect(yaml).toBe("# literal {tool} stays literal\nname: ci\n");
  });

  it("renders a closure header with ghagen-supplied variables", () => {
    const m = simpleModel({ name: "ci" });
    const yaml = toYaml(m, { header: (v) => `built by ${v.tool}` });
    expect(yaml).toBe("# built by ghagen\nname: ci\n");
  });

  it('renders header: "" as a bare # with no separator', () => {
    const m = simpleModel({ name: "ci" });
    expect(toYaml(m, { header: "" })).toBe("#\nname: ci\n");
  });

  it("passes a fully-populated HeaderVariables to the closure", () => {
    const m = simpleModel({ name: "ci" });
    const captured: HeaderVariables[] = [];
    toYaml(m, {
      header: (v) => {
        captured.push(v);
        return "ok";
      },
    });
    expect(captured).toHaveLength(1);
    const vars = captured[0]!;
    expect(Object.keys(vars).sort()).toEqual(["source_file", "source_line", "tool", "version"]);
    expect(vars.tool).toBe("ghagen");
    expect(vars.version).toMatch(/^\d+\.\d+\.\d+$/);
    expect(typeof vars.source_file).toBe("string");
    expect(typeof vars.source_line).toBe("string");
  });
});

// ---------------------------------------------------------------------------
// key ordering (observed via the public toData surface)
// ---------------------------------------------------------------------------
describe("key ordering", () => {
  it("orders keys according to keyOrder, then remaining in insertion order", () => {
    const m = new Model(
      JOB_SPEC,
      { steps: [], name: "build", "runs-on": "ubuntu-latest", env: {} },
      {},
    );
    const keys = Object.keys(toData(m) as Record<string, unknown>);
    // JOB_KEY_ORDER puts name, runs-on, ... env, ... steps
    expect(keys.indexOf("name")).toBeLessThan(keys.indexOf("runs-on"));
    expect(keys.indexOf("runs-on")).toBeLessThan(keys.indexOf("steps"));
  });

  it("merges extras after schema fields", () => {
    const m = simpleModel({ name: "ci" }, { extras: { "x-custom": true } }, ["name"]);
    const keys = Object.keys(toData(m) as Record<string, unknown>);
    expect(keys).toEqual(["name", "x-custom"]);
  });
});

// ---------------------------------------------------------------------------
// Comments
// ---------------------------------------------------------------------------
describe("comments", () => {
  it("withComment adds a block comment before the field", () => {
    const m = simpleModel({ name: withComment("ci", "The workflow name") });
    const yaml = toYaml(m, { header: null });
    const lines = yaml.split("\n");
    const commentIdx = lines.findIndex((l) => l.includes("# The workflow name"));
    const fieldIdx = lines.findIndex((l) => l.startsWith("name:"));
    expect(commentIdx).toBeGreaterThanOrEqual(0);
    expect(commentIdx).toBeLessThan(fieldIdx);
  });

  it("withEolComment adds an EOL comment on the field value", () => {
    const m = simpleModel({ name: withEolComment("ci", "inline note") });
    const yaml = toYaml(m, { header: null });
    expect(yaml).toContain(`name: ci${" ".repeat(EOL_GUTTER)}# inline note`);
  });

  it("model-level comment attaches to the first key", () => {
    const m = simpleModel({ name: "ci", on: "push" }, { comment: "Top comment" });
    const yaml = toYaml(m, { header: null });
    const lines = yaml.split("\n");
    const commentIdx = lines.findIndex((l) => l.includes("# Top comment"));
    const nameIdx = lines.findIndex((l) => l.startsWith("name:"));
    expect(commentIdx).toBeGreaterThanOrEqual(0);
    expect(commentIdx).toBeLessThan(nameIdx);
  });

  it("model-level eolComment attaches to the last value", () => {
    const m = simpleModel({ alpha: 1, zulu: 2 }, { eolComment: "end of block" });
    const yaml = toYaml(m, { header: null });
    expect(yaml).toContain(`zulu: 2${" ".repeat(EOL_GUTTER)}# end of block`);
  });

  it("a `#` in a comment payload is not a comment delimiter", () => {
    const m = simpleModel({ name: withComment("ci", "see issue # 42 for details") });
    const yaml = toYaml(m, { header: null });
    expect(yaml).toContain("# see issue # 42 for details\n");
  });

  it("the EOL gutter does not depend on a neighbouring key's comment", () => {
    // Cross-port parity: `test_comments.py` asserts the same four strings.
    // The gutter is EOL_GUTTER whichever side of the key the comment sits on
    // and whether or not a neighbour carries one. On `main` TypeScript emitted
    // one column for a collection value (the regex refused to widen after a
    // `:`) and Python emitted one column whenever a neighbour was commented.
    const scalar = simpleModel({ name: "ci", on: withEolComment("push", "trigger") }, {}, [
      "name",
      "on",
    ]);
    expect(toYaml(scalar, { header: null })).toContain("on: push  # trigger\n");

    const scalarWithNeighbour = simpleModel(
      { name: withComment("ci", "the name"), on: withEolComment("push", "trigger") },
      {},
      ["name", "on"],
    );
    expect(toYaml(scalarWithNeighbour, { header: null })).toContain("on: push  # trigger\n");

    const collection = simpleModel(
      { name: "ci", on: withEolComment({ push: {} }, "trigger") },
      {},
      ["name", "on"],
    );
    expect(toYaml(collection, { header: null })).toContain("on:  # trigger\n");

    const collectionWithNeighbour = simpleModel(
      { name: withComment("ci", "the name"), on: withEolComment({ push: {} }, "trigger") },
      {},
      ["name", "on"],
    );
    expect(toYaml(collectionWithNeighbour, { header: null })).toContain("on:  # trigger\n");
  });

  it("a multi-line EOL comment degrades to a block comment above the field", () => {
    // Cross-port parity: `test_comments.py` asserts the same string, and the
    // Python port emitted unparseable YAML for this input before the fix.
    const m = simpleModel({ name: withEolComment("ci", "line one\nline two") });
    const yaml = toYaml(m, { header: null });
    expect(yaml).toBe("# line one\n# line two\nname: ci\n");
    expect(YAML.parse(yaml)).toEqual({ name: "ci" });
  });
});

// ---------------------------------------------------------------------------
// Scalar content is never rewritten — the emitted document is not inspected
// for `#`, so a `#` in a `run:` script survives a full emit → parse round trip.
// ---------------------------------------------------------------------------
describe("scalar round-trip", () => {
  const RUN_SHAPES = [
    "echo hi # note",
    "npm ci # install deps\nnpm test\n",
    "echo 'a # b'",
    "curl https://x/y#frag # note",
    "echo hi #note",
    "echo hi  # note",
    "echo hi: # note",
    "# note\necho hi",
    "#!/usr/bin/env bash\necho hi",
    "echo hi\t# note",
    "sed -i 's/# a/# b/' f",
  ];

  it.each(RUN_SHAPES)("a step's `run` survives emit → parse: %j", (run) => {
    const w = workflow({
      name: "x",
      on: { push: {} },
      jobs: { j: job({ runsOn: "u", steps: [step({ run })] }) },
    });
    // A round trip, not a substring match: the corrupted output was still
    // valid YAML, so only comparing against the input catches the injection.
    const parsed = YAML.parse(toYaml(w, { header: null })) as {
      jobs: { j: { steps: { run: string }[] } };
    };
    expect(parsed.jobs.j.steps[0]!.run).toBe(run);
  });

  it("an env value keeps its `#`", () => {
    const m = simpleModel({ env: { COLOR: "red # crimson" } });
    const yaml = toYaml(m, { header: null });
    expect((YAML.parse(yaml) as { env: { COLOR: string } }).env.COLOR).toBe("red # crimson");
  });
});

// ---------------------------------------------------------------------------
// Headers — all three documented forms survive a `#` in the payload.
// ---------------------------------------------------------------------------
describe("header payloads containing `#`", () => {
  it("a string header is emitted verbatim", () => {
    const m = simpleModel({ name: "ci" });
    expect(toYaml(m, { header: "build # 7 of pipeline" })).toContain("# build # 7 of pipeline\n");
  });

  it("a closure header is emitted verbatim", () => {
    const m = simpleModel({ name: "ci" });
    expect(toYaml(m, { header: (v) => `build # 7 by ${v.tool}` })).toContain(
      "# build # 7 by ghagen\n",
    );
  });

  it("the default header is unchanged", () => {
    const m = simpleModel({ name: "ci" });
    expect(toYaml(m)).toContain("# This file is generated by ghagen");
  });
});

// ---------------------------------------------------------------------------
// Comment geometry — a model's own EOL comment when the target value is a
// collection. Cross-port parity: every string asserted here is asserted
// byte-identically by `tests/test_emitter/test_comments.py`.
// ---------------------------------------------------------------------------
describe("model EOL comment on a collection value", () => {
  it("renders a job's own eolComment on the `steps:` key line", () => {
    const w = workflow({
      name: "x",
      on: { push: {} },
      jobs: { j: job({ runsOn: "u", eolComment: "job note", steps: [step({ run: "x" })] }) },
    });
    expect(toYaml(w, { header: null })).toContain("    steps:  # job note\n    - run: x\n");
  });

  it("renders a seq-item model's own eolComment on the `- with:` line", () => {
    const w = workflow({
      name: "x",
      on: { push: {} },
      jobs: { j: job({ runsOn: "u", steps: [step({ with_: { a: "1" }, eolComment: "note" })] }) },
    });
    expect(toYaml(w, { header: null })).toContain("    - with:  # note\n        a: '1'\n");
  });
});

// ---------------------------------------------------------------------------
// postProcess
// ---------------------------------------------------------------------------
describe("postProcess", () => {
  it("callback can add pairs to the YAMLMap", () => {
    const m = simpleModel(
      { name: "ci" },
      {
        postProcess: (node: YAMLMap) => {
          node.items.push(new Pair(new Scalar("injected"), new Scalar("yes")));
        },
      },
    );
    const yaml = toYaml(m, { header: null });
    expect(yaml).toContain("injected: yes");
  });
});

// ---------------------------------------------------------------------------
// Value conversion
// ---------------------------------------------------------------------------
describe("value conversion", () => {
  it("multiline string ending with newline uses block literal |", () => {
    const m = simpleModel({ script: "echo hello\necho world\n" });
    const yaml = toYaml(m, { header: null });
    expect(yaml).toContain("script: |\n");
  });

  it("multiline string without trailing newline uses strip |-", () => {
    const m = simpleModel({ script: "echo hello\necho world" });
    const yaml = toYaml(m, { header: null });
    expect(yaml).toContain("script: |-\n");
  });

  it("single-line string is plain (no block indicator)", () => {
    const m = simpleModel({ name: "ci" });
    const yaml = toYaml(m, { header: null });
    expect(yaml).toContain("name: ci");
    expect(yaml).not.toMatch(/name: [|>]/);
  });

  it("raw() values are unwrapped as plain scalars", () => {
    const m = simpleModel({ expr: raw("${{ github.event }}") });
    const yaml = toYaml(m, { header: null });
    expect(yaml).toContain("expr: ${{ github.event }}");
  });

  it("nested model produces a recursive YAMLMap", () => {
    const inner = simpleModel({ image: "node:20" }, {}, ["image"]);
    const outer = simpleModel({ container: inner }, {}, ["container"]);
    const yaml = toYaml(outer, { header: null });
    expect(yaml).toContain("container:");
    expect(yaml).toContain("  image: node:20");
  });

  it("array produces a YAML sequence", () => {
    const m = simpleModel({ items: ["a", "b", "c"] });
    const yaml = toYaml(m, { header: null });
    expect(yaml).toContain("- a");
    expect(yaml).toContain("- b");
    expect(yaml).toContain("- c");
  });

  it("plain object produces a nested map", () => {
    const m = simpleModel({ env: { NODE_ENV: "production" } });
    const yaml = toYaml(m, { header: null });
    expect(yaml).toContain("env:");
    expect(yaml).toContain("  NODE_ENV: production");
  });

  it("null value is serialized as a null entry", () => {
    const m = simpleModel({ empty: null });
    const yaml = toYaml(m, { header: null });
    expect(yaml).toContain("? empty");
  });

  it("undefined value is serialized as a null entry", () => {
    const m = simpleModel({ empty: undefined });
    const yaml = toYaml(m, { header: null });
    expect(yaml).toContain("? empty");
  });
});

// ---------------------------------------------------------------------------
// toYamlFile
// ---------------------------------------------------------------------------
describe("toYamlFile()", () => {
  it("writes YAML to disk matching toYaml() output", () => {
    const dir = mkdtempSync(join(tmpdir(), "ghagen-test-"));
    try {
      const m = simpleModel({ name: "ci" });
      const filePath = join(dir, "workflow.yml");
      toYamlFile(m, filePath);
      const contents = readFileSync(filePath, "utf-8");
      expect(contents).toBe(toYaml(m));
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });
});
