import { describe, it, expect } from "vitest";
import { mkdtempSync, readFileSync, rmSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { YAMLMap, Scalar, Pair } from "yaml";
import { toYaml, toYamlFile } from "./yaml-writer.js";
import type { HeaderVariables } from "./header.js";
import { Model, raw, withComment, withEolComment } from "../models/_base.js";
import type { ModelMeta, ModelSpec } from "../models/_base.js";
import { JOB_SPEC } from "../models/job.js";

// ---------------------------------------------------------------------------
// helpers
// ---------------------------------------------------------------------------

/** Build a bare Model with an ad-hoc spec for testing serialization in isolation. */
function simpleModel(
  data: Record<string, unknown> = {},
  meta: Record<string, unknown> = {},
  order: readonly string[] = [],
) {
  const spec = { kind: "step", fieldMap: {}, order } as unknown as ModelSpec;
  return new Model(spec, data, meta as ModelMeta);
}

// ---------------------------------------------------------------------------
// toYaml basics
// ---------------------------------------------------------------------------
describe("toYaml()", () => {
  it("produces YAML with default header comment", () => {
    const m = simpleModel({ name: "ci" });
    const yaml = toYaml(m);
    expect(yaml).toContain("# This file is generated by ghagen");
    expect(yaml).toContain("# Do not edit manually.");
  });

  it("omits header when header is null", () => {
    const m = simpleModel({ name: "ci" });
    const yaml = toYaml(m, { header: null });
    expect(yaml).not.toContain("This file is generated by ghagen");
  });

  it("uses a custom header string", () => {
    const m = simpleModel({ name: "ci" });
    const yaml = toYaml(m, { header: "Custom header" });
    expect(yaml).toContain("# Custom header");
    expect(yaml).not.toContain("Do not edit manually");
  });

  it("emits string header literally without {variable} substitution", () => {
    const m = simpleModel({ name: "ci" });
    const yaml = toYaml(m, { header: "literal {tool} stays literal" });
    expect(yaml).toContain("# literal {tool} stays literal");
  });

  it("renders a closure header with ghagen-supplied variables", () => {
    const m = simpleModel({ name: "ci" });
    const yaml = toYaml(m, { header: (v) => `built by ${v.tool}` });
    expect(yaml).toContain("# built by ghagen");
  });

  it("passes a fully-populated HeaderVariables to the closure", () => {
    const m = simpleModel({ name: "ci" });
    const captured: HeaderVariables[] = [];
    toYaml(m, {
      header: (v) => {
        captured.push(v);
        return "ok";
      },
    });
    expect(captured).toHaveLength(1);
    const vars = captured[0]!;
    expect(Object.keys(vars).sort()).toEqual(["source_file", "source_line", "tool", "version"]);
    expect(vars.tool).toBe("ghagen");
    expect(vars.version).toMatch(/^\d+\.\d+\.\d+$/);
    expect(typeof vars.source_file).toBe("string");
    expect(typeof vars.source_line).toBe("string");
  });
});

// ---------------------------------------------------------------------------
// toYamlMap() key ordering
// ---------------------------------------------------------------------------
describe("toYamlMap() key ordering", () => {
  it("orders keys according to keyOrder, then remaining in insertion order", () => {
    const m = new Model(
      JOB_SPEC,
      { steps: [], name: "build", "runs-on": "ubuntu-latest", env: {} },
      {},
    );
    const map = m.toYamlMap();
    const keys = map.items.map((p: Pair) => (p.key instanceof Scalar ? p.key.value : p.key));
    // JOB_KEY_ORDER puts name, runs-on, ... env, ... steps
    expect(keys.indexOf("name")).toBeLessThan(keys.indexOf("runs-on"));
    expect(keys.indexOf("runs-on")).toBeLessThan(keys.indexOf("steps"));
  });

  it("merges extras after schema fields", () => {
    const m = simpleModel({ name: "ci" }, { extras: { "x-custom": true } }, ["name"]);
    const map = m.toYamlMap();
    const keys = map.items.map((p: Pair) => (p.key instanceof Scalar ? p.key.value : p.key));
    expect(keys).toEqual(["name", "x-custom"]);
  });
});

// ---------------------------------------------------------------------------
// Comments
// ---------------------------------------------------------------------------
describe("comments", () => {
  it("withComment adds a block comment before the field", () => {
    const m = simpleModel({ name: withComment("ci", "The workflow name") });
    const yaml = toYaml(m, { header: null });
    const lines = yaml.split("\n");
    const commentIdx = lines.findIndex((l) => l.includes("# The workflow name"));
    const fieldIdx = lines.findIndex((l) => l.startsWith("name:"));
    expect(commentIdx).toBeGreaterThanOrEqual(0);
    expect(commentIdx).toBeLessThan(fieldIdx);
  });

  it("withEolComment adds an EOL comment on the field value", () => {
    const m = simpleModel({ name: withEolComment("ci", "inline note") });
    const yaml = toYaml(m, { header: null });
    expect(yaml).toMatch(/name: ci\s+# inline note/);
  });

  it("model-level comment attaches to the first key", () => {
    const m = simpleModel({ name: "ci", on: "push" }, { comment: "Top comment" });
    const yaml = toYaml(m, { header: null });
    const lines = yaml.split("\n");
    const commentIdx = lines.findIndex((l) => l.includes("# Top comment"));
    const nameIdx = lines.findIndex((l) => l.startsWith("name:"));
    expect(commentIdx).toBeGreaterThanOrEqual(0);
    expect(commentIdx).toBeLessThan(nameIdx);
  });

  it("model-level eolComment attaches to the last value", () => {
    const m = simpleModel({ alpha: 1, zulu: 2 }, { eolComment: "end of block" });
    const yaml = toYaml(m, { header: null });
    expect(yaml).toMatch(/zulu: 2\s+# end of block/);
  });
});

// ---------------------------------------------------------------------------
// postProcess
// ---------------------------------------------------------------------------
describe("postProcess", () => {
  it("callback can add pairs to the YAMLMap", () => {
    const m = simpleModel(
      { name: "ci" },
      {
        postProcess: (node: YAMLMap) => {
          node.items.push(new Pair(new Scalar("injected"), new Scalar("yes")));
        },
      },
    );
    const yaml = toYaml(m, { header: null });
    expect(yaml).toContain("injected: yes");
  });
});

// ---------------------------------------------------------------------------
// Value conversion
// ---------------------------------------------------------------------------
describe("value conversion", () => {
  it("multiline string ending with newline uses block literal |", () => {
    const m = simpleModel({ script: "echo hello\necho world\n" });
    const yaml = toYaml(m, { header: null });
    expect(yaml).toContain("script: |\n");
  });

  it("multiline string without trailing newline uses strip |-", () => {
    const m = simpleModel({ script: "echo hello\necho world" });
    const yaml = toYaml(m, { header: null });
    expect(yaml).toContain("script: |-\n");
  });

  it("single-line string is plain (no block indicator)", () => {
    const m = simpleModel({ name: "ci" });
    const yaml = toYaml(m, { header: null });
    expect(yaml).toContain("name: ci");
    expect(yaml).not.toMatch(/name: [|>]/);
  });

  it("raw() values are unwrapped as plain scalars", () => {
    const m = simpleModel({ expr: raw("${{ github.event }}") });
    const yaml = toYaml(m, { header: null });
    expect(yaml).toContain("expr: ${{ github.event }}");
  });

  it("nested model produces a recursive YAMLMap", () => {
    const inner = simpleModel({ image: "node:20" }, {}, ["image"]);
    const outer = simpleModel({ container: inner }, {}, ["container"]);
    const yaml = toYaml(outer, { header: null });
    expect(yaml).toContain("container:");
    expect(yaml).toContain("  image: node:20");
  });

  it("array produces a YAML sequence", () => {
    const m = simpleModel({ items: ["a", "b", "c"] });
    const yaml = toYaml(m, { header: null });
    expect(yaml).toContain("- a");
    expect(yaml).toContain("- b");
    expect(yaml).toContain("- c");
  });

  it("plain object produces a nested map", () => {
    const m = simpleModel({ env: { NODE_ENV: "production" } });
    const yaml = toYaml(m, { header: null });
    expect(yaml).toContain("env:");
    expect(yaml).toContain("  NODE_ENV: production");
  });

  it("null value is serialized as a null entry", () => {
    const m = simpleModel({ empty: null });
    const yaml = toYaml(m, { header: null });
    expect(yaml).toContain("? empty");
  });

  it("undefined value is serialized as a null entry", () => {
    const m = simpleModel({ empty: undefined });
    const yaml = toYaml(m, { header: null });
    expect(yaml).toContain("? empty");
  });
});

// ---------------------------------------------------------------------------
// toYamlFile
// ---------------------------------------------------------------------------
describe("toYamlFile()", () => {
  it("writes YAML to disk matching toYaml() output", () => {
    const dir = mkdtempSync(join(tmpdir(), "ghagen-test-"));
    try {
      const m = simpleModel({ name: "ci" });
      const filePath = join(dir, "workflow.yml");
      toYamlFile(m, filePath);
      const contents = readFileSync(filePath, "utf-8");
      expect(contents).toBe(toYaml(m));
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });
});
